using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

// This file is automatically generated, DO NOT EDIT

namespace WowPacketParserModule.V9_0_1_36216.UpdateFields.V9_0_5_37862
{
    public class VisibleItem : IVisibleItem
    {
        public int ItemID { get; set; }
        public int ItemModifiedAppearanceID { get; set; }
        public ushort ItemAppearanceModID { get; set; }
        public ushort ItemVisual { get; set; }
    }
}

