using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

// This file is automatically generated, DO NOT EDIT

namespace WowPacketParserModule.V10_0_0_46181.UpdateFields.V10_1_7_51187
{
    public class CategoryCooldownMod : ICategoryCooldownMod
    {
        public int SpellCategoryID { get; set; }
        public int ModCooldown { get; set; }
    }
}

