using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

// This file is automatically generated, DO NOT EDIT

namespace WowPacketParserModule.V10_0_0_46181.UpdateFields.V10_1_7_51187
{
    public class ItemModList : IItemModList
    {
        public DynamicUpdateField<IItemMod> Values { get; } = new DynamicUpdateField<IItemMod>();
    }
}

