using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

// This file is automatically generated, DO NOT EDIT

namespace WowPacketParserModule.V10_0_0_46181.UpdateFields.V10_1_7_51187
{
    public class VisualAnim : IVisualAnim
    {
        public System.Nullable<uint> AnimationDataID { get; set; }
        public System.Nullable<uint> AnimKitID { get; set; }
        public System.Nullable<uint> AnimProgress { get; set; }
        public System.Nullable<bool> IsDecay { get; set; }
    }
}

