using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

// This file is automatically generated, DO NOT EDIT

namespace WowPacketParserModule.V4_4_0_54481.UpdateFields.V4_4_0_54481
{
    public class ConversationActor : IConversationActor
    {
        public int Id { get; set; }
        public uint CreatureID { get; set; }
        public uint CreatureDisplayInfoID { get; set; }
        public WowGuid ActorGUID { get; set; }
        public uint Type { get; set; }
        public uint NoActorObject { get; }
    }
}

