// <auto-generated>
// DO NOT EDIT
// </auto-generated>

using System.CodeDom.Compiler;
using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

namespace WowPacketParserModule.V12_0_0_65390.UpdateFields.V12_0_1_65818
{
    [GeneratedCode("UpdateFieldCodeGenerator.Formats.WowPacketParserHandler", "1.0.0.0")]
    public class AreaTriggerDisk : IAreaTriggerDisk
    {
        public System.Nullable<float> InnerRadius { get; set; }
        public System.Nullable<float> InnerRadiusTarget { get; set; }
        public System.Nullable<float> OuterRadius { get; set; }
        public System.Nullable<float> OuterRadiusTarget { get; set; }
        public System.Nullable<float> Height { get; set; }
        public System.Nullable<float> HeightTarget { get; set; }
        public System.Nullable<float> LocationZOffset { get; set; }
        public System.Nullable<float> LocationZOffsetTarget { get; set; }
    }
}

