// <auto-generated>
// DO NOT EDIT
// </auto-generated>

using System.CodeDom.Compiler;
using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

namespace WowPacketParserModule.V12_0_0_65390.UpdateFields.V12_0_1_65818
{
    [GeneratedCode("UpdateFieldCodeGenerator.Formats.WowPacketParserHandler", "1.0.0.0")]
    public class HousingFixtureData : IHousingFixtureData
    {
        public System.Nullable<int> ExteriorComponentID { get; set; }
        public System.Nullable<int> HouseExteriorWmoDataID { get; set; }
        public System.Nullable<int> ExteriorComponentHookID { get; set; }
        public WowGuid HouseGUID { get; set; }
        public WowGuid AttachParentGUID { get; set; }
        public WowGuid Guid { get; set; }
        public WowGuid GameObjectGUID { get; set; }
        public System.Nullable<byte> ExteriorComponentType { get; set; }
        public System.Nullable<byte> Field_59 { get; set; }
        public System.Nullable<byte> Size { get; set; }
    }
}

