// <auto-generated>
// DO NOT EDIT
// </auto-generated>

using System.CodeDom.Compiler;
using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

namespace WowPacketParserModule.V12_0_0_65390.UpdateFields.V12_0_1_65818
{
    [GeneratedCode("UpdateFieldCodeGenerator.Formats.WowPacketParserHandler", "1.0.0.0")]
    public class HousingCornerstoneData : IHousingCornerstoneData
    {
        public System.Nullable<ulong> Cost { get; set; }
        public System.Nullable<int> PlotIndex { get; set; }
    }
}

