// <auto-generated>
// DO NOT EDIT
// </auto-generated>

using System.CodeDom.Compiler;
using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

namespace WowPacketParserModule.V12_0_0_65390.UpdateFields.V12_0_1_65818
{
    [GeneratedCode("UpdateFieldCodeGenerator.Formats.WowPacketParserHandler", "1.0.0.0")]
    public class MirroredMeshObjectData : IMirroredMeshObjectData
    {
        public WowGuid AttachParentGUID { get; set; }
        public System.Nullable<Vector3> PositionLocalSpace { get; set; }
        public System.Nullable<Quaternion> RotationLocalSpace { get; set; }
        public System.Nullable<float> ScaleLocalSpace { get; set; }
        public System.Nullable<byte> AttachmentFlags { get; set; }
    }
}

