// <auto-generated>
// DO NOT EDIT
// </auto-generated>

using System.CodeDom.Compiler;
using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

namespace WowPacketParserModule.V12_0_0_65390.UpdateFields.V12_0_1_65818
{
    [GeneratedCode("UpdateFieldCodeGenerator.Formats.WowPacketParserHandler", "1.0.0.0")]
    public class PlayerInitiativeInfo : IPlayerInitiativeInfo
    {
        public System.Nullable<long> RemainingDuration { get; set; }
        public System.Nullable<int> CurrentInitiativeID { get; set; }
        public System.Nullable<int> CurrentMilestoneID { get; set; }
        public System.Nullable<int> CurrentCycleID { get; set; }
        public System.Nullable<float> ProgressRequired { get; set; }
        public System.Nullable<float> CurrentProgress { get; set; }
        public System.Nullable<float> PlayerTotalContribution { get; set; }
    }
}

