// <auto-generated>
// DO NOT EDIT
// </auto-generated>

using System.CodeDom.Compiler;
using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

namespace WowPacketParserModule.V11_0_0_55666.UpdateFields.V11_1_7_61491
{
    [GeneratedCode("UpdateFieldCodeGenerator.Formats.WowPacketParserHandler", "1.0.0.0")]
    public class CTROptions : ICTROptions
    {
        public uint ConditionalFlags { get; set; }
        public byte FactionGroup { get; set; }
        public uint ChromieTimeExpansionMask { get; set; }
    }
}

