// <auto-generated>
// DO NOT EDIT
// </auto-generated>

using System.CodeDom.Compiler;
using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

namespace WowPacketParserModule.V11_0_0_55666.UpdateFields.V11_1_5_60392
{
    [GeneratedCode("UpdateFieldCodeGenerator.Formats.WowPacketParserHandler", "1.0.0.0")]
    public class NPCCraftingOrderInfo : INPCCraftingOrderInfo
    {
        public System.Nullable<ulong> OrderID { get; set; }
        public System.Nullable<int> NpcCraftingOrderSetID { get; set; }
        public System.Nullable<int> NpcTreasureID { get; set; }
        public System.Nullable<int> NpcCraftingOrderCustomerID { get; set; }
    }
}

