version: 1.0.{build}
image:
- Visual Studio 2026
# - Ubuntu
# - macOS
configuration:
- Debug
- Release
platform: Any CPU
clone_depth: 1
environment:
  DOTNET_NOLOGO: true
  DOTNET_GENERATE_ASPNET_CERTIFICATE: false
  DOTNET_CLI_TELEMETRY_OPTOUT: true
before_build:
- ps: dotnet restore
build:
  verbosity: minimal
  project: WowPacketParser.slnx
artifacts:
- path: WowPacketParser\bin
  name: WPP
