// <auto-generated>
// DO NOT EDIT
// </auto-generated>

using System.CodeDom.Compiler;
using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

namespace WowPacketParserModule.V5_5_0_61735.UpdateFields.V5_5_1_63311
{
    [GeneratedCode("UpdateFieldCodeGenerator.Formats.WowPacketParserHandler", "1.0.0.0")]
    public class TraitConfig : ITraitConfig
    {
        public System.Nullable<int> ID { get; set; }
        public System.Nullable<int> Type { get; set; }
        public System.Nullable<int> SkillLineID { get; set; }
        public System.Nullable<int> ChrSpecializationID { get; set; }
        public System.Nullable<int> CombatConfigFlags { get; set; }
        public System.Nullable<int> LocalIdentifier { get; set; }
        public System.Nullable<int> TraitSystemID { get; set; }
        public DynamicUpdateField<ITraitEntry> Entries { get; } = new DynamicUpdateField<ITraitEntry>();
        public string Name { get; set; }
        public DynamicUpdateField<ITraitSubTreeCache> SubTrees { get; } = new DynamicUpdateField<ITraitSubTreeCache>();
    }
}

