using WowPacketParser.Store.Objects.UpdateFields;

// This file is automatically generated, DO NOT EDIT

namespace WowPacketParserModule.V9_0_1_36216.UpdateFields.V9_1_0_39185
{
    public class ReplayedQuest : IReplayedQuest
    {
        public int QuestID { get; set; }
        public uint ReplayTime { get; set; }
    }
}

