using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

// This file is automatically generated, DO NOT EDIT

namespace WowPacketParserModule.V2_5_1_38707.UpdateFields.V1_14_3_42770
{
    public class RestInfo : IRestInfo
    {
        public uint Threshold { get; set; }
        public byte StateID { get; set; }
    }
}

