// <auto-generated>
// DO NOT EDIT
// </auto-generated>

using System.CodeDom.Compiler;
using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

namespace WowPacketParserModule.V4_4_0_54481.UpdateFields.V4_4_2_59185
{
    [GeneratedCode("UpdateFieldCodeGenerator.Formats.WowPacketParserHandler", "1.0.0.0")]
    public class ItemEnchantment : IItemEnchantment
    {
        public System.Nullable<int> ID { get; set; }
        public System.Nullable<uint> Duration { get; set; }
        public System.Nullable<short> Charges { get; set; }
        public System.Nullable<ushort> Inactive { get; set; }
    }
}

