using WowPacketParser.Misc;

namespace WowPacketParser.Enums.Version.V1_14_4_51146
{
    public static class Opcodes_1_14_4
    {
        public static BiDictionary<Opcode, int> Opcodes(Direction direction)
        {
            switch (direction)
            {
                case Direction.ClientToServer:
                    return ClientOpcodes;
                case Direction.ServerToClient:
                    return ServerOpcodes;
                default:
                    return MiscOpcodes;
            }
        }

        private static readonly BiDictionary<Opcode, int> ClientOpcodes = new()
        {
            // GROUP: CliGlobal

            {Opcode.CMSG_GUILD_PROMOTE_MEMBER, 0x305D},
            {Opcode.CMSG_GUILD_DEMOTE_MEMBER, 0x305E},
            {Opcode.CMSG_GUILD_ASSIGN_MEMBER_RANK, 0x305F},
            {Opcode.CMSG_GUILD_DECLINE_INVITATION, 0x3060},
            {Opcode.CMSG_GUILD_AUTO_DECLINE_INVITATION, 0x3061},
            {Opcode.CMSG_GUILD_LEAVE, 0x3062},
            {Opcode.CMSG_GUILD_OFFICER_REMOVE_MEMBER, 0x3063},
            {Opcode.CMSG_GUILD_ADD_RANK, 0x3064},
            {Opcode.CMSG_GUILD_DELETE_RANK, 0x3065},
            {Opcode.CMSG_GUILD_SHIFT_RANK, 0x3066},
            {Opcode.CMSG_GUILD_SET_RANK_PERMISSIONS, 0x3067},
            {Opcode.CMSG_GUILD_DELETE, 0x3068},
            {Opcode.CMSG_GUILD_QUERY_MEMBERS_FOR_RECIPE, 0x306B},
            {Opcode.CMSG_GUILD_GET_RANKS, 0x306D},
            {Opcode.CMSG_GUILD_SET_ACHIEVEMENT_TRACKING, 0x306F},
            {Opcode.CMSG_GUILD_SET_MEMBER_NOTE, 0x3072},
            {Opcode.CMSG_GUILD_GET_ROSTER, 0x3073},
            {Opcode.CMSG_GUILD_UPDATE_MOTD_TEXT, 0x3074},
            {Opcode.CMSG_GUILD_UPDATE_INFO_TEXT, 0x3075},
            {Opcode.CMSG_GUILD_CHANGE_NAME_REQUEST, 0x307E},
            {Opcode.CMSG_GUILD_BANK_LOG_QUERY, 0x3082},
            {Opcode.CMSG_GUILD_BANK_REMAINING_WITHDRAW_MONEY_QUERY, 0x3083},
            {Opcode.CMSG_GUILD_PERMISSIONS_QUERY, 0x3084},
            {Opcode.CMSG_GUILD_EVENT_LOG_QUERY, 0x3085},
            {Opcode.CMSG_GUILD_BANK_SET_TAB_TEXT, 0x3086},
            {Opcode.CMSG_GUILD_BANK_TEXT_QUERY, 0x3087},
            {Opcode.CMSG_GUILD_REPLACE_GUILD_MASTER, 0x3088},
            // {Opcode.UNNAMED, 0x308C},
            // {Opcode.UNNAMED, 0x308D},

            // GROUP: CliAccount

            {Opcode.CMSG_TWITTER_CONNECT, 0x3127},
            // {Opcode.UNNAMED, 0x3128},
            // {Opcode.UNNAMED, 0x3129},
            {Opcode.CMSG_TWITTER_CHECK_STATUS, 0x312A},
            {Opcode.CMSG_TWITTER_DISCONNECT, 0x312B},

            // GROUP: CliPlayer

            {Opcode.CMSG_INITIATE_TRADE, 0x3156},
            {Opcode.CMSG_BEGIN_TRADE, 0x3157},
            {Opcode.CMSG_BUSY_TRADE, 0x3158},
            {Opcode.CMSG_IGNORE_TRADE, 0x3159},
            {Opcode.CMSG_ACCEPT_TRADE, 0x315A},
            {Opcode.CMSG_UNACCEPT_TRADE, 0x315B},
            {Opcode.CMSG_CANCEL_TRADE, 0x315C},
            {Opcode.CMSG_SET_TRADE_ITEM, 0x315D},
            {Opcode.CMSG_CLEAR_TRADE_ITEM, 0x315E},
            {Opcode.CMSG_SET_TRADE_GOLD, 0x315F},
            {Opcode.CMSG_STABLE_PET, 0x3169},
            {Opcode.CMSG_UNSTABLE_PET, 0x316A},
            {Opcode.CMSG_STABLE_SWAP_PET, 0x316B},
            {Opcode.CMSG_BUY_STABLE_SLOT, 0x316C},
            // {Opcode.UNNAMED, 0x316D},
            {Opcode.CMSG_BATTLEFIELD_LEAVE, 0x3176},
            {Opcode.CMSG_QUERY_QUEST_COMPLETION_NPCS, 0x3178},
            // {Opcode.UNNAMED, 0x3179},
            {Opcode.CMSG_REQUEST_CEMETERY_LIST, 0x317A},
            {Opcode.CMSG_SET_PREFERRED_CEMETERY, 0x317B},
            {Opcode.CMSG_INSPECT_HONOR_STATS, 0x317F},
            {Opcode.CMSG_PVP_LOG_DATA, 0x3180},
            {Opcode.CMSG_REQUEST_CATEGORY_COOLDOWNS, 0x3182},
            {Opcode.CMSG_BATTLEFIELD_LIST, 0x3183},
            {Opcode.CMSG_CANCEL_QUEUED_SPELL, 0x3184},
            {Opcode.CMSG_OBJECT_UPDATE_FAILED, 0x3185},
            {Opcode.CMSG_OBJECT_UPDATE_RESCUED, 0x3186},
            {Opcode.CMSG_VIOLENCE_LEVEL, 0x3189},
            {Opcode.CMSG_USED_FOLLOW, 0x318B},
            {Opcode.CMSG_STAND_STATE_CHANGE, 0x318E},
            {Opcode.CMSG_MISSILE_TRAJECTORY_COLLISION, 0x318F},
            {Opcode.CMSG_SAVE_CUF_PROFILES, 0x3190},
            // {Opcode.UNNAMED, 0x3198},
            // {Opcode.UNNAMED, 0x3199},
            {Opcode.CMSG_UNLOCK_VOID_STORAGE, 0x31A4},
            {Opcode.CMSG_QUERY_VOID_STORAGE, 0x31A5},
            {Opcode.CMSG_VOID_STORAGE_TRANSFER, 0x31A6},
            {Opcode.CMSG_SWAP_VOID_ITEM, 0x31A7},
            {Opcode.CMSG_QUERY_COUNTDOWN_TIMER, 0x31AC},
            {Opcode.CMSG_CANCEL_AURA, 0x31B1},
            {Opcode.CMSG_GAME_EVENT_DEBUG_ENABLE, 0x31B3},
            {Opcode.CMSG_GAME_EVENT_DEBUG_DISABLE, 0x31B4},
            // {Opcode.UNNAMED, 0x31BB},
            // {Opcode.UNNAMED, 0x31BC},
            {Opcode.CMSG_AREA_TRIGGER, 0x31D8},
            {Opcode.CMSG_BATTLE_PET_UPDATE_NOTIFY, 0x31E1},
            {Opcode.CMSG_BATTLE_PET_UPDATE_DISPLAY_NOTIFY, 0x31E2},
            {Opcode.CMSG_REQUEST_FORCED_REACTIONS, 0x3207},
            {Opcode.CMSG_ASSIGN_EQUIPMENT_SET_SPEC, 0x3209},
            // {Opcode.UNNAMED, 0x320F},
            {Opcode.CMSG_CONFIRM_RESPEC_WIPE, 0x3210},
            {Opcode.CMSG_LOOT_UNIT, 0x3211},
            {Opcode.CMSG_LOOT_MONEY, 0x3212},
            {Opcode.CMSG_LOOT_ITEM, 0x3213},
            {Opcode.CMSG_LOOT_MASTER_GIVE, 0x3214},
            {Opcode.CMSG_LOOT_RELEASE, 0x3215},
            {Opcode.CMSG_LOOT_ROLL, 0x3216},
            {Opcode.CMSG_SCENE_PLAYBACK_COMPLETE, 0x3221},
            {Opcode.CMSG_SCENE_PLAYBACK_CANCELED, 0x3222},
            {Opcode.CMSG_SCENE_TRIGGER_EVENT, 0x3223},
            {Opcode.CMSG_SET_DIFFICULTY_ID, 0x3224},
            {Opcode.CMSG_KEYBOUND_OVERRIDE, 0x3225},
            {Opcode.CMSG_MAIL_DELETE, 0x3227},
            {Opcode.CMSG_REQUEST_VEHICLE_EXIT, 0x3237},
            {Opcode.CMSG_REQUEST_VEHICLE_PREV_SEAT, 0x3238},
            {Opcode.CMSG_REQUEST_VEHICLE_NEXT_SEAT, 0x3239},
            {Opcode.CMSG_REQUEST_VEHICLE_SWITCH_SEAT, 0x323A},
            {Opcode.CMSG_RIDE_VEHICLE_INTERACT, 0x323B},
            {Opcode.CMSG_EJECT_PASSENGER, 0x323C},
            {Opcode.CMSG_USE_CRITTER_ITEM, 0x3241},
            {Opcode.CMSG_CHECK_IS_ADVENTURE_MAP_POI_VALID, 0x3247},
            {Opcode.CMSG_ATTACK_SWING, 0x3255},
            {Opcode.CMSG_ATTACK_STOP, 0x3256},
            {Opcode.CMSG_CANCEL_CHANNELLING, 0x326A},
            {Opcode.CMSG_CANCEL_GROWTH_AURA, 0x326F},
            {Opcode.CMSG_QUERY_CREATURE, 0x3270},
            {Opcode.CMSG_QUERY_GAME_OBJECT, 0x3271},
            {Opcode.CMSG_QUERY_NPC_TEXT, 0x3272},
            {Opcode.CMSG_QUERY_QUEST_INFO, 0x3273},
            {Opcode.CMSG_QUERY_PAGE_TEXT, 0x3274},
            {Opcode.CMSG_QUERY_PET_NAME, 0x3275},
            {Opcode.CMSG_QUERY_BATTLE_PET_NAME, 0x3276},
            {Opcode.CMSG_QUERY_PETITION, 0x3277},
            {Opcode.CMSG_REQUEST_PLAYED_TIME, 0x327A},
            {Opcode.CMSG_SET_TITLE, 0x327E},
            {Opcode.CMSG_CANCEL_MOUNT_AURA, 0x327F},
            {Opcode.CMSG_MOUNT_SPECIAL_ANIM, 0x3280},
            {Opcode.CMSG_DESTROY_ITEM, 0x3292},
            {Opcode.CMSG_GET_MIRROR_IMAGE_DATA, 0x3296},
            {Opcode.CMSG_USE_ITEM, 0x3297},
            // {Opcode.UNNAMED, 0x3298},
            // {Opcode.UNNAMED, 0x3299},
            {Opcode.CMSG_PET_CAST_SPELL, 0x329A},
            {Opcode.CMSG_CAST_SPELL, 0x329B},
            {Opcode.CMSG_UPDATE_SPELL_VISUAL, 0x329C},
            {Opcode.CMSG_UPDATE_AREA_TRIGGER_VISUAL, 0x329D},
            {Opcode.CMSG_CANCEL_CAST, 0x329E},
            {Opcode.CMSG_CLOSE_QUEST_CHOICE, 0x32A1},
            {Opcode.CMSG_REQUEST_LFG_LIST_BLACKLIST, 0x32A3},
            {Opcode.CMSG_SAVE_GUILD_EMBLEM, 0x32A7},
            {Opcode.CMSG_TABARD_VENDOR_ACTIVATE, 0x32A8},
            {Opcode.CMSG_TOGGLE_PVP, 0x32AA},
            {Opcode.CMSG_SET_PVP, 0x32AB},
            {Opcode.CMSG_BATTLEMASTER_HELLO, 0x32B0},
            {Opcode.CMSG_REQUEST_CONQUEST_FORMULA_CONSTANTS, 0x32B3},
            {Opcode.CMSG_SET_ADVANCED_COMBAT_LOGGING, 0x32B4},
            {Opcode.CMSG_ITEM_TEXT_QUERY, 0x32C4},
            {Opcode.CMSG_OPEN_ITEM, 0x32C5},
            {Opcode.CMSG_READ_ITEM, 0x32C6},
            {Opcode.CMSG_CHANGE_BAG_SLOT_FLAG, 0x32C7},
            {Opcode.CMSG_CHANGE_BANK_BAG_SLOT_FLAG, 0x32C8},
            // {Opcode.UNNAMED, 0x32C9},
            // {Opcode.UNNAMED, 0x32D8},
            {Opcode.CMSG_QUERY_TREASURE_PICKER, 0x32DB},
            {Opcode.CMSG_REQUEST_WORLD_QUEST_UPDATE, 0x32DC},
            {Opcode.CMSG_REQUEST_AREA_POI_UPDATE, 0x32DD},
            {Opcode.CMSG_REMOVE_NEW_ITEM, 0x32DE},
            // {Opcode.UNNAMED, 0x32DF},
            // {Opcode.UNNAMED, 0x32EF},
            // {Opcode.UNNAMED, 0x32F0},
            // {Opcode.UNNAMED, 0x32F1},
            // {Opcode.UNNAMED, 0x32F2},
            // {Opcode.UNNAMED, 0x32F3},
            {Opcode.CMSG_REPORT_SERVER_LAG, 0x32FA},
            {Opcode.CMSG_OFFER_PETITION, 0x32FC},
            // {Opcode.UNNAMED, 0x3300},
            // {Opcode.UNNAMED, 0x3301},
            // {Opcode.UNNAMED, 0x3302},
            // {Opcode.UNNAMED, 0x3303},
            // {Opcode.UNNAMED, 0x330E},

            // GROUP: CliPlayerGameEvent

            {Opcode.CMSG_SEND_TEXT_EMOTE, 0x3488},
            {Opcode.CMSG_SET_SHEATHED, 0x3489},
            {Opcode.CMSG_PET_SET_ACTION, 0x348A},
            {Opcode.CMSG_PET_ACTION, 0x348B},
            {Opcode.CMSG_PET_STOP_ATTACK, 0x348C},
            {Opcode.CMSG_PET_ABANDON, 0x348D},
            {Opcode.CMSG_PET_CANCEL_AURA, 0x348E},
            {Opcode.CMSG_PET_SPELL_AUTOCAST, 0x348F},
            {Opcode.CMSG_REQUEST_PET_INFO, 0x3490},
            {Opcode.CMSG_REQUEST_STABLED_PETS, 0x3491},
            {Opcode.CMSG_TALK_TO_GOSSIP, 0x3492},
            {Opcode.CMSG_CLOSE_INTERACTION, 0x3493},
            {Opcode.CMSG_GOSSIP_SELECT_OPTION, 0x3494},
            {Opcode.CMSG_SPELL_CLICK, 0x3495},
            {Opcode.CMSG_QUEST_GIVER_HELLO, 0x3496},
            {Opcode.CMSG_QUEST_GIVER_QUERY_QUEST, 0x3497},
            {Opcode.CMSG_QUEST_GIVER_ACCEPT_QUEST, 0x3498},
            {Opcode.CMSG_QUEST_GIVER_COMPLETE_QUEST, 0x3499},
            {Opcode.CMSG_QUEST_GIVER_CHOOSE_REWARD, 0x349A},
            {Opcode.CMSG_QUEST_GIVER_REQUEST_REWARD, 0x349B},
            {Opcode.CMSG_QUEST_GIVER_STATUS_QUERY, 0x349C},
            {Opcode.CMSG_QUEST_GIVER_STATUS_MULTIPLE_QUERY, 0x349D},
            {Opcode.CMSG_QUEST_CONFIRM_ACCEPT, 0x349E},
            {Opcode.CMSG_PUSH_QUEST_TO_PARTY, 0x349F},
            {Opcode.CMSG_QUEST_PUSH_RESULT, 0x34A0},
            {Opcode.CMSG_LIST_INVENTORY, 0x34A1},
            {Opcode.CMSG_SELL_ITEM, 0x34A2},
            {Opcode.CMSG_BUY_ITEM, 0x34A3},
            {Opcode.CMSG_BUY_BACK_ITEM, 0x34A4},
            {Opcode.CMSG_TAXI_NODE_STATUS_QUERY, 0x34A8},
            {Opcode.CMSG_ENABLE_TAXI_NODE, 0x34A9},
            {Opcode.CMSG_TAXI_QUERY_AVAILABLE_NODES, 0x34AA},
            {Opcode.CMSG_ACTIVATE_TAXI, 0x34AB},
            {Opcode.CMSG_TAXI_REQUEST_EARLY_LANDING, 0x34AC},
            {Opcode.CMSG_TRAINER_LIST, 0x34AD},
            {Opcode.CMSG_TRAINER_BUY_SPELL, 0x34AE},
            {Opcode.CMSG_SPIRIT_HEALER_ACTIVATE, 0x34AF},
            {Opcode.CMSG_AREA_SPIRIT_HEALER_QUERY, 0x34B0},
            {Opcode.CMSG_AREA_SPIRIT_HEALER_QUEUE, 0x34B1},
            {Opcode.CMSG_BINDER_ACTIVATE, 0x34B2},
            {Opcode.CMSG_BANKER_ACTIVATE, 0x34B3},
            {Opcode.CMSG_BUY_BANK_SLOT, 0x34B4},
            {Opcode.CMSG_GUILD_BANK_ACTIVATE, 0x34B5},
            {Opcode.CMSG_AUTO_GUILD_BANK_ITEM, 0x34B6},
            {Opcode.CMSG_STORE_GUILD_BANK_ITEM, 0x34B7},
            {Opcode.CMSG_SWAP_ITEM_WITH_GUILD_BANK_ITEM, 0x34B8},
            {Opcode.CMSG_SWAP_GUILD_BANK_ITEM_WITH_GUILD_BANK_ITEM, 0x34B9},
            {Opcode.CMSG_MOVE_GUILD_BANK_ITEM, 0x34BA},
            {Opcode.CMSG_MERGE_ITEM_WITH_GUILD_BANK_ITEM, 0x34BB},
            {Opcode.CMSG_SPLIT_ITEM_TO_GUILD_BANK, 0x34BC},
            {Opcode.CMSG_MERGE_GUILD_BANK_ITEM_WITH_ITEM, 0x34BD},
            {Opcode.CMSG_SPLIT_GUILD_BANK_ITEM_TO_INVENTORY, 0x34BE},
            {Opcode.CMSG_AUTO_STORE_GUILD_BANK_ITEM, 0x34BF},
            {Opcode.CMSG_MERGE_GUILD_BANK_ITEM_WITH_GUILD_BANK_ITEM, 0x34C0},
            {Opcode.CMSG_SPLIT_GUILD_BANK_ITEM, 0x34C1},
            {Opcode.CMSG_GUILD_BANK_QUERY_TAB, 0x34C2},
            {Opcode.CMSG_GUILD_BANK_BUY_TAB, 0x34C3},
            {Opcode.CMSG_GUILD_BANK_UPDATE_TAB, 0x34C4},
            {Opcode.CMSG_GUILD_BANK_DEPOSIT_MONEY, 0x34C5},
            {Opcode.CMSG_GUILD_BANK_WITHDRAW_MONEY, 0x34C6},
            {Opcode.CMSG_PETITION_SHOW_LIST, 0x34C7},
            {Opcode.CMSG_PETITION_BUY, 0x34C8},
            {Opcode.CMSG_PETITION_SHOW_SIGNATURES, 0x34C9},
            {Opcode.CMSG_AUCTION_HELLO_REQUEST, 0x34CA},
            {Opcode.CMSG_AUCTION_SELL_ITEM, 0x34CB},
            {Opcode.CMSG_AUCTION_REMOVE_ITEM, 0x34CC},
            {Opcode.CMSG_AUCTION_LIST_ITEMS, 0x34CD},
            {Opcode.CMSG_AUCTION_REPLICATE_ITEMS, 0x34CE},
            {Opcode.CMSG_AUCTION_LIST_OWNED_ITEMS, 0x34CF},
            {Opcode.CMSG_AUCTION_LIST_BIDDED_ITEMS, 0x34D0},
            {Opcode.CMSG_AUCTION_PLACE_BID, 0x34D1},
            {Opcode.CMSG_AUCTION_LIST_PENDING_SALES, 0x34D2},
            {Opcode.CMSG_QUERY_TIME, 0x34D5},
            {Opcode.CMSG_LOGOUT_REQUEST, 0x34D6},
            {Opcode.CMSG_LOGOUT_CANCEL, 0x34D8},
            {Opcode.CMSG_LOGOUT_INSTANT, 0x34D9},
            {Opcode.CMSG_RECLAIM_CORPSE, 0x34DB},
            {Opcode.CMSG_COMPLETE_MOVIE, 0x34DD},
            {Opcode.CMSG_SET_FACTION_AT_WAR, 0x34DE},
            {Opcode.CMSG_SET_FACTION_NOT_AT_WAR, 0x34DF},
            {Opcode.CMSG_SET_FACTION_INACTIVE, 0x34E0},
            {Opcode.CMSG_SET_WATCHED_FACTION, 0x34E1},
            {Opcode.CMSG_DUEL_RESPONSE, 0x34E2},
            {Opcode.CMSG_UNLEARN_SKILL, 0x34E5},
            {Opcode.CMSG_CANCEL_AUTO_REPEAT_SPELL, 0x34E7},
            {Opcode.CMSG_FAR_SIGHT, 0x34E8},
            {Opcode.CMSG_SOCKET_GEMS, 0x34EB},
            {Opcode.CMSG_REPAIR_ITEM, 0x34EC},
            {Opcode.CMSG_GAME_OBJ_USE, 0x34EE},
            {Opcode.CMSG_GAME_OBJ_REPORT_USE, 0x34EF},
            {Opcode.CMSG_CANCEL_TEMP_ENCHANTMENT, 0x34F2},
            {Opcode.CMSG_SET_TAXI_BENCHMARK_MODE, 0x34F3},
            {Opcode.CMSG_REPORT_PVP_PLAYER_AFK, 0x34F4},
            {Opcode.CMSG_ALTER_APPEARANCE, 0x34F5},
            {Opcode.CMSG_OPT_OUT_OF_LOOT, 0x34F6},
            {Opcode.CMSG_TOTEM_DESTROYED, 0x34F8},
            {Opcode.CMSG_DISMISS_CRITTER, 0x34F9},
            {Opcode.CMSG_QUERY_INSPECT_ACHIEVEMENTS, 0x3500},
            {Opcode.CMSG_HEARTH_AND_RESURRECT, 0x3506},
            {Opcode.CMSG_SAVE_EQUIPMENT_SET, 0x3509},
            {Opcode.CMSG_DELETE_EQUIPMENT_SET, 0x350A},
            {Opcode.CMSG_INSTANCE_LOCK_RESPONSE, 0x350B},
            {Opcode.CMSG_LOW_LEVEL_RAID2, 0x3512},
            {Opcode.CMSG_DECLINE_GUILD_INVITES, 0x351D},
            {Opcode.CMSG_OVERRIDE_SCREEN_FLASH, 0x351E},
            {Opcode.CMSG_BATTLEMASTER_JOIN, 0x3520},
            {Opcode.CMSG_BATTLEMASTER_JOIN_ARENA, 0x3521},
            {Opcode.CMSG_BATTLEMASTER_JOIN_SKIRMISH, 0x3522},
            {Opcode.CMSG_BATTLEFIELD_PORT, 0x3525},
            {Opcode.CMSG_REPOP_REQUEST, 0x3526},
            {Opcode.CMSG_SET_SELECTION, 0x3528},
            {Opcode.CMSG_INSPECT, 0x3529},
            {Opcode.CMSG_REQUEST_CROWD_CONTROL_SPELL, 0x352A},
            {Opcode.CMSG_BLACK_MARKET_OPEN, 0x352B},
            {Opcode.CMSG_QUEST_LOG_REMOVE_QUEST, 0x352E},
            {Opcode.CMSG_GET_ITEM_PURCHASE_DATA, 0x352F},
            {Opcode.CMSG_ITEM_PURCHASE_REFUND, 0x3530},
            {Opcode.CMSG_SELF_RES, 0x3531},
            {Opcode.CMSG_SET_ACTION_BAR_TOGGLES, 0x3532},
            {Opcode.CMSG_SIGN_PETITION, 0x3533},
            {Opcode.CMSG_DECLINE_PETITION, 0x3534},
            {Opcode.CMSG_TURN_IN_PETITION, 0x3535},
            {Opcode.CMSG_MAIL_GET_LIST, 0x3536},
            {Opcode.CMSG_MAIL_TAKE_MONEY, 0x3537},
            {Opcode.CMSG_MAIL_TAKE_ITEM, 0x3538},
            {Opcode.CMSG_QUERY_NEXT_MAIL_TIME, 0x3539},
            {Opcode.CMSG_MAIL_MARK_AS_READ, 0x353A},
            {Opcode.CMSG_MAIL_CREATE_TEXT_ITEM, 0x353B},
            {Opcode.CMSG_EMOTE, 0x3541},
            {Opcode.CMSG_OPENING_CINEMATIC, 0x3543},
            {Opcode.CMSG_NEXT_CINEMATIC_CAMERA, 0x3544},
            {Opcode.CMSG_COMPLETE_CINEMATIC, 0x3545},
            {Opcode.CMSG_CONVERSATION_LINE_STARTED, 0x3546},
            {Opcode.CMSG_QUEST_GIVER_CLOSE_QUEST, 0x3549},
            {Opcode.CMSG_LEARN_TALENT, 0x3552},
            // {Opcode.UNNAMED, 0x3553},
            // {Opcode.UNNAMED, 0x3554},
            // {Opcode.UNNAMED, 0x3555},
            {Opcode.CMSG_CONTRIBUTION_LAST_UPDATE_REQUEST, 0x355B},
            {Opcode.CMSG_SET_ACTION_BUTTON, 0x355D},
            {Opcode.CMSG_SET_AMMO, 0x355E},
            {Opcode.CMSG_SHOWING_CLOAK, 0x3568},
            {Opcode.CMSG_SHOWING_HELM, 0x3569},
            // {Opcode.UNNAMED, 0x356B},

            // GROUP: CliUserClient

            {Opcode.CMSG_CONNECT_TO_FAILED, 0x35D4},
            {Opcode.CMSG_ADDON_LIST, 0x35D8},
            {Opcode.CMSG_SET_ROLE, 0x35D9},
            {Opcode.CMSG_INITIATE_ROLE_POLL, 0x35DA},
            {Opcode.CMSG_REQUEST_BATTLEFIELD_STATUS, 0x35DD},
            {Opcode.CMSG_START_WAR_GAME, 0x35DF},
            {Opcode.CMSG_START_SPECTATOR_WAR_GAME, 0x35E0},
            {Opcode.CMSG_ACCEPT_WARGAME_INVITE, 0x35E1},
            {Opcode.CMSG_REQUEST_RATED_PVP_INFO, 0x35E4},
            {Opcode.CMSG_DB_QUERY_BULK, 0x35E5},
            {Opcode.CMSG_HOTFIX_REQUEST, 0x35E6},
            {Opcode.CMSG_GENERATE_RANDOM_CHARACTER_NAME, 0x35E8},
            {Opcode.CMSG_ENUM_CHARACTERS, 0x35E9},
            {Opcode.CMSG_REORDER_CHARACTERS, 0x35EA},
            {Opcode.CMSG_PLAYER_LOGIN, 0x35EB},
            {Opcode.CMSG_WARDEN3_DATA, 0x35ED},
            {Opcode.CMSG_COMMENTATOR_START_WARGAME, 0x35F0},
            {Opcode.CMSG_COMMENTATOR_ENABLE, 0x35F1},
            {Opcode.CMSG_COMMENTATOR_GET_MAP_INFO, 0x35F2},
            {Opcode.CMSG_COMMENTATOR_GET_PLAYER_INFO, 0x35F3},
            {Opcode.CMSG_COMMENTATOR_GET_PLAYER_COOLDOWNS, 0x35F4},
            {Opcode.CMSG_COMMENTATOR_ENTER_INSTANCE, 0x35F5},
            {Opcode.CMSG_COMMENTATOR_EXIT_INSTANCE, 0x35F6},
            {Opcode.CMSG_REQUEST_PARTY_JOIN_UPDATES, 0x35F8},
            {Opcode.CMSG_LOADING_SCREEN_NOTIFY, 0x35F9},
            {Opcode.CMSG_WORLD_PORT_RESPONSE, 0x35FA},
            {Opcode.CMSG_SEND_MAIL, 0x35FB},
            {Opcode.CMSG_ACCEPT_GUILD_INVITE, 0x35FD},
            {Opcode.CMSG_PARTY_INVITE, 0x3603},
            {Opcode.CMSG_PARTY_INVITE_RESPONSE, 0x3605},
            {Opcode.CMSG_GUILD_INVITE_BY_NAME, 0x3607},
            {Opcode.CMSG_LFG_LIST_LEAVE, 0x360B},
            {Opcode.CMSG_LFG_LIST_GET_STATUS, 0x360C},
            {Opcode.CMSG_LFG_LIST_SEARCH, 0x360D},
            {Opcode.CMSG_SET_EVERYONE_IS_ASSISTANT, 0x3619},
            {Opcode.CMSG_DF_READY_CHECK_RESPONSE, 0x361A},
            // {Opcode.UNNAMED, 0x3622},
            {Opcode.CMSG_BATTLE_PET_REQUEST_JOURNAL_LOCK, 0x3624},
            {Opcode.CMSG_BATTLE_PET_REQUEST_JOURNAL, 0x3625},
            {Opcode.CMSG_DO_READY_CHECK, 0x3635},
            {Opcode.CMSG_READY_CHECK_RESPONSE, 0x3636},
            {Opcode.CMSG_CREATE_CHARACTER, 0x3645},
            {Opcode.CMSG_SUPPORT_TICKET_SUBMIT_COMPLAINT, 0x3647},
            // {Opcode.UNNAMED, 0x3648},
            // {Opcode.UNNAMED, 0x3649},
            {Opcode.CMSG_PARTY_UNINVITE, 0x364A},
            {Opcode.CMSG_SET_LOOT_METHOD, 0x364B},
            {Opcode.CMSG_LEAVE_GROUP, 0x364C},
            {Opcode.CMSG_SET_PARTY_LEADER, 0x364D},
            {Opcode.CMSG_MINIMAP_PING, 0x364E},
            {Opcode.CMSG_GROUP_CHANGE_SUB_GROUP, 0x364F},
            {Opcode.CMSG_GROUP_SWAP_SUB_GROUP, 0x3650},
            {Opcode.CMSG_CONVERT_RAID, 0x3651},
            {Opcode.CMSG_SET_ASSISTANT_LEADER, 0x3652},
            {Opcode.CMSG_UPDATE_RAID_TARGET, 0x3653},
            {Opcode.CMSG_SET_PARTY_ASSIGNMENT, 0x3654},
            {Opcode.CMSG_SILENCE_PARTY_TALKER, 0x3655},
            {Opcode.CMSG_REQUEST_PARTY_MEMBER_STATS, 0x3656},
            {Opcode.CMSG_RANDOM_ROLL, 0x3657},
            {Opcode.CMSG_MAIL_RETURN_TO_SENDER, 0x3658},
            {Opcode.CMSG_QUERY_SCENARIO_POI, 0x3659},
            {Opcode.CMSG_ADD_BATTLENET_FRIEND, 0x365C},
            {Opcode.CMSG_QUERY_CORPSE_LOCATION_FROM_CLIENT, 0x3662},
            {Opcode.CMSG_QUERY_CORPSE_TRANSPORT, 0x3663},
            {Opcode.CMSG_CAN_DUEL, 0x3664},
            {Opcode.CMSG_UPDATE_CLIENT_SETTINGS, 0x3666},
            {Opcode.CMSG_RESET_INSTANCES, 0x366A},
            {Opcode.CMSG_SUMMON_RESPONSE, 0x366C},
            {Opcode.CMSG_COMPLAINT, 0x366E},
            {Opcode.CMSG_CALENDAR_GET, 0x3671},
            {Opcode.CMSG_CALENDAR_GET_EVENT, 0x3672},
            {Opcode.CMSG_CALENDAR_COMMUNITY_INVITE, 0x3673},
            {Opcode.CMSG_CALENDAR_INVITE, 0x3674},
            {Opcode.CMSG_CALENDAR_REMOVE_INVITE, 0x3675},
            {Opcode.CMSG_CALENDAR_RSVP, 0x3676},
            {Opcode.CMSG_CALENDAR_STATUS, 0x3677},
            {Opcode.CMSG_CALENDAR_MODERATOR_STATUS, 0x3678},
            {Opcode.CMSG_CALENDAR_REMOVE_EVENT, 0x3679},
            {Opcode.CMSG_CALENDAR_COPY_EVENT, 0x367A},
            {Opcode.CMSG_CALENDAR_COMPLAIN, 0x367B},
            {Opcode.CMSG_CALENDAR_GET_NUM_PENDING, 0x367C},
            {Opcode.CMSG_CALENDAR_EVENT_SIGN_UP, 0x367D},
            {Opcode.CMSG_CALENDAR_ADD_EVENT, 0x367F},
            {Opcode.CMSG_CALENDAR_UPDATE_EVENT, 0x3680},
            {Opcode.CMSG_KEEP_ALIVE, 0x3681},
            {Opcode.CMSG_WHO_IS, 0x3682},
            {Opcode.CMSG_WHO, 0x3683},
            {Opcode.CMSG_SET_DUNGEON_DIFFICULTY, 0x3684},
            {Opcode.CMSG_RESURRECT_RESPONSE, 0x3685},
            {Opcode.CMSG_PET_RENAME, 0x3686},
            {Opcode.CMSG_BUG_REPORT, 0x3687},
            {Opcode.CMSG_SET_PLAYER_DECLINED_NAMES, 0x3689},
            {Opcode.CMSG_QUERY_REALM_NAME, 0x368A},
            {Opcode.CMSG_QUERY_GUILD_INFO, 0x368B},
            {Opcode.CMSG_CHAR_CUSTOMIZE, 0x368C},
            {Opcode.CMSG_GM_TICKET_GET_SYSTEM_STATUS, 0x368E},
            {Opcode.CMSG_GM_TICKET_GET_CASE_STATUS, 0x368F},
            {Opcode.CMSG_GM_TICKET_ACKNOWLEDGE_SURVEY, 0x3690},
            {Opcode.CMSG_CHAR_RACE_OR_FACTION_CHANGE, 0x3692},
            {Opcode.CMSG_SUBMIT_USER_FEEDBACK, 0x3693},
            {Opcode.CMSG_REQUEST_ACCOUNT_DATA, 0x3694},
            {Opcode.CMSG_UPDATE_ACCOUNT_DATA, 0x3695},
            {Opcode.CMSG_SERVER_TIME_OFFSET_REQUEST, 0x369C},
            {Opcode.CMSG_CHAR_DELETE, 0x369D},
            {Opcode.CMSG_LOW_LEVEL_RAID1, 0x36A1},
            {Opcode.CMSG_INSPECT_PVP, 0x36A3},
            {Opcode.CMSG_ARENA_TEAM_QUERY, 0x36A4},
            // {Opcode.UNNAMED, 0x36AA},
            {Opcode.CMSG_ARENA_TEAM_ROSTER, 0x36B7},
            {Opcode.CMSG_ARENA_TEAM_ACCEPT, 0x36B8},
            {Opcode.CMSG_ARENA_TEAM_DECLINE, 0x36B9},
            {Opcode.CMSG_ARENA_TEAM_LEAVE, 0x36BA},
            {Opcode.CMSG_ARENA_TEAM_REMOVE, 0x36BB},
            {Opcode.CMSG_ARENA_TEAM_DISBAND, 0x36BC},
            {Opcode.CMSG_ARENA_TEAM_LEADER, 0x36BD},
            {Opcode.CMSG_GET_ACCOUNT_CHARACTER_LIST, 0x36BE},
            {Opcode.CMSG_LIVE_REGION_GET_ACCOUNT_CHARACTER_LIST, 0x36BF},
            {Opcode.CMSG_LIVE_REGION_CHARACTER_COPY, 0x36C0},
            {Opcode.CMSG_LIVE_REGION_ACCOUNT_RESTORE, 0x36C1},
            {Opcode.CMSG_BATTLE_PAY_GET_PRODUCT_LIST, 0x36C3},
            {Opcode.CMSG_BATTLE_PAY_GET_PURCHASE_LIST, 0x36C4},
            {Opcode.CMSG_CHARACTER_RENAME_REQUEST, 0x36C8},
            {Opcode.CMSG_SHOW_TRADE_SKILL, 0x36C9},
            {Opcode.CMSG_BATTLE_PAY_DISTRIBUTION_ASSIGN_TO_TARGET, 0x36CA},
            {Opcode.CMSG_CHARACTER_UPGRADE_MANUAL_UNREVOKE_REQUEST, 0x36CB},
            {Opcode.CMSG_CHARACTER_UPGRADE_START, 0x36CC},
            {Opcode.CMSG_CHARACTER_CHECK_UPGRADE, 0x36CD},
            {Opcode.CMSG_GUILD_SET_GUILD_MASTER, 0x36CF},
            {Opcode.CMSG_PETITION_RENAME_GUILD, 0x36D0},
            {Opcode.CMSG_REQUEST_RAID_INFO, 0x36D1},
            {Opcode.CMSG_BATTLE_PAY_START_PURCHASE, 0x36D2},
            {Opcode.CMSG_BATTLE_PAY_CONFIRM_PURCHASE_RESPONSE, 0x36D3},
            {Opcode.CMSG_BATTLE_PAY_ACK_FAILED_RESPONSE, 0x36D4},
            {Opcode.CMSG_CONTACT_LIST, 0x36D6},
            {Opcode.CMSG_ADD_FRIEND, 0x36D7},
            {Opcode.CMSG_DEL_FRIEND, 0x36D8},
            {Opcode.CMSG_SET_CONTACT_NOTES, 0x36D9},
            {Opcode.CMSG_BATTLENET_CHALLENGE_RESPONSE, 0x36DA},
            {Opcode.CMSG_ADD_IGNORE, 0x36DB},
            {Opcode.CMSG_DEL_IGNORE, 0x36DC},
            {Opcode.CMSG_SET_RAID_DIFFICULTY, 0x36E2},
            {Opcode.CMSG_TUTORIAL_FLAG, 0x36E3},
            {Opcode.CMSG_ENUM_CHARACTERS_DELETED_BY_CLIENT, 0x36E4},
            {Opcode.CMSG_UNDELETE_CHARACTER, 0x36E5},
            {Opcode.CMSG_GET_UNDELETE_CHARACTER_COOLDOWN_STATUS, 0x36E6},
            {Opcode.CMSG_ENGINE_SURVEY, 0x36EA},
            {Opcode.CMSG_COMMERCE_TOKEN_GET_COUNT, 0x36EB},
            {Opcode.CMSG_COMMERCE_TOKEN_GET_MARKET_PRICE, 0x36EC},
            {Opcode.CMSG_AUCTIONABLE_TOKEN_SELL, 0x36ED},
            {Opcode.CMSG_AUCTIONABLE_TOKEN_SELL_AT_MARKET_PRICE, 0x36EE},
            {Opcode.CMSG_CONSUMABLE_TOKEN_CAN_VETERAN_BUY, 0x36EF},
            {Opcode.CMSG_CONSUMABLE_TOKEN_BUY, 0x36F0},
            {Opcode.CMSG_CONSUMABLE_TOKEN_BUY_AT_MARKET_PRICE, 0x36F1},
            {Opcode.CMSG_GET_REMAINING_GAME_TIME, 0x36F2},
            {Opcode.CMSG_CONSUMABLE_TOKEN_REDEEM, 0x36F3},
            {Opcode.CMSG_CONSUMABLE_TOKEN_REDEEM_CONFIRMATION, 0x36F4},
            {Opcode.CMSG_COMMERCE_TOKEN_GET_LOG, 0x36F5},
            {Opcode.CMSG_GET_VAS_ACCOUNT_CHARACTER_LIST, 0x36F7},
            {Opcode.CMSG_GET_VAS_TRANSFER_TARGET_REALM_LIST, 0x36F8},
            {Opcode.CMSG_BATTLE_PAY_START_VAS_PURCHASE, 0x36F9},
            {Opcode.CMSG_UPDATE_VAS_PURCHASE_STATES, 0x36FA},
            {Opcode.CMSG_BATTLENET_REQUEST, 0x36FC},
            {Opcode.CMSG_CLUB_PRESENCE_SUBSCRIBE, 0x36FE},
            {Opcode.CMSG_CHANGE_REALM_TICKET, 0x3700},
            {Opcode.CMSG_REPORT_ENABLED_ADDONS, 0x3707},
            {Opcode.CMSG_REPORT_CLIENT_VARIABLES, 0x3708},
            {Opcode.CMSG_REPORT_KEYBINDING_EXECUTION_COUNTS, 0x3709},
            {Opcode.CMSG_QUICK_JOIN_RESPOND_TO_INVITE, 0x370C},
            // {Opcode.UNNAMED, 0x370D},
            {Opcode.CMSG_QUICK_JOIN_AUTO_ACCEPT_REQUESTS, 0x370E},
            {Opcode.CMSG_CAN_REDEEM_TOKEN_FOR_BALANCE, 0x370F},
            {Opcode.CMSG_BATTLE_PAY_REQUEST_PRICE_INFO, 0x3710},
            {Opcode.CMSG_VAS_GET_SERVICE_STATUS, 0x3711},
            {Opcode.CMSG_VAS_GET_QUEUE_MINUTES, 0x3712},
            {Opcode.CMSG_VAS_CHECK_TRANSFER_OK, 0x3713},
            {Opcode.CMSG_BATTLE_PAY_OPEN_CHECKOUT, 0x3714},
            {Opcode.CMSG_VOICE_CHAT_LOGIN, 0x3716},
            {Opcode.CMSG_VOICE_CHANNEL_STT_TOKEN_REQUEST, 0x3717},
            {Opcode.CMSG_VOICE_CHAT_JOIN_CHANNEL, 0x3718},
            // {Opcode.UNNAMED, 0x371A},
            {Opcode.CMSG_BATTLE_PAY_CANCEL_OPEN_CHECKOUT, 0x371B},
            {Opcode.CMSG_GET_ACCOUNT_NOTIFICATIONS, 0x373C},
            {Opcode.CMSG_ACCOUNT_NOTIFICATION_ACKNOWLEDGED, 0x373D},
            {Opcode.CMSG_UPDATE_AADC_STATUS, 0x3741},
            {Opcode.CMSG_BATTLE_PAY_DISTRIBUTION_ASSIGN_VAS, 0x3742},
            // {Opcode.UNNAMED, 0x3746},
            // {Opcode.UNNAMED, 0x3747},

            // GROUP: undefined

            {Opcode.CMSG_SUSPEND_COMMS_ACK, 0x3764},
            {Opcode.CMSG_AUTH_SESSION, 0x3765},
            {Opcode.CMSG_AUTH_CONTINUED_SESSION, 0x3766},
            {Opcode.CMSG_ENTER_ENCRYPTED_MODE_ACK, 0x3767},
            {Opcode.CMSG_PING, 0x3768},
            {Opcode.CMSG_LOG_DISCONNECT, 0x3769},
            {Opcode.CMSG_SUSPEND_TOKEN_RESPONSE, 0x376A},
            {Opcode.CMSG_ENABLE_NAGLE, 0x376B},
            {Opcode.CMSG_QUEUED_MESSAGES_END, 0x376C},
            {Opcode.CMSG_LOG_STREAMING_ERROR, 0x376D},
            {Opcode.CMSG_QUERY_PLAYER_NAME_BY_COMMUNITY_ID, 0x376F},
            {Opcode.CMSG_QUERY_PLAYER_NAMES_FOR_COMMUNITY, 0x3770},
            {Opcode.CMSG_LATENCY_REPORT, 0x3771},
            {Opcode.CMSG_QUERY_PLAYER_NAMES, 0x3772},

            // GROUP: CliChatEntity

            {Opcode.CMSG_CHAT_JOIN_CHANNEL, 0x37C8},
            {Opcode.CMSG_CHAT_LEAVE_CHANNEL, 0x37C9},
            {Opcode.CMSG_CHAT_REPORT_IGNORED, 0x37CB},
            {Opcode.CMSG_CHAT_REPORT_FILTERED, 0x37CC},
            {Opcode.CMSG_CHAT_REGISTER_ADDON_PREFIXES, 0x37CD},
            {Opcode.CMSG_CHAT_UNREGISTER_ALL_ADDON_PREFIXES, 0x37CE},
            {Opcode.CMSG_CHAT_MESSAGE_CHANNEL, 0x37CF},
            {Opcode.CMSG_CHAT_MESSAGE_WHISPER, 0x37D0},
            {Opcode.CMSG_CHAT_MESSAGE_GUILD, 0x37D1},
            {Opcode.CMSG_CHAT_MESSAGE_OFFICER, 0x37D2},
            {Opcode.CMSG_CHAT_MESSAGE_AFK, 0x37D3},
            {Opcode.CMSG_CHAT_MESSAGE_DND, 0x37D4},
            {Opcode.CMSG_CHAT_CHANNEL_LIST, 0x37D5},
            {Opcode.CMSG_CHAT_CHANNEL_DISPLAY_LIST, 0x37D6},
            {Opcode.CMSG_CHAT_CHANNEL_PASSWORD, 0x37D7},
            {Opcode.CMSG_CHAT_CHANNEL_SET_OWNER, 0x37D8},
            {Opcode.CMSG_CHAT_CHANNEL_OWNER, 0x37D9},
            {Opcode.CMSG_CHAT_CHANNEL_MODERATOR, 0x37DB},
            {Opcode.CMSG_CHAT_CHANNEL_UNMODERATOR, 0x37DC},
            {Opcode.CMSG_CHAT_CHANNEL_INVITE, 0x37DF},
            {Opcode.CMSG_CHAT_CHANNEL_KICK, 0x37E0},
            {Opcode.CMSG_CHAT_CHANNEL_BAN, 0x37E1},
            {Opcode.CMSG_CHAT_CHANNEL_UNBAN, 0x37E2},
            {Opcode.CMSG_CHAT_CHANNEL_ANNOUNCEMENTS, 0x37E3},
            {Opcode.CMSG_CHAT_CHANNEL_SILENCE_ALL, 0x37E4},
            {Opcode.CMSG_CHAT_CHANNEL_UNSILENCE_ALL, 0x37E5},
            {Opcode.CMSG_CHAT_CHANNEL_DECLINE_INVITE, 0x37E6},
            {Opcode.CMSG_CHAT_MESSAGE_SAY, 0x37E7},
            {Opcode.CMSG_CHAT_MESSAGE_EMOTE, 0x37E8},
            {Opcode.CMSG_CHAT_MESSAGE_YELL, 0x37E9},
            {Opcode.CMSG_CHAT_MESSAGE_PARTY, 0x37EA},
            {Opcode.CMSG_CHAT_MESSAGE_RAID, 0x37EB},
            {Opcode.CMSG_CHAT_MESSAGE_INSTANCE_CHAT, 0x37EC},
            {Opcode.CMSG_CHAT_MESSAGE_RAID_WARNING, 0x37ED},
            {Opcode.CMSG_CHAT_ADDON_MESSAGE, 0x37EE},
            {Opcode.CMSG_CHAT_ADDON_MESSAGE_TARGETED, 0x37EF},

            // GROUP: CliPlayerInventory

            {Opcode.CMSG_WRAP_ITEM, 0x3994},
            {Opcode.CMSG_USE_EQUIPMENT_SET, 0x3995},
            {Opcode.CMSG_AUTOSTORE_BANK_ITEM, 0x3996},
            {Opcode.CMSG_AUTOBANK_ITEM, 0x3997},
            {Opcode.CMSG_AUTO_EQUIP_ITEM, 0x3998},
            {Opcode.CMSG_AUTO_STORE_BAG_ITEM, 0x3999},
            {Opcode.CMSG_SWAP_ITEM, 0x399A},
            {Opcode.CMSG_SWAP_INV_ITEM, 0x399B},
            {Opcode.CMSG_SPLIT_ITEM, 0x399C},
            {Opcode.CMSG_AUTO_EQUIP_ITEM_SLOT, 0x399D},

            // GROUP: CliPlayerMovement

            {Opcode.CMSG_MOVE_START_FORWARD, 0x39E4},
            {Opcode.CMSG_MOVE_START_BACKWARD, 0x39E5},
            {Opcode.CMSG_MOVE_STOP, 0x39E6},
            {Opcode.CMSG_MOVE_START_STRAFE_LEFT, 0x39E7},
            {Opcode.CMSG_MOVE_START_STRAFE_RIGHT, 0x39E8},
            {Opcode.CMSG_MOVE_STOP_STRAFE, 0x39E9},
            {Opcode.CMSG_MOVE_JUMP, 0x39EA},
            {Opcode.CMSG_MOVE_DOUBLE_JUMP, 0x39EB},
            {Opcode.CMSG_MOVE_START_TURN_LEFT, 0x39EC},
            {Opcode.CMSG_MOVE_START_TURN_RIGHT, 0x39ED},
            {Opcode.CMSG_MOVE_STOP_TURN, 0x39EE},
            {Opcode.CMSG_MOVE_START_PITCH_UP, 0x39EF},
            {Opcode.CMSG_MOVE_START_PITCH_DOWN, 0x39F0},
            {Opcode.CMSG_MOVE_STOP_PITCH, 0x39F1},
            {Opcode.CMSG_MOVE_SET_RUN_MODE, 0x39F2},
            {Opcode.CMSG_MOVE_SET_WALK_MODE, 0x39F3},
            {Opcode.CMSG_MOVE_TELEPORT_ACK, 0x39FA},
            {Opcode.CMSG_MOVE_FALL_LAND, 0x39FB},
            {Opcode.CMSG_MOVE_START_SWIM, 0x39FC},
            {Opcode.CMSG_MOVE_STOP_SWIM, 0x39FD},
            {Opcode.CMSG_MOVE_SET_FACING, 0x3A09},
            {Opcode.CMSG_MOVE_SET_PITCH, 0x3A0A},
            {Opcode.CMSG_MOVE_FORCE_RUN_SPEED_CHANGE_ACK, 0x3A0B},
            {Opcode.CMSG_MOVE_FORCE_RUN_BACK_SPEED_CHANGE_ACK, 0x3A0C},
            {Opcode.CMSG_MOVE_FORCE_SWIM_SPEED_CHANGE_ACK, 0x3A0D},
            {Opcode.CMSG_MOVE_FORCE_ROOT_ACK, 0x3A0E},
            {Opcode.CMSG_MOVE_FORCE_UNROOT_ACK, 0x3A0F},
            {Opcode.CMSG_MOVE_HEARTBEAT, 0x3A10},
            {Opcode.CMSG_MOVE_KNOCK_BACK_ACK, 0x3A12},
            {Opcode.CMSG_MOVE_HOVER_ACK, 0x3A13},
            {Opcode.CMSG_MOVE_SET_VEHICLE_REC_ID_ACK, 0x3A14},
            {Opcode.CMSG_MOVE_APPLY_MOVEMENT_FORCE_ACK, 0x3A15},
            {Opcode.CMSG_MOVE_REMOVE_MOVEMENT_FORCE_ACK, 0x3A16},
            {Opcode.CMSG_MOVE_REMOVE_MOVEMENT_FORCES, 0x3A17},
            {Opcode.CMSG_MOVE_SPLINE_DONE, 0x3A18},
            {Opcode.CMSG_MOVE_FALL_RESET, 0x3A19},
            {Opcode.CMSG_MOVE_UPDATE_FALL_SPEED, 0x3A1A},
            {Opcode.CMSG_MOVE_TIME_SKIPPED, 0x3A1B},
            {Opcode.CMSG_MOVE_FEATHER_FALL_ACK, 0x3A1C},
            {Opcode.CMSG_MOVE_WATER_WALK_ACK, 0x3A1D},
            {Opcode.CMSG_MOVE_ENABLE_DOUBLE_JUMP_ACK, 0x3A1E},
            {Opcode.CMSG_MOVE_FORCE_WALK_SPEED_CHANGE_ACK, 0x3A21},
            {Opcode.CMSG_MOVE_FORCE_SWIM_BACK_SPEED_CHANGE_ACK, 0x3A22},
            {Opcode.CMSG_MOVE_FORCE_TURN_RATE_CHANGE_ACK, 0x3A23},
            {Opcode.CMSG_MOVE_ENABLE_SWIM_TO_FLY_TRANS_ACK, 0x3A24},
            {Opcode.CMSG_MOVE_SET_CAN_TURN_WHILE_FALLING_ACK, 0x3A25},
            {Opcode.CMSG_MOVE_SET_IGNORE_MOVEMENT_FORCES_ACK, 0x3A26},
            {Opcode.CMSG_MOVE_SET_CAN_FLY_ACK, 0x3A27},
            {Opcode.CMSG_MOVE_SET_FLY, 0x3A28},
            {Opcode.CMSG_MOVE_START_ASCEND, 0x3A29},
            {Opcode.CMSG_MOVE_STOP_ASCEND, 0x3A2A},
            {Opcode.CMSG_MOVE_FORCE_FLIGHT_SPEED_CHANGE_ACK, 0x3A2D},
            {Opcode.CMSG_MOVE_FORCE_FLIGHT_BACK_SPEED_CHANGE_ACK, 0x3A2E},
            {Opcode.CMSG_MOVE_CHANGE_TRANSPORT, 0x3A2F},
            {Opcode.CMSG_MOVE_START_DESCEND, 0x3A30},
            {Opcode.CMSG_MOVE_FORCE_PITCH_RATE_CHANGE_ACK, 0x3A32},
            {Opcode.CMSG_MOVE_DISMISS_VEHICLE, 0x3A33},
            {Opcode.CMSG_MOVE_CHANGE_VEHICLE_SEATS, 0x3A34},
            {Opcode.CMSG_MOVE_GRAVITY_DISABLE_ACK, 0x3A35},
            {Opcode.CMSG_MOVE_GRAVITY_ENABLE_ACK, 0x3A36},
            {Opcode.CMSG_MOVE_INERTIA_DISABLE_ACK, 0x3A37},
            {Opcode.CMSG_MOVE_INERTIA_ENABLE_ACK, 0x3A38},
            {Opcode.CMSG_MOVE_COLLISION_DISABLE_ACK, 0x3A39},
            {Opcode.CMSG_MOVE_COLLISION_ENABLE_ACK, 0x3A3A},
            {Opcode.CMSG_MOVE_SET_COLLISION_HEIGHT_ACK, 0x3A3B},
            {Opcode.CMSG_SET_ACTIVE_MOVER, 0x3A3C},
            {Opcode.CMSG_TIME_SYNC_RESPONSE, 0x3A3D},
            {Opcode.CMSG_TIME_SYNC_RESPONSE_FAILED, 0x3A3E},
            {Opcode.CMSG_TIME_SYNC_RESPONSE_DROPPED, 0x3A3F},
            {Opcode.CMSG_TIME_ADJUSTMENT_RESPONSE, 0x3A40},
            {Opcode.CMSG_DISCARDED_TIME_SYNC_ACKS, 0x3A41},
            {Opcode.CMSG_MOVE_SET_MOD_MOVEMENT_FORCE_MAGNITUDE_ACK, 0x3A42},
            {Opcode.CMSG_UPDATE_MISSILE_TRAJECTORY, 0x3A43},
            {Opcode.CMSG_MOVE_SEAMLESS_TRANSFER_COMPLETE, 0x3A44},
            {Opcode.CMSG_MOVE_INIT_ACTIVE_MOVER_COMPLETE, 0x3A46},
            // {Opcode.UNNAMED, 0x3A4E},
            // {Opcode.UNNAMED, 0x3A4F},
            // {Opcode.UNNAMED, 0x3A50},
            // {Opcode.UNNAMED, 0x3A51},
            // {Opcode.UNNAMED, 0x3A52},
            // {Opcode.UNNAMED, 0x3A53},
            // {Opcode.UNNAMED, 0x3A54},
            // {Opcode.UNNAMED, 0x3A55},
            // {Opcode.UNNAMED, 0x3A56},
            // {Opcode.UNNAMED, 0x3A57},
            // {Opcode.UNNAMED, 0x3A58},
            // {Opcode.UNNAMED, 0x3A59},
            // {Opcode.UNNAMED, 0x3A5A},
            // {Opcode.UNNAMED, 0x3A5B},
            // {Opcode.UNNAMED, 0x3A5C},
            // {Opcode.UNNAMED, 0x3A5D},
            // {Opcode.UNNAMED, 0x3A5E},
            {Opcode.CMSG_MOVE_SET_FACING_HEARTBEAT, 0x3A5F}, // not sure
            // {Opcode.UNNAMED, 0x3A60},
        };

        private static readonly BiDictionary<Opcode, int> ServerOpcodes = new()
        {
            { Opcode.SMSG_AURA_UPDATE, 0x2C1F },
            { Opcode.SMSG_SPELL_GO, 0x2C36 },
            { Opcode.SMSG_SPELL_START, 0x2C37 },
            { Opcode.SMSG_ON_MONSTER_MOVE, 0x2DD4 },
            { Opcode.SMSG_UPDATE_OBJECT, 0x27C8 },
            { Opcode.SMSG_EMOTE, 0x27CF },
            { Opcode.SMSG_CHAT, 0x2BAD },
            { Opcode.SMSG_GOSSIP_COMPLETE, 0x2A97 },
            { Opcode.SMSG_GOSSIP_MESSAGE, 0x2A98 },
            { Opcode.SMSG_TEXT_EMOTE, 0x2677 },
        };

        private static readonly BiDictionary<Opcode, int> MiscOpcodes = new BiDictionary<Opcode, int>();
    }
}