using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

// This file is automatically generated, DO NOT EDIT

namespace WowPacketParserModule.V10_0_0_46181.UpdateFields.V10_1_5_50232
{
    public class ItemMod : IItemMod
    {
        public int Value { get; set; }
        public byte Type { get; set; }
    }
}

