using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

// This file is automatically generated, DO NOT EDIT

namespace WowPacketParserModule.V10_0_0_46181.UpdateFields.V10_1_5_50232
{
    public class QuestSession : IQuestSession
    {
        public WowGuid Owner { get; set; }
        public System.Nullable<ulong>[] QuestCompleted { get; } = new System.Nullable<ulong>[875];
    }
}

