using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

// This file is automatically generated, DO NOT EDIT

namespace WowPacketParserModule.V10_0_0_46181.UpdateFields.V10_1_5_50232
{
    public class TraitConfig : ITraitConfig
    {
        public System.Nullable<int> ID { get; set; }
        public System.Nullable<int> Type { get; set; }
        public System.Nullable<int> SkillLineID { get; set; }
        public System.Nullable<int> ChrSpecializationID { get; set; }
        public System.Nullable<int> CombatConfigFlags { get; set; }
        public System.Nullable<int> LocalIdentifier { get; set; }
        public System.Nullable<int> TraitSystemID { get; set; }
        public DynamicUpdateField<ITraitEntry> Entries { get; } = new DynamicUpdateField<ITraitEntry>();
        public string Name { get; set; }
    }
}

