// <auto-generated>
// DO NOT EDIT
// </auto-generated>

using System.CodeDom.Compiler;
using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

namespace WowPacketParserModule.V12_0_0_65390.UpdateFields.V12_0_0_65390
{
    [GeneratedCode("UpdateFieldCodeGenerator.Formats.WowPacketParserHandler", "1.0.0.0")]
    public class SkillInfo : ISkillInfo
    {
        public System.Nullable<ushort>[] SkillLineID { get; } = new System.Nullable<ushort>[300];
        public System.Nullable<ushort>[] SkillStep { get; } = new System.Nullable<ushort>[300];
        public System.Nullable<ushort>[] SkillRank { get; } = new System.Nullable<ushort>[300];
        public System.Nullable<ushort>[] SkillStartingRank { get; } = new System.Nullable<ushort>[300];
        public System.Nullable<ushort>[] SkillMaxRank { get; } = new System.Nullable<ushort>[300];
        public System.Nullable<short>[] SkillTempBonus { get; } = new System.Nullable<short>[300];
        public System.Nullable<ushort>[] SkillPermBonus { get; } = new System.Nullable<ushort>[300];
    }
}

