// <auto-generated>
// DO NOT EDIT
// </auto-generated>

using System.CodeDom.Compiler;
using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

namespace WowPacketParserModule.V12_0_0_65390.UpdateFields.V12_0_0_65390
{
    [GeneratedCode("UpdateFieldCodeGenerator.Formats.WowPacketParserHandler", "1.0.0.0")]
    public class TraitEntry : ITraitEntry
    {
        public int TraitNodeID { get; set; }
        public int TraitNodeEntryID { get; set; }
        public int Rank { get; set; }
        public int GrantedRanks { get; set; }
        public int BonusRanks { get; set; }
    }
}

