// <auto-generated>
// DO NOT EDIT
// </auto-generated>

using System.CodeDom.Compiler;
using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

namespace WowPacketParserModule.V12_0_0_65390.UpdateFields.V12_1_0_69214
{
    [GeneratedCode("UpdateFieldCodeGenerator.Formats.WowPacketParserHandler", "1.0.0.0")]
    public class DiscordPlayerInfo : IDiscordPlayerInfo
    {
        public ulong DiscordUserID { get; set; }
        public byte AccountType { get; set; }
        public ulong GuildLobbyID { get; set; }
        public byte GuildSettings { get; set; }
        public byte DisplayNameType { get; set; }
        public string AccessToken { get; set; }
    }
}

