using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

// This file is automatically generated, DO NOT EDIT

namespace WowPacketParserModule.V10_0_0_46181.UpdateFields.V10_0_0_46181
{
    public class PVPInfo : IPVPInfo
    {
        public System.Nullable<sbyte> Field_00 { get; set; }
        public System.Nullable<uint> WeeklyPlayed { get; set; }
        public System.Nullable<uint> WeeklyWon { get; set; }
        public System.Nullable<uint> SeasonPlayed { get; set; }
        public System.Nullable<uint> SeasonWon { get; set; }
        public System.Nullable<uint> Rating { get; set; }
        public System.Nullable<uint> WeeklyBestRating { get; set; }
        public System.Nullable<uint> SeasonBestRating { get; set; }
        public System.Nullable<uint> PvpTierID { get; set; }
        public System.Nullable<uint> WeeklyBestWinPvpTierID { get; set; }
        public System.Nullable<uint> Field_28 { get; set; }
        public System.Nullable<uint> Field_30 { get; set; }
        public System.Nullable<uint> Field_34 { get; set; }
        public System.Nullable<uint> Field_38 { get; set; }
        public System.Nullable<uint> Field_3C { get; set; }
        public System.Nullable<uint> Field_40 { get; set; }
        public System.Nullable<uint> Field_44 { get; set; }
        public System.Nullable<bool> Disqualified { get; set; }
    }
}

