using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

// This file is automatically generated, DO NOT EDIT

namespace WowPacketParserModule.V2_5_1_38707.UpdateFields.V2_5_4_42800
{
    public class ConversationActor : IConversationActor
    {
        public uint Type { get; set; }
        public int Id { get; set; }
        public WowGuid ActorGUID { get; set; }
        public uint CreatureID { get; set; }
        public uint CreatureDisplayInfoID { get; set; }
        public WowGuid Unknown { get; set; }
    }
}

