using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

// This file is automatically generated, DO NOT EDIT

namespace WowPacketParserModule.V2_5_1_38707.UpdateFields.V2_5_4_42800
{
    public class ItemEnchantment : IItemEnchantment
    {
        public System.Nullable<int> ID { get; set; }
        public System.Nullable<uint> Duration { get; set; }
        public System.Nullable<short> Charges { get; set; }
        public System.Nullable<byte> Unk254 { get; set; }
        public System.Nullable<byte> Unk254_2 { get; set; }
    }
}

