using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

// This file is automatically generated, DO NOT EDIT

namespace WowPacketParserModule.V2_5_1_38707.UpdateFields.V2_5_4_42800
{
    public class SceneObjectData : ISceneObjectData
    {
        public System.Nullable<int> ScriptPackageID { get; set; }
        public System.Nullable<uint> RndSeedVal { get; set; }
        public WowGuid CreatedBy { get; set; }
        public System.Nullable<uint> SceneType { get; set; }
    }
}

