// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: bgs/low/pb/client/club_range_set.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.Club.V1 {

  /// <summary>Holder for reflection information generated from bgs/low/pb/client/club_range_set.proto</summary>
  public static partial class ClubRangeSetReflection {

    #region Descriptor
    /// <summary>File descriptor for bgs/low/pb/client/club_range_set.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ClubRangeSetReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiZiZ3MvbG93L3BiL2NsaWVudC9jbHViX3JhbmdlX3NldC5wcm90bxIUYmdz",
            "LnByb3RvY29sLmNsdWIudjEaL2Jncy9sb3cvcGIvY2xpZW50L2dsb2JhbF9l",
            "eHRlbnNpb25zL3JhbmdlLnByb3RvItoEChBDbHViVHlwZVJhbmdlU2V0EjIK",
            "Cm5hbWVfcmFuZ2UYAiABKAsyHi5iZ3MucHJvdG9jb2wuVW5zaWduZWRJbnRS",
            "YW5nZRI5ChFkZXNjcmlwdGlvbl9yYW5nZRgDIAEoCzIeLmJncy5wcm90b2Nv",
            "bC5VbnNpZ25lZEludFJhbmdlEjcKD2Jyb2FkY2FzdF9yYW5nZRgEIAEoCzIe",
            "LmJncy5wcm90b2NvbC5VbnNpZ25lZEludFJhbmdlEjgKEHNob3J0X25hbWVf",
            "cmFuZ2UYByABKAsyHi5iZ3MucHJvdG9jb2wuVW5zaWduZWRJbnRSYW5nZRI4",
            "CgZtZW1iZXIYGSABKAsyKC5iZ3MucHJvdG9jb2wuY2x1Yi52MS5DbHViTWVt",
            "YmVyUmFuZ2VTZXQSOAoGc3RyZWFtGBogASgLMiguYmdzLnByb3RvY29sLmNs",
            "dWIudjEuQ2x1YlN0cmVhbVJhbmdlU2V0EkAKCmludml0YXRpb24YGyABKAsy",
            "LC5iZ3MucHJvdG9jb2wuY2x1Yi52MS5DbHViSW52aXRhdGlvblJhbmdlU2V0",
            "EkAKCnN1Z2dlc3Rpb24YHCABKAsyLC5iZ3MucHJvdG9jb2wuY2x1Yi52MS5D",
            "bHViU3VnZ2VzdGlvblJhbmdlU2V0EjgKBnRpY2tldBgdIAEoCzIoLmJncy5w",
            "cm90b2NvbC5jbHViLnYxLkNsdWJUaWNrZXRSYW5nZVNldBIyCgNiYW4YHiAB",
            "KAsyJS5iZ3MucHJvdG9jb2wuY2x1Yi52MS5DbHViQmFuUmFuZ2VTZXQi5AEK",
            "EkNsdWJNZW1iZXJSYW5nZVNldBItCgVjb3VudBgBIAEoCzIeLmJncy5wcm90",
            "b2NvbC5VbnNpZ25lZEludFJhbmdlEi0KBXZvaWNlGAMgASgLMh4uYmdzLnBy",
            "b3RvY29sLlVuc2lnbmVkSW50UmFuZ2USPAoUc3RyZWFtX3N1YnNjcmlwdGlv",
            "bnMYBSABKAsyHi5iZ3MucHJvdG9jb2wuVW5zaWduZWRJbnRSYW5nZRIyCgpu",
            "b3RlX3JhbmdlGAcgASgLMh4uYmdzLnByb3RvY29sLlVuc2lnbmVkSW50UmFu",
            "Z2Ui5QEKEkNsdWJTdHJlYW1SYW5nZVNldBItCgVjb3VudBgBIAEoCzIeLmJn",
            "cy5wcm90b2NvbC5VbnNpZ25lZEludFJhbmdlEjIKCm5hbWVfcmFuZ2UYAyAB",
            "KAsyHi5iZ3MucHJvdG9jb2wuVW5zaWduZWRJbnRSYW5nZRI1Cg1zdWJqZWN0",
            "X3JhbmdlGAQgASgLMh4uYmdzLnByb3RvY29sLlVuc2lnbmVkSW50UmFuZ2US",
            "NQoNbWVzc2FnZV9yYW5nZRgFIAEoCzIeLmJncy5wcm90b2NvbC5VbnNpZ25l",
            "ZEludFJhbmdlIkcKFkNsdWJJbnZpdGF0aW9uUmFuZ2VTZXQSLQoFY291bnQY",
            "ASABKAsyHi5iZ3MucHJvdG9jb2wuVW5zaWduZWRJbnRSYW5nZSJHChZDbHVi",
            "U3VnZ2VzdGlvblJhbmdlU2V0Ei0KBWNvdW50GAEgASgLMh4uYmdzLnByb3Rv",
            "Y29sLlVuc2lnbmVkSW50UmFuZ2UiQwoSQ2x1YlRpY2tldFJhbmdlU2V0Ei0K",
            "BWNvdW50GAEgASgLMh4uYmdzLnByb3RvY29sLlVuc2lnbmVkSW50UmFuZ2Ui",
            "dgoPQ2x1YkJhblJhbmdlU2V0Ei0KBWNvdW50GAEgASgLMh4uYmdzLnByb3Rv",
            "Y29sLlVuc2lnbmVkSW50UmFuZ2USNAoMcmVhc29uX3JhbmdlGAMgASgLMh4u",
            "YmdzLnByb3RvY29sLlVuc2lnbmVkSW50UmFuZ2VCAkgB"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.RangeReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.Club.V1.ClubTypeRangeSet), WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.Club.V1.ClubTypeRangeSet.Parser, new[]{ "NameRange", "DescriptionRange", "BroadcastRange", "ShortNameRange", "Member", "Stream", "Invitation", "Suggestion", "Ticket", "Ban" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.Club.V1.ClubMemberRangeSet), WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.Club.V1.ClubMemberRangeSet.Parser, new[]{ "Count", "Voice", "StreamSubscriptions", "NoteRange" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.Club.V1.ClubStreamRangeSet), WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.Club.V1.ClubStreamRangeSet.Parser, new[]{ "Count", "NameRange", "SubjectRange", "MessageRange" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.Club.V1.ClubInvitationRangeSet), WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.Club.V1.ClubInvitationRangeSet.Parser, new[]{ "Count" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.Club.V1.ClubSuggestionRangeSet), WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.Club.V1.ClubSuggestionRangeSet.Parser, new[]{ "Count" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.Club.V1.ClubTicketRangeSet), WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.Club.V1.ClubTicketRangeSet.Parser, new[]{ "Count" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.Club.V1.ClubBanRangeSet), WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.Club.V1.ClubBanRangeSet.Parser, new[]{ "Count", "ReasonRange" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ClubTypeRangeSet : pb::IMessage<ClubTypeRangeSet>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ClubTypeRangeSet> _parser = new pb::MessageParser<ClubTypeRangeSet>(() => new ClubTypeRangeSet());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ClubTypeRangeSet> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.Club.V1.ClubRangeSetReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClubTypeRangeSet() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClubTypeRangeSet(ClubTypeRangeSet other) : this() {
      nameRange_ = other.nameRange_ != null ? other.nameRange_.Clone() : null;
      descriptionRange_ = other.descriptionRange_ != null ? other.descriptionRange_.Clone() : null;
      broadcastRange_ = other.broadcastRange_ != null ? other.broadcastRange_.Clone() : null;
      shortNameRange_ = other.shortNameRange_ != null ? other.shortNameRange_.Clone() : null;
      member_ = other.member_ != null ? other.member_.Clone() : null;
      stream_ = other.stream_ != null ? other.stream_.Clone() : null;
      invitation_ = other.invitation_ != null ? other.invitation_.Clone() : null;
      suggestion_ = other.suggestion_ != null ? other.suggestion_.Clone() : null;
      ticket_ = other.ticket_ != null ? other.ticket_.Clone() : null;
      ban_ = other.ban_ != null ? other.ban_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClubTypeRangeSet Clone() {
      return new ClubTypeRangeSet(this);
    }

    /// <summary>Field number for the "name_range" field.</summary>
    public const int NameRangeFieldNumber = 2;
    private WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange nameRange_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange NameRange {
      get { return nameRange_; }
      set {
        nameRange_ = value;
      }
    }

    /// <summary>Field number for the "description_range" field.</summary>
    public const int DescriptionRangeFieldNumber = 3;
    private WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange descriptionRange_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange DescriptionRange {
      get { return descriptionRange_; }
      set {
        descriptionRange_ = value;
      }
    }

    /// <summary>Field number for the "broadcast_range" field.</summary>
    public const int BroadcastRangeFieldNumber = 4;
    private WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange broadcastRange_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange BroadcastRange {
      get { return broadcastRange_; }
      set {
        broadcastRange_ = value;
      }
    }

    /// <summary>Field number for the "short_name_range" field.</summary>
    public const int ShortNameRangeFieldNumber = 7;
    private WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange shortNameRange_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange ShortNameRange {
      get { return shortNameRange_; }
      set {
        shortNameRange_ = value;
      }
    }

    /// <summary>Field number for the "member" field.</summary>
    public const int MemberFieldNumber = 25;
    private WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.Club.V1.ClubMemberRangeSet member_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.Club.V1.ClubMemberRangeSet Member {
      get { return member_; }
      set {
        member_ = value;
      }
    }

    /// <summary>Field number for the "stream" field.</summary>
    public const int StreamFieldNumber = 26;
    private WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.Club.V1.ClubStreamRangeSet stream_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.Club.V1.ClubStreamRangeSet Stream {
      get { return stream_; }
      set {
        stream_ = value;
      }
    }

    /// <summary>Field number for the "invitation" field.</summary>
    public const int InvitationFieldNumber = 27;
    private WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.Club.V1.ClubInvitationRangeSet invitation_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.Club.V1.ClubInvitationRangeSet Invitation {
      get { return invitation_; }
      set {
        invitation_ = value;
      }
    }

    /// <summary>Field number for the "suggestion" field.</summary>
    public const int SuggestionFieldNumber = 28;
    private WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.Club.V1.ClubSuggestionRangeSet suggestion_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.Club.V1.ClubSuggestionRangeSet Suggestion {
      get { return suggestion_; }
      set {
        suggestion_ = value;
      }
    }

    /// <summary>Field number for the "ticket" field.</summary>
    public const int TicketFieldNumber = 29;
    private WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.Club.V1.ClubTicketRangeSet ticket_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.Club.V1.ClubTicketRangeSet Ticket {
      get { return ticket_; }
      set {
        ticket_ = value;
      }
    }

    /// <summary>Field number for the "ban" field.</summary>
    public const int BanFieldNumber = 30;
    private WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.Club.V1.ClubBanRangeSet ban_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.Club.V1.ClubBanRangeSet Ban {
      get { return ban_; }
      set {
        ban_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ClubTypeRangeSet);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ClubTypeRangeSet other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(NameRange, other.NameRange)) return false;
      if (!object.Equals(DescriptionRange, other.DescriptionRange)) return false;
      if (!object.Equals(BroadcastRange, other.BroadcastRange)) return false;
      if (!object.Equals(ShortNameRange, other.ShortNameRange)) return false;
      if (!object.Equals(Member, other.Member)) return false;
      if (!object.Equals(Stream, other.Stream)) return false;
      if (!object.Equals(Invitation, other.Invitation)) return false;
      if (!object.Equals(Suggestion, other.Suggestion)) return false;
      if (!object.Equals(Ticket, other.Ticket)) return false;
      if (!object.Equals(Ban, other.Ban)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (nameRange_ != null) hash ^= NameRange.GetHashCode();
      if (descriptionRange_ != null) hash ^= DescriptionRange.GetHashCode();
      if (broadcastRange_ != null) hash ^= BroadcastRange.GetHashCode();
      if (shortNameRange_ != null) hash ^= ShortNameRange.GetHashCode();
      if (member_ != null) hash ^= Member.GetHashCode();
      if (stream_ != null) hash ^= Stream.GetHashCode();
      if (invitation_ != null) hash ^= Invitation.GetHashCode();
      if (suggestion_ != null) hash ^= Suggestion.GetHashCode();
      if (ticket_ != null) hash ^= Ticket.GetHashCode();
      if (ban_ != null) hash ^= Ban.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (nameRange_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(NameRange);
      }
      if (descriptionRange_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(DescriptionRange);
      }
      if (broadcastRange_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(BroadcastRange);
      }
      if (shortNameRange_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(ShortNameRange);
      }
      if (member_ != null) {
        output.WriteRawTag(202, 1);
        output.WriteMessage(Member);
      }
      if (stream_ != null) {
        output.WriteRawTag(210, 1);
        output.WriteMessage(Stream);
      }
      if (invitation_ != null) {
        output.WriteRawTag(218, 1);
        output.WriteMessage(Invitation);
      }
      if (suggestion_ != null) {
        output.WriteRawTag(226, 1);
        output.WriteMessage(Suggestion);
      }
      if (ticket_ != null) {
        output.WriteRawTag(234, 1);
        output.WriteMessage(Ticket);
      }
      if (ban_ != null) {
        output.WriteRawTag(242, 1);
        output.WriteMessage(Ban);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (nameRange_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(NameRange);
      }
      if (descriptionRange_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(DescriptionRange);
      }
      if (broadcastRange_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(BroadcastRange);
      }
      if (shortNameRange_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(ShortNameRange);
      }
      if (member_ != null) {
        output.WriteRawTag(202, 1);
        output.WriteMessage(Member);
      }
      if (stream_ != null) {
        output.WriteRawTag(210, 1);
        output.WriteMessage(Stream);
      }
      if (invitation_ != null) {
        output.WriteRawTag(218, 1);
        output.WriteMessage(Invitation);
      }
      if (suggestion_ != null) {
        output.WriteRawTag(226, 1);
        output.WriteMessage(Suggestion);
      }
      if (ticket_ != null) {
        output.WriteRawTag(234, 1);
        output.WriteMessage(Ticket);
      }
      if (ban_ != null) {
        output.WriteRawTag(242, 1);
        output.WriteMessage(Ban);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (nameRange_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(NameRange);
      }
      if (descriptionRange_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(DescriptionRange);
      }
      if (broadcastRange_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(BroadcastRange);
      }
      if (shortNameRange_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ShortNameRange);
      }
      if (member_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(Member);
      }
      if (stream_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(Stream);
      }
      if (invitation_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(Invitation);
      }
      if (suggestion_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(Suggestion);
      }
      if (ticket_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(Ticket);
      }
      if (ban_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(Ban);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ClubTypeRangeSet other) {
      if (other == null) {
        return;
      }
      if (other.nameRange_ != null) {
        if (nameRange_ == null) {
          NameRange = new WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange();
        }
        NameRange.MergeFrom(other.NameRange);
      }
      if (other.descriptionRange_ != null) {
        if (descriptionRange_ == null) {
          DescriptionRange = new WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange();
        }
        DescriptionRange.MergeFrom(other.DescriptionRange);
      }
      if (other.broadcastRange_ != null) {
        if (broadcastRange_ == null) {
          BroadcastRange = new WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange();
        }
        BroadcastRange.MergeFrom(other.BroadcastRange);
      }
      if (other.shortNameRange_ != null) {
        if (shortNameRange_ == null) {
          ShortNameRange = new WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange();
        }
        ShortNameRange.MergeFrom(other.ShortNameRange);
      }
      if (other.member_ != null) {
        if (member_ == null) {
          Member = new WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.Club.V1.ClubMemberRangeSet();
        }
        Member.MergeFrom(other.Member);
      }
      if (other.stream_ != null) {
        if (stream_ == null) {
          Stream = new WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.Club.V1.ClubStreamRangeSet();
        }
        Stream.MergeFrom(other.Stream);
      }
      if (other.invitation_ != null) {
        if (invitation_ == null) {
          Invitation = new WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.Club.V1.ClubInvitationRangeSet();
        }
        Invitation.MergeFrom(other.Invitation);
      }
      if (other.suggestion_ != null) {
        if (suggestion_ == null) {
          Suggestion = new WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.Club.V1.ClubSuggestionRangeSet();
        }
        Suggestion.MergeFrom(other.Suggestion);
      }
      if (other.ticket_ != null) {
        if (ticket_ == null) {
          Ticket = new WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.Club.V1.ClubTicketRangeSet();
        }
        Ticket.MergeFrom(other.Ticket);
      }
      if (other.ban_ != null) {
        if (ban_ == null) {
          Ban = new WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.Club.V1.ClubBanRangeSet();
        }
        Ban.MergeFrom(other.Ban);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 18: {
            if (nameRange_ == null) {
              NameRange = new WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange();
            }
            input.ReadMessage(NameRange);
            break;
          }
          case 26: {
            if (descriptionRange_ == null) {
              DescriptionRange = new WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange();
            }
            input.ReadMessage(DescriptionRange);
            break;
          }
          case 34: {
            if (broadcastRange_ == null) {
              BroadcastRange = new WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange();
            }
            input.ReadMessage(BroadcastRange);
            break;
          }
          case 58: {
            if (shortNameRange_ == null) {
              ShortNameRange = new WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange();
            }
            input.ReadMessage(ShortNameRange);
            break;
          }
          case 202: {
            if (member_ == null) {
              Member = new WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.Club.V1.ClubMemberRangeSet();
            }
            input.ReadMessage(Member);
            break;
          }
          case 210: {
            if (stream_ == null) {
              Stream = new WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.Club.V1.ClubStreamRangeSet();
            }
            input.ReadMessage(Stream);
            break;
          }
          case 218: {
            if (invitation_ == null) {
              Invitation = new WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.Club.V1.ClubInvitationRangeSet();
            }
            input.ReadMessage(Invitation);
            break;
          }
          case 226: {
            if (suggestion_ == null) {
              Suggestion = new WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.Club.V1.ClubSuggestionRangeSet();
            }
            input.ReadMessage(Suggestion);
            break;
          }
          case 234: {
            if (ticket_ == null) {
              Ticket = new WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.Club.V1.ClubTicketRangeSet();
            }
            input.ReadMessage(Ticket);
            break;
          }
          case 242: {
            if (ban_ == null) {
              Ban = new WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.Club.V1.ClubBanRangeSet();
            }
            input.ReadMessage(Ban);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 18: {
            if (nameRange_ == null) {
              NameRange = new WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange();
            }
            input.ReadMessage(NameRange);
            break;
          }
          case 26: {
            if (descriptionRange_ == null) {
              DescriptionRange = new WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange();
            }
            input.ReadMessage(DescriptionRange);
            break;
          }
          case 34: {
            if (broadcastRange_ == null) {
              BroadcastRange = new WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange();
            }
            input.ReadMessage(BroadcastRange);
            break;
          }
          case 58: {
            if (shortNameRange_ == null) {
              ShortNameRange = new WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange();
            }
            input.ReadMessage(ShortNameRange);
            break;
          }
          case 202: {
            if (member_ == null) {
              Member = new WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.Club.V1.ClubMemberRangeSet();
            }
            input.ReadMessage(Member);
            break;
          }
          case 210: {
            if (stream_ == null) {
              Stream = new WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.Club.V1.ClubStreamRangeSet();
            }
            input.ReadMessage(Stream);
            break;
          }
          case 218: {
            if (invitation_ == null) {
              Invitation = new WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.Club.V1.ClubInvitationRangeSet();
            }
            input.ReadMessage(Invitation);
            break;
          }
          case 226: {
            if (suggestion_ == null) {
              Suggestion = new WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.Club.V1.ClubSuggestionRangeSet();
            }
            input.ReadMessage(Suggestion);
            break;
          }
          case 234: {
            if (ticket_ == null) {
              Ticket = new WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.Club.V1.ClubTicketRangeSet();
            }
            input.ReadMessage(Ticket);
            break;
          }
          case 242: {
            if (ban_ == null) {
              Ban = new WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.Club.V1.ClubBanRangeSet();
            }
            input.ReadMessage(Ban);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ClubMemberRangeSet : pb::IMessage<ClubMemberRangeSet>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ClubMemberRangeSet> _parser = new pb::MessageParser<ClubMemberRangeSet>(() => new ClubMemberRangeSet());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ClubMemberRangeSet> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.Club.V1.ClubRangeSetReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClubMemberRangeSet() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClubMemberRangeSet(ClubMemberRangeSet other) : this() {
      count_ = other.count_ != null ? other.count_.Clone() : null;
      voice_ = other.voice_ != null ? other.voice_.Clone() : null;
      streamSubscriptions_ = other.streamSubscriptions_ != null ? other.streamSubscriptions_.Clone() : null;
      noteRange_ = other.noteRange_ != null ? other.noteRange_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClubMemberRangeSet Clone() {
      return new ClubMemberRangeSet(this);
    }

    /// <summary>Field number for the "count" field.</summary>
    public const int CountFieldNumber = 1;
    private WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange count_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange Count {
      get { return count_; }
      set {
        count_ = value;
      }
    }

    /// <summary>Field number for the "voice" field.</summary>
    public const int VoiceFieldNumber = 3;
    private WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange voice_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange Voice {
      get { return voice_; }
      set {
        voice_ = value;
      }
    }

    /// <summary>Field number for the "stream_subscriptions" field.</summary>
    public const int StreamSubscriptionsFieldNumber = 5;
    private WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange streamSubscriptions_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange StreamSubscriptions {
      get { return streamSubscriptions_; }
      set {
        streamSubscriptions_ = value;
      }
    }

    /// <summary>Field number for the "note_range" field.</summary>
    public const int NoteRangeFieldNumber = 7;
    private WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange noteRange_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange NoteRange {
      get { return noteRange_; }
      set {
        noteRange_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ClubMemberRangeSet);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ClubMemberRangeSet other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Count, other.Count)) return false;
      if (!object.Equals(Voice, other.Voice)) return false;
      if (!object.Equals(StreamSubscriptions, other.StreamSubscriptions)) return false;
      if (!object.Equals(NoteRange, other.NoteRange)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (count_ != null) hash ^= Count.GetHashCode();
      if (voice_ != null) hash ^= Voice.GetHashCode();
      if (streamSubscriptions_ != null) hash ^= StreamSubscriptions.GetHashCode();
      if (noteRange_ != null) hash ^= NoteRange.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (count_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Count);
      }
      if (voice_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Voice);
      }
      if (streamSubscriptions_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(StreamSubscriptions);
      }
      if (noteRange_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(NoteRange);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (count_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Count);
      }
      if (voice_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Voice);
      }
      if (streamSubscriptions_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(StreamSubscriptions);
      }
      if (noteRange_ != null) {
        output.WriteRawTag(58);
        output.WriteMessage(NoteRange);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (count_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Count);
      }
      if (voice_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Voice);
      }
      if (streamSubscriptions_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(StreamSubscriptions);
      }
      if (noteRange_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(NoteRange);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ClubMemberRangeSet other) {
      if (other == null) {
        return;
      }
      if (other.count_ != null) {
        if (count_ == null) {
          Count = new WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange();
        }
        Count.MergeFrom(other.Count);
      }
      if (other.voice_ != null) {
        if (voice_ == null) {
          Voice = new WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange();
        }
        Voice.MergeFrom(other.Voice);
      }
      if (other.streamSubscriptions_ != null) {
        if (streamSubscriptions_ == null) {
          StreamSubscriptions = new WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange();
        }
        StreamSubscriptions.MergeFrom(other.StreamSubscriptions);
      }
      if (other.noteRange_ != null) {
        if (noteRange_ == null) {
          NoteRange = new WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange();
        }
        NoteRange.MergeFrom(other.NoteRange);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (count_ == null) {
              Count = new WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange();
            }
            input.ReadMessage(Count);
            break;
          }
          case 26: {
            if (voice_ == null) {
              Voice = new WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange();
            }
            input.ReadMessage(Voice);
            break;
          }
          case 42: {
            if (streamSubscriptions_ == null) {
              StreamSubscriptions = new WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange();
            }
            input.ReadMessage(StreamSubscriptions);
            break;
          }
          case 58: {
            if (noteRange_ == null) {
              NoteRange = new WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange();
            }
            input.ReadMessage(NoteRange);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (count_ == null) {
              Count = new WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange();
            }
            input.ReadMessage(Count);
            break;
          }
          case 26: {
            if (voice_ == null) {
              Voice = new WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange();
            }
            input.ReadMessage(Voice);
            break;
          }
          case 42: {
            if (streamSubscriptions_ == null) {
              StreamSubscriptions = new WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange();
            }
            input.ReadMessage(StreamSubscriptions);
            break;
          }
          case 58: {
            if (noteRange_ == null) {
              NoteRange = new WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange();
            }
            input.ReadMessage(NoteRange);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ClubStreamRangeSet : pb::IMessage<ClubStreamRangeSet>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ClubStreamRangeSet> _parser = new pb::MessageParser<ClubStreamRangeSet>(() => new ClubStreamRangeSet());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ClubStreamRangeSet> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.Club.V1.ClubRangeSetReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClubStreamRangeSet() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClubStreamRangeSet(ClubStreamRangeSet other) : this() {
      count_ = other.count_ != null ? other.count_.Clone() : null;
      nameRange_ = other.nameRange_ != null ? other.nameRange_.Clone() : null;
      subjectRange_ = other.subjectRange_ != null ? other.subjectRange_.Clone() : null;
      messageRange_ = other.messageRange_ != null ? other.messageRange_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClubStreamRangeSet Clone() {
      return new ClubStreamRangeSet(this);
    }

    /// <summary>Field number for the "count" field.</summary>
    public const int CountFieldNumber = 1;
    private WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange count_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange Count {
      get { return count_; }
      set {
        count_ = value;
      }
    }

    /// <summary>Field number for the "name_range" field.</summary>
    public const int NameRangeFieldNumber = 3;
    private WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange nameRange_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange NameRange {
      get { return nameRange_; }
      set {
        nameRange_ = value;
      }
    }

    /// <summary>Field number for the "subject_range" field.</summary>
    public const int SubjectRangeFieldNumber = 4;
    private WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange subjectRange_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange SubjectRange {
      get { return subjectRange_; }
      set {
        subjectRange_ = value;
      }
    }

    /// <summary>Field number for the "message_range" field.</summary>
    public const int MessageRangeFieldNumber = 5;
    private WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange messageRange_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange MessageRange {
      get { return messageRange_; }
      set {
        messageRange_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ClubStreamRangeSet);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ClubStreamRangeSet other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Count, other.Count)) return false;
      if (!object.Equals(NameRange, other.NameRange)) return false;
      if (!object.Equals(SubjectRange, other.SubjectRange)) return false;
      if (!object.Equals(MessageRange, other.MessageRange)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (count_ != null) hash ^= Count.GetHashCode();
      if (nameRange_ != null) hash ^= NameRange.GetHashCode();
      if (subjectRange_ != null) hash ^= SubjectRange.GetHashCode();
      if (messageRange_ != null) hash ^= MessageRange.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (count_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Count);
      }
      if (nameRange_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(NameRange);
      }
      if (subjectRange_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(SubjectRange);
      }
      if (messageRange_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(MessageRange);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (count_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Count);
      }
      if (nameRange_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(NameRange);
      }
      if (subjectRange_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(SubjectRange);
      }
      if (messageRange_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(MessageRange);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (count_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Count);
      }
      if (nameRange_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(NameRange);
      }
      if (subjectRange_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SubjectRange);
      }
      if (messageRange_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MessageRange);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ClubStreamRangeSet other) {
      if (other == null) {
        return;
      }
      if (other.count_ != null) {
        if (count_ == null) {
          Count = new WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange();
        }
        Count.MergeFrom(other.Count);
      }
      if (other.nameRange_ != null) {
        if (nameRange_ == null) {
          NameRange = new WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange();
        }
        NameRange.MergeFrom(other.NameRange);
      }
      if (other.subjectRange_ != null) {
        if (subjectRange_ == null) {
          SubjectRange = new WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange();
        }
        SubjectRange.MergeFrom(other.SubjectRange);
      }
      if (other.messageRange_ != null) {
        if (messageRange_ == null) {
          MessageRange = new WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange();
        }
        MessageRange.MergeFrom(other.MessageRange);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (count_ == null) {
              Count = new WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange();
            }
            input.ReadMessage(Count);
            break;
          }
          case 26: {
            if (nameRange_ == null) {
              NameRange = new WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange();
            }
            input.ReadMessage(NameRange);
            break;
          }
          case 34: {
            if (subjectRange_ == null) {
              SubjectRange = new WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange();
            }
            input.ReadMessage(SubjectRange);
            break;
          }
          case 42: {
            if (messageRange_ == null) {
              MessageRange = new WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange();
            }
            input.ReadMessage(MessageRange);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (count_ == null) {
              Count = new WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange();
            }
            input.ReadMessage(Count);
            break;
          }
          case 26: {
            if (nameRange_ == null) {
              NameRange = new WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange();
            }
            input.ReadMessage(NameRange);
            break;
          }
          case 34: {
            if (subjectRange_ == null) {
              SubjectRange = new WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange();
            }
            input.ReadMessage(SubjectRange);
            break;
          }
          case 42: {
            if (messageRange_ == null) {
              MessageRange = new WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange();
            }
            input.ReadMessage(MessageRange);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ClubInvitationRangeSet : pb::IMessage<ClubInvitationRangeSet>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ClubInvitationRangeSet> _parser = new pb::MessageParser<ClubInvitationRangeSet>(() => new ClubInvitationRangeSet());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ClubInvitationRangeSet> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.Club.V1.ClubRangeSetReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClubInvitationRangeSet() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClubInvitationRangeSet(ClubInvitationRangeSet other) : this() {
      count_ = other.count_ != null ? other.count_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClubInvitationRangeSet Clone() {
      return new ClubInvitationRangeSet(this);
    }

    /// <summary>Field number for the "count" field.</summary>
    public const int CountFieldNumber = 1;
    private WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange count_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange Count {
      get { return count_; }
      set {
        count_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ClubInvitationRangeSet);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ClubInvitationRangeSet other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Count, other.Count)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (count_ != null) hash ^= Count.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (count_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Count);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (count_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Count);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (count_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Count);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ClubInvitationRangeSet other) {
      if (other == null) {
        return;
      }
      if (other.count_ != null) {
        if (count_ == null) {
          Count = new WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange();
        }
        Count.MergeFrom(other.Count);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (count_ == null) {
              Count = new WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange();
            }
            input.ReadMessage(Count);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (count_ == null) {
              Count = new WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange();
            }
            input.ReadMessage(Count);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ClubSuggestionRangeSet : pb::IMessage<ClubSuggestionRangeSet>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ClubSuggestionRangeSet> _parser = new pb::MessageParser<ClubSuggestionRangeSet>(() => new ClubSuggestionRangeSet());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ClubSuggestionRangeSet> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.Club.V1.ClubRangeSetReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClubSuggestionRangeSet() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClubSuggestionRangeSet(ClubSuggestionRangeSet other) : this() {
      count_ = other.count_ != null ? other.count_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClubSuggestionRangeSet Clone() {
      return new ClubSuggestionRangeSet(this);
    }

    /// <summary>Field number for the "count" field.</summary>
    public const int CountFieldNumber = 1;
    private WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange count_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange Count {
      get { return count_; }
      set {
        count_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ClubSuggestionRangeSet);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ClubSuggestionRangeSet other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Count, other.Count)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (count_ != null) hash ^= Count.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (count_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Count);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (count_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Count);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (count_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Count);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ClubSuggestionRangeSet other) {
      if (other == null) {
        return;
      }
      if (other.count_ != null) {
        if (count_ == null) {
          Count = new WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange();
        }
        Count.MergeFrom(other.Count);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (count_ == null) {
              Count = new WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange();
            }
            input.ReadMessage(Count);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (count_ == null) {
              Count = new WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange();
            }
            input.ReadMessage(Count);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ClubTicketRangeSet : pb::IMessage<ClubTicketRangeSet>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ClubTicketRangeSet> _parser = new pb::MessageParser<ClubTicketRangeSet>(() => new ClubTicketRangeSet());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ClubTicketRangeSet> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.Club.V1.ClubRangeSetReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClubTicketRangeSet() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClubTicketRangeSet(ClubTicketRangeSet other) : this() {
      count_ = other.count_ != null ? other.count_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClubTicketRangeSet Clone() {
      return new ClubTicketRangeSet(this);
    }

    /// <summary>Field number for the "count" field.</summary>
    public const int CountFieldNumber = 1;
    private WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange count_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange Count {
      get { return count_; }
      set {
        count_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ClubTicketRangeSet);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ClubTicketRangeSet other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Count, other.Count)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (count_ != null) hash ^= Count.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (count_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Count);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (count_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Count);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (count_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Count);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ClubTicketRangeSet other) {
      if (other == null) {
        return;
      }
      if (other.count_ != null) {
        if (count_ == null) {
          Count = new WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange();
        }
        Count.MergeFrom(other.Count);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (count_ == null) {
              Count = new WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange();
            }
            input.ReadMessage(Count);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (count_ == null) {
              Count = new WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange();
            }
            input.ReadMessage(Count);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class ClubBanRangeSet : pb::IMessage<ClubBanRangeSet>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ClubBanRangeSet> _parser = new pb::MessageParser<ClubBanRangeSet>(() => new ClubBanRangeSet());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ClubBanRangeSet> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.Club.V1.ClubRangeSetReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClubBanRangeSet() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClubBanRangeSet(ClubBanRangeSet other) : this() {
      count_ = other.count_ != null ? other.count_.Clone() : null;
      reasonRange_ = other.reasonRange_ != null ? other.reasonRange_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClubBanRangeSet Clone() {
      return new ClubBanRangeSet(this);
    }

    /// <summary>Field number for the "count" field.</summary>
    public const int CountFieldNumber = 1;
    private WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange count_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange Count {
      get { return count_; }
      set {
        count_ = value;
      }
    }

    /// <summary>Field number for the "reason_range" field.</summary>
    public const int ReasonRangeFieldNumber = 3;
    private WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange reasonRange_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange ReasonRange {
      get { return reasonRange_; }
      set {
        reasonRange_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ClubBanRangeSet);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ClubBanRangeSet other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Count, other.Count)) return false;
      if (!object.Equals(ReasonRange, other.ReasonRange)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (count_ != null) hash ^= Count.GetHashCode();
      if (reasonRange_ != null) hash ^= ReasonRange.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (count_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Count);
      }
      if (reasonRange_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(ReasonRange);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (count_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Count);
      }
      if (reasonRange_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(ReasonRange);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (count_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Count);
      }
      if (reasonRange_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ReasonRange);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ClubBanRangeSet other) {
      if (other == null) {
        return;
      }
      if (other.count_ != null) {
        if (count_ == null) {
          Count = new WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange();
        }
        Count.MergeFrom(other.Count);
      }
      if (other.reasonRange_ != null) {
        if (reasonRange_ == null) {
          ReasonRange = new WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange();
        }
        ReasonRange.MergeFrom(other.ReasonRange);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (count_ == null) {
              Count = new WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange();
            }
            input.ReadMessage(Count);
            break;
          }
          case 26: {
            if (reasonRange_ == null) {
              ReasonRange = new WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange();
            }
            input.ReadMessage(ReasonRange);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (count_ == null) {
              Count = new WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange();
            }
            input.ReadMessage(Count);
            break;
          }
          case 26: {
            if (reasonRange_ == null) {
              ReasonRange = new WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649.Bgs.Protocol.UnsignedIntRange();
            }
            input.ReadMessage(ReasonRange);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
