using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

// This file is automatically generated, DO NOT EDIT

namespace WowPacketParserModule.V10_0_0_46181.UpdateFields.V10_0_2_46479
{
    public class CraftingOrder_Unk2 : ICraftingOrder_Unk2
    {
        public System.Nullable<long> field_0 { get; set; }
        public WowGuid field_8 { get; set; }
        public WowGuid field_18 { get; set; }
        public System.Nullable<int> field_28 { get; set; }
        public System.Nullable<uint> field_2C { get; set; }
        public System.Nullable<uint> field_30 { get; set; }
        public System.Nullable<byte> field_34 { get; set; }
        public bool field_35 { get; set; }
    }
}
