using System;
using System.Collections.Generic;
using WowPacketParser.Enums;

namespace WowPacketParserModule.V10_0_0_46181.Protos.V10_2_0_52649
{
    public static class ProtobufParser
    {
        private static readonly Dictionary<(ServiceHash, uint /*MethodId*/), (Google.Protobuf.MessageParser /*Request|Notification*/, Google.Protobuf.MessageParser /*Response*/)> Parsers = new()
        {
            { (ServiceHash.AccountService,          13u), (Bgs.Protocol.Account.V1.ResolveAccountRequest.Parser, Bgs.Protocol.Account.V1.ResolveAccountResponse.Parser) },
            { (ServiceHash.AccountService,          25u), (Bgs.Protocol.Account.V1.SubscriptionUpdateRequest.Parser, Bgs.Protocol.Account.V1.SubscriptionUpdateResponse.Parser) },
            { (ServiceHash.AccountService,          26u), (Bgs.Protocol.Account.V1.SubscriptionUpdateRequest.Parser, Bgs.Protocol.NoData.Parser) },
            { (ServiceHash.AccountService,          30u), (Bgs.Protocol.Account.V1.GetAccountStateRequest.Parser, Bgs.Protocol.Account.V1.GetAccountStateResponse.Parser) },
            { (ServiceHash.AccountService,          31u), (Bgs.Protocol.Account.V1.GetGameAccountStateRequest.Parser, Bgs.Protocol.Account.V1.GetGameAccountStateResponse.Parser) },
            { (ServiceHash.AccountService,          32u), (Bgs.Protocol.Account.V1.GetLicensesRequest.Parser, Bgs.Protocol.Account.V1.GetLicensesResponse.Parser) },
            { (ServiceHash.AccountService,          33u), (Bgs.Protocol.Account.V1.GetGameTimeRemainingInfoRequest.Parser, Bgs.Protocol.Account.V1.GetGameTimeRemainingInfoResponse.Parser) },
            { (ServiceHash.AccountService,          34u), (Bgs.Protocol.Account.V1.GetGameSessionInfoRequest.Parser, Bgs.Protocol.Account.V1.GetGameSessionInfoResponse.Parser) },
            { (ServiceHash.AccountService,          35u), (Bgs.Protocol.Account.V1.GetCAISInfoRequest.Parser, Bgs.Protocol.Account.V1.GetCAISInfoResponse.Parser) },
            { (ServiceHash.AccountService,          37u), (Bgs.Protocol.Account.V1.GetAuthorizedDataRequest.Parser, Bgs.Protocol.Account.V1.GetAuthorizedDataResponse.Parser) },
            { (ServiceHash.AccountService,          44u), (Bgs.Protocol.Account.V1.GetSignedAccountStateRequest.Parser, Bgs.Protocol.Account.V1.GetSignedAccountStateResponse.Parser) },
            { (ServiceHash.AccountService,          45u), (Bgs.Protocol.Account.V1.GetAccountInfoRequest.Parser, Bgs.Protocol.Account.V1.GetAccountInfoResponse.Parser) },
            { (ServiceHash.AccountService,          46u), (Bgs.Protocol.Account.V1.GetAccountPlatformRestrictionsRequest.Parser, Bgs.Protocol.Account.V1.GetAccountPlatformRestrictionsResponse.Parser) },
            { (ServiceHash.AuthenticationListener,   4u), (Bgs.Protocol.Authentication.V1.ServerStateChangeRequest.Parser, Bgs.Protocol.NO_RESPONSE.Parser) },
            { (ServiceHash.AuthenticationListener,   5u), (Bgs.Protocol.Authentication.V1.LogonResult.Parser, Bgs.Protocol.NO_RESPONSE.Parser) },
            { (ServiceHash.AuthenticationListener,  10u), (Bgs.Protocol.Authentication.V1.LogonUpdateRequest.Parser, Bgs.Protocol.NO_RESPONSE.Parser) },
            { (ServiceHash.AuthenticationListener,  11u), (Bgs.Protocol.Authentication.V1.VersionInfoNotification.Parser, Bgs.Protocol.NO_RESPONSE.Parser) },
            { (ServiceHash.AuthenticationListener,  12u), (Bgs.Protocol.Authentication.V1.LogonQueueUpdateRequest.Parser, Bgs.Protocol.NO_RESPONSE.Parser) },
            { (ServiceHash.AuthenticationListener,  13u), (Bgs.Protocol.NoData.Parser, Bgs.Protocol.NO_RESPONSE.Parser) },
            { (ServiceHash.AuthenticationService,    1u), (Bgs.Protocol.Authentication.V1.LogonRequest.Parser, Bgs.Protocol.NoData.Parser) },
            { (ServiceHash.AuthenticationService,    7u), (Bgs.Protocol.Authentication.V1.VerifyWebCredentialsRequest.Parser, Bgs.Protocol.NoData.Parser) },
            { (ServiceHash.AuthenticationService,    8u), (Bgs.Protocol.Authentication.V1.GenerateWebCredentialsRequest.Parser, Bgs.Protocol.Authentication.V1.GenerateWebCredentialsResponse.Parser) },
            { (ServiceHash.ChallengeService,         3u), (Bgs.Protocol.Challenge.V1.ChallengeExternalRequest.Parser, Bgs.Protocol.NO_RESPONSE.Parser) },
            { (ServiceHash.ChallengeService,         4u), (Bgs.Protocol.Challenge.V1.ChallengeExternalResult.Parser, Bgs.Protocol.NO_RESPONSE.Parser) },
            { (ServiceHash.ClubListener,             1u), (Bgs.Protocol.Club.V1.SubscribeNotification.Parser, Bgs.Protocol.NO_RESPONSE.Parser) },
            { (ServiceHash.ClubListener,             2u), (Bgs.Protocol.Club.V1.UnsubscribeNotification.Parser, Bgs.Protocol.NO_RESPONSE.Parser) },
            { (ServiceHash.ClubListener,             3u), (Bgs.Protocol.Club.V1.StateChangedNotification.Parser, Bgs.Protocol.NO_RESPONSE.Parser) },
            { (ServiceHash.ClubListener,             4u), (Bgs.Protocol.Club.V1.SettingsChangedNotification.Parser, Bgs.Protocol.NO_RESPONSE.Parser) },
            { (ServiceHash.ClubListener,            30u), (Bgs.Protocol.Club.V1.MemberAddedNotification.Parser, Bgs.Protocol.NO_RESPONSE.Parser) },
            { (ServiceHash.ClubListener,            31u), (Bgs.Protocol.Club.V1.MemberRemovedNotification.Parser, Bgs.Protocol.NO_RESPONSE.Parser) },
            { (ServiceHash.ClubListener,            32u), (Bgs.Protocol.Club.V1.MemberStateChangedNotification.Parser, Bgs.Protocol.NO_RESPONSE.Parser) },
            { (ServiceHash.ClubListener,            33u), (Bgs.Protocol.Club.V1.SubscriberStateChangedNotification.Parser, Bgs.Protocol.NO_RESPONSE.Parser) },
            { (ServiceHash.ClubListener,            34u), (Bgs.Protocol.Club.V1.MemberRoleChangedNotification.Parser, Bgs.Protocol.NO_RESPONSE.Parser) },
            { (ServiceHash.ClubListener,            50u), (Bgs.Protocol.Club.V1.InvitationAddedNotification.Parser, Bgs.Protocol.NO_RESPONSE.Parser) },
            { (ServiceHash.ClubListener,            51u), (Bgs.Protocol.Club.V1.InvitationRemovedNotification.Parser, Bgs.Protocol.NO_RESPONSE.Parser) },
            { (ServiceHash.ClubListener,            70u), (Bgs.Protocol.Club.V1.SuggestionAddedNotification.Parser, Bgs.Protocol.NO_RESPONSE.Parser) },
            { (ServiceHash.ClubListener,            71u), (Bgs.Protocol.Club.V1.SuggestionRemovedNotification.Parser, Bgs.Protocol.NO_RESPONSE.Parser) },
            { (ServiceHash.ClubListener,           100u), (Bgs.Protocol.Club.V1.StreamAddedNotification.Parser, Bgs.Protocol.NO_RESPONSE.Parser) },
            { (ServiceHash.ClubListener,           101u), (Bgs.Protocol.Club.V1.StreamRemovedNotification.Parser, Bgs.Protocol.NO_RESPONSE.Parser) },
            { (ServiceHash.ClubListener,           102u), (Bgs.Protocol.Club.V1.StreamStateChangedNotification.Parser, Bgs.Protocol.NO_RESPONSE.Parser) },
            { (ServiceHash.ClubListener,           150u), (Bgs.Protocol.Club.V1.StreamMessageAddedNotification.Parser, Bgs.Protocol.NO_RESPONSE.Parser) },
            { (ServiceHash.ClubListener,           152u), (Bgs.Protocol.Club.V1.StreamMessageUpdatedNotification.Parser, Bgs.Protocol.NO_RESPONSE.Parser) },
            { (ServiceHash.ClubListener,           153u), (Bgs.Protocol.Club.V1.StreamTypingIndicatorNotification.Parser, Bgs.Protocol.NO_RESPONSE.Parser) },
            { (ServiceHash.ClubListener,           154u), (Bgs.Protocol.Club.V1.StreamUnreadIndicatorNotification.Parser, Bgs.Protocol.NO_RESPONSE.Parser) },
            { (ServiceHash.ClubListener,           155u), (Bgs.Protocol.Club.V1.StreamAdvanceViewTimeNotification.Parser, Bgs.Protocol.NO_RESPONSE.Parser) },
            { (ServiceHash.ClubService,              1u), (Bgs.Protocol.Club.V1.SubscribeRequest.Parser, Bgs.Protocol.NoData.Parser) },
            { (ServiceHash.ClubService,              2u), (Bgs.Protocol.Club.V1.UnsubscribeRequest.Parser, Bgs.Protocol.NoData.Parser) },
            { (ServiceHash.ClubService,              3u), (Bgs.Protocol.Club.V1.CreateRequest.Parser, Bgs.Protocol.Club.V1.CreateResponse.Parser) },
            { (ServiceHash.ClubService,              4u), (Bgs.Protocol.Club.V1.DestroyRequest.Parser, Bgs.Protocol.NoData.Parser) },
            { (ServiceHash.ClubService,              5u), (Bgs.Protocol.Club.V1.GetDescriptionRequest.Parser, Bgs.Protocol.Club.V1.GetDescriptionResponse.Parser) },
            { (ServiceHash.ClubService,              6u), (Bgs.Protocol.Club.V1.GetClubTypeRequest.Parser, Bgs.Protocol.Club.V1.GetClubTypeResponse.Parser) },
            { (ServiceHash.ClubService,              7u), (Bgs.Protocol.Club.V1.UpdateClubStateRequest.Parser, Bgs.Protocol.NoData.Parser) },
            { (ServiceHash.ClubService,              8u), (Bgs.Protocol.Club.V1.UpdateClubSettingsRequest.Parser, Bgs.Protocol.NoData.Parser) },
            { (ServiceHash.ClubService,             30u), (Bgs.Protocol.Club.V1.JoinRequest.Parser, Bgs.Protocol.NoData.Parser) },
            { (ServiceHash.ClubService,             31u), (Bgs.Protocol.Club.V1.LeaveRequest.Parser, Bgs.Protocol.NoData.Parser) },
            { (ServiceHash.ClubService,             32u), (Bgs.Protocol.Club.V1.KickRequest.Parser, Bgs.Protocol.NoData.Parser) },
            { (ServiceHash.ClubService,             33u), (Bgs.Protocol.Club.V1.GetMemberRequest.Parser, Bgs.Protocol.Club.V1.GetMemberResponse.Parser) },
            { (ServiceHash.ClubService,             34u), (Bgs.Protocol.Club.V1.GetMembersRequest.Parser, Bgs.Protocol.Club.V1.GetMembersResponse.Parser) },
            { (ServiceHash.ClubService,             35u), (Bgs.Protocol.Club.V1.UpdateMemberStateRequest.Parser, Bgs.Protocol.NoData.Parser) },
            { (ServiceHash.ClubService,             36u), (Bgs.Protocol.Club.V1.UpdateSubscriberStateRequest.Parser, Bgs.Protocol.NoData.Parser) },
            { (ServiceHash.ClubService,             37u), (Bgs.Protocol.Club.V1.AssignRoleRequest.Parser, Bgs.Protocol.NoData.Parser) },
            { (ServiceHash.ClubService,             38u), (Bgs.Protocol.Club.V1.UnassignRoleRequest.Parser, Bgs.Protocol.NoData.Parser) },
            { (ServiceHash.ClubService,             50u), (Bgs.Protocol.Club.V1.SendInvitationRequest.Parser, Bgs.Protocol.NoData.Parser) },
            { (ServiceHash.ClubService,             51u), (Bgs.Protocol.Club.V1.AcceptInvitationRequest.Parser, Bgs.Protocol.NoData.Parser) },
            { (ServiceHash.ClubService,             52u), (Bgs.Protocol.Club.V1.DeclineInvitationRequest.Parser, Bgs.Protocol.NoData.Parser) },
            { (ServiceHash.ClubService,             53u), (Bgs.Protocol.Club.V1.RevokeInvitationRequest.Parser, Bgs.Protocol.NoData.Parser) },
            { (ServiceHash.ClubService,             54u), (Bgs.Protocol.Club.V1.GetInvitationRequest.Parser, Bgs.Protocol.Club.V1.GetInvitationResponse.Parser) },
            { (ServiceHash.ClubService,             55u), (Bgs.Protocol.Club.V1.GetInvitationsRequest.Parser, Bgs.Protocol.Club.V1.GetInvitationsResponse.Parser) },
            { (ServiceHash.ClubService,             60u), (Bgs.Protocol.Club.V1.SendSuggestionRequest.Parser, Bgs.Protocol.NoData.Parser) },
            { (ServiceHash.ClubService,             61u), (Bgs.Protocol.Club.V1.AcceptSuggestionRequest.Parser, Bgs.Protocol.NoData.Parser) },
            { (ServiceHash.ClubService,             62u), (Bgs.Protocol.Club.V1.DeclineSuggestionRequest.Parser, Bgs.Protocol.NoData.Parser) },
            { (ServiceHash.ClubService,             63u), (Bgs.Protocol.Club.V1.GetSuggestionRequest.Parser, Bgs.Protocol.Club.V1.GetSuggestionResponse.Parser) },
            { (ServiceHash.ClubService,             64u), (Bgs.Protocol.Club.V1.GetSuggestionsRequest.Parser, Bgs.Protocol.Club.V1.GetSuggestionsResponse.Parser) },
            { (ServiceHash.ClubService,             70u), (Bgs.Protocol.Club.V1.CreateTicketRequest.Parser, Bgs.Protocol.Club.V1.CreateTicketResponse.Parser) },
            { (ServiceHash.ClubService,             71u), (Bgs.Protocol.Club.V1.DestroyTicketRequest.Parser, Bgs.Protocol.NoData.Parser) },
            { (ServiceHash.ClubService,             72u), (Bgs.Protocol.Club.V1.RedeemTicketRequest.Parser, Bgs.Protocol.NoData.Parser) },
            { (ServiceHash.ClubService,             73u), (Bgs.Protocol.Club.V1.GetTicketRequest.Parser, Bgs.Protocol.Club.V1.GetTicketResponse.Parser) },
            { (ServiceHash.ClubService,             74u), (Bgs.Protocol.Club.V1.GetTicketsRequest.Parser, Bgs.Protocol.Club.V1.GetTicketsResponse.Parser) },
            { (ServiceHash.ClubService,             80u), (Bgs.Protocol.Club.V1.AddBanRequest.Parser, Bgs.Protocol.NoData.Parser) },
            { (ServiceHash.ClubService,             81u), (Bgs.Protocol.Club.V1.RemoveBanRequest.Parser, Bgs.Protocol.NoData.Parser) },
            { (ServiceHash.ClubService,             82u), (Bgs.Protocol.Club.V1.GetBanRequest.Parser, Bgs.Protocol.Club.V1.GetBanResponse.Parser) },
            { (ServiceHash.ClubService,             83u), (Bgs.Protocol.Club.V1.GetBansRequest.Parser, Bgs.Protocol.Club.V1.GetBansResponse.Parser) },
            { (ServiceHash.ClubService,            100u), (Bgs.Protocol.Club.V1.SubscribeStreamRequest.Parser, Bgs.Protocol.NoData.Parser) },
            { (ServiceHash.ClubService,            101u), (Bgs.Protocol.Club.V1.UnsubscribeStreamRequest.Parser, Bgs.Protocol.NoData.Parser) },
            { (ServiceHash.ClubService,            102u), (Bgs.Protocol.Club.V1.CreateStreamRequest.Parser, Bgs.Protocol.Club.V1.CreateStreamResponse.Parser) },
            { (ServiceHash.ClubService,            103u), (Bgs.Protocol.Club.V1.DestroyStreamRequest.Parser, Bgs.Protocol.NoData.Parser) },
            { (ServiceHash.ClubService,            104u), (Bgs.Protocol.Club.V1.GetStreamRequest.Parser, Bgs.Protocol.Club.V1.GetStreamResponse.Parser) },
            { (ServiceHash.ClubService,            105u), (Bgs.Protocol.Club.V1.GetStreamsRequest.Parser, Bgs.Protocol.Club.V1.GetStreamsResponse.Parser) },
            { (ServiceHash.ClubService,            106u), (Bgs.Protocol.Club.V1.UpdateStreamStateRequest.Parser, Bgs.Protocol.NoData.Parser) },
            { (ServiceHash.ClubService,            107u), (Bgs.Protocol.Club.V1.SetStreamFocusRequest.Parser, Bgs.Protocol.NoData.Parser) },
            { (ServiceHash.ClubService,            108u), (Bgs.Protocol.Club.V1.GetStreamVoiceTokenRequest.Parser, Bgs.Protocol.Club.V1.GetStreamVoiceTokenResponse.Parser) },
            { (ServiceHash.ClubService,            109u), (Bgs.Protocol.Club.V1.KickFromStreamVoiceRequest.Parser, Bgs.Protocol.NoData.Parser) },
            { (ServiceHash.ClubService,            150u), (Bgs.Protocol.Club.V1.CreateMessageRequest.Parser, Bgs.Protocol.Club.V1.CreateMessageResponse.Parser) },
            { (ServiceHash.ClubService,            151u), (Bgs.Protocol.Club.V1.DestroyMessageRequest.Parser, Bgs.Protocol.Club.V1.DestroyMessageResponse.Parser) },
            { (ServiceHash.ClubService,            152u), (Bgs.Protocol.Club.V1.EditMessageRequest.Parser, Bgs.Protocol.Club.V1.EditMessageResponse.Parser) },
            { (ServiceHash.ClubService,            153u), (Bgs.Protocol.Club.V1.SetMessagePinnedRequest.Parser, Bgs.Protocol.NoData.Parser) },
            { (ServiceHash.ClubService,            154u), (Bgs.Protocol.Club.V1.SetTypingIndicatorRequest.Parser, Bgs.Protocol.NoData.Parser) },
            { (ServiceHash.ClubService,            155u), (Bgs.Protocol.Club.V1.AdvanceStreamViewTimeRequest.Parser, Bgs.Protocol.NoData.Parser) },
            { (ServiceHash.ClubService,            156u), (Bgs.Protocol.Club.V1.GetStreamHistoryRequest.Parser, Bgs.Protocol.Club.V1.GetStreamHistoryResponse.Parser) },
            { (ServiceHash.ClubService,            157u), (Bgs.Protocol.Club.V1.GetStreamMessageRequest.Parser, Bgs.Protocol.Club.V1.GetStreamMessageResponse.Parser) },
            { (ServiceHash.ClubMembershipListener,   1u), (Bgs.Protocol.Club.V1.Membership.ClubAddedNotification.Parser, Bgs.Protocol.NO_RESPONSE.Parser) },
            { (ServiceHash.ClubMembershipListener,   2u), (Bgs.Protocol.Club.V1.Membership.ClubRemovedNotification.Parser, Bgs.Protocol.NO_RESPONSE.Parser) },
            { (ServiceHash.ClubMembershipListener,   3u), (Bgs.Protocol.Club.V1.Membership.ReceivedInvitationAddedNotification.Parser, Bgs.Protocol.NO_RESPONSE.Parser) },
            { (ServiceHash.ClubMembershipListener,   4u), (Bgs.Protocol.Club.V1.Membership.ReceivedInvitationRemovedNotification.Parser, Bgs.Protocol.NO_RESPONSE.Parser) },
            { (ServiceHash.ClubMembershipListener,   5u), (Bgs.Protocol.Club.V1.Membership.SharedSettingsChangedNotification.Parser, Bgs.Protocol.NO_RESPONSE.Parser) },
            { (ServiceHash.ClubMembershipListener,   6u), (Bgs.Protocol.Club.V1.Membership.StreamMentionAddedNotification.Parser, Bgs.Protocol.NO_RESPONSE.Parser) },
            { (ServiceHash.ClubMembershipListener,   7u), (Bgs.Protocol.Club.V1.Membership.StreamMentionRemovedNotification.Parser, Bgs.Protocol.NO_RESPONSE.Parser) },
            { (ServiceHash.ClubMembershipListener,   8u), (Bgs.Protocol.Club.V1.Membership.StreamMentionAdvanceViewTimeNotification.Parser, Bgs.Protocol.NO_RESPONSE.Parser) },
            { (ServiceHash.ClubMembershipService,    1u), (Bgs.Protocol.Club.V1.Membership.SubscribeRequest.Parser,Bgs.Protocol.Club.V1.Membership.SubscribeResponse.Parser) },
            { (ServiceHash.ClubMembershipService,    2u), (Bgs.Protocol.Club.V1.Membership.UnsubscribeRequest.Parser, Bgs.Protocol.NoData.Parser) },
            { (ServiceHash.ClubMembershipService,    3u), (Bgs.Protocol.Club.V1.Membership.GetStateRequest.Parser,Bgs.Protocol.Club.V1.Membership.GetStateResponse.Parser) },
            { (ServiceHash.ClubMembershipService,    4u), (Bgs.Protocol.Club.V1.Membership.UpdateClubSharedSettingsRequest.Parser, Bgs.Protocol.NoData.Parser) },
            { (ServiceHash.ClubMembershipService,    5u), (Bgs.Protocol.Club.V1.Membership.GetStreamMentionsRequest.Parser,Bgs.Protocol.Club.V1.Membership.GetStreamMentionsResponse.Parser) },
            { (ServiceHash.ClubMembershipService,    6u), (Bgs.Protocol.Club.V1.Membership.RemoveStreamMentionsRequest.Parser, Bgs.Protocol.NoData.Parser) },
            { (ServiceHash.ClubMembershipService,    7u), (Bgs.Protocol.Club.V1.Membership.AdvanceStreamMentionViewTimeRequest.Parser, Bgs.Protocol.NoData.Parser) },
            { (ServiceHash.ConnectionService,        1u), (Bgs.Protocol.Connection.V1.ConnectRequest.Parser, Bgs.Protocol.Connection.V1.ConnectResponse.Parser) },
            { (ServiceHash.ConnectionService,        2u), (Bgs.Protocol.Connection.V1.BindRequest.Parser, Bgs.Protocol.Connection.V1.BindResponse.Parser) },
            { (ServiceHash.ConnectionService,        3u), (Bgs.Protocol.Connection.V1.EchoRequest.Parser, Bgs.Protocol.Connection.V1.EchoResponse.Parser) },
            { (ServiceHash.ConnectionService,        4u), (Bgs.Protocol.Connection.V1.DisconnectNotification.Parser, Bgs.Protocol.NO_RESPONSE.Parser) },
            { (ServiceHash.ConnectionService,        5u), (Bgs.Protocol.NoData.Parser, Bgs.Protocol.NO_RESPONSE.Parser) },
            { (ServiceHash.ConnectionService,        6u), (Bgs.Protocol.Connection.V1.EncryptRequest.Parser, Bgs.Protocol.NoData.Parser) },
            { (ServiceHash.ConnectionService,        7u), (Bgs.Protocol.Connection.V1.DisconnectRequest.Parser, Bgs.Protocol.NO_RESPONSE.Parser) },
            { (ServiceHash.FriendsService,           1u), (Bgs.Protocol.Friends.V1.SubscribeRequest.Parser, Bgs.Protocol.Friends.V1.SubscribeResponse.Parser) },
            { (ServiceHash.FriendsService,           2u), (Bgs.Protocol.Friends.V1.SendInvitationRequest.Parser, Bgs.Protocol.NoData.Parser) },
            { (ServiceHash.FriendsService,           3u), (Bgs.Protocol.Friends.V1.AcceptInvitationRequest.Parser, Bgs.Protocol.NoData.Parser) },
            { (ServiceHash.FriendsService,           4u), (Bgs.Protocol.Friends.V1.RevokeInvitationRequest.Parser, Bgs.Protocol.NoData.Parser) },
            { (ServiceHash.FriendsService,           5u), (Bgs.Protocol.Friends.V1.DeclineInvitationRequest.Parser, Bgs.Protocol.NoData.Parser) },
            { (ServiceHash.FriendsService,           6u), (Bgs.Protocol.Friends.V1.IgnoreInvitationRequest.Parser, Bgs.Protocol.NoData.Parser) },
            { (ServiceHash.FriendsService,           8u), (Bgs.Protocol.Friends.V1.RemoveFriendRequest.Parser, Bgs.Protocol.NoData.Parser) },
            { (ServiceHash.FriendsService,           9u), (Bgs.Protocol.Friends.V1.ViewFriendsRequest.Parser, Bgs.Protocol.Friends.V1.ViewFriendsResponse.Parser) },
            { (ServiceHash.FriendsService,          10u), (Bgs.Protocol.Friends.V1.UpdateFriendStateRequest.Parser, Bgs.Protocol.NoData.Parser) },
            { (ServiceHash.FriendsService,          11u), (Bgs.Protocol.Friends.V1.UnsubscribeRequest.Parser, Bgs.Protocol.NoData.Parser) },
            { (ServiceHash.FriendsService,          12u), (Bgs.Protocol.Friends.V1.RevokeAllInvitationsRequest.Parser, Bgs.Protocol.NoData.Parser) },
            { (ServiceHash.FriendsService,          13u), (Bgs.Protocol.Friends.V1.GetFriendListRequest.Parser, Bgs.Protocol.Friends.V1.GetFriendListResponse.Parser) },
            { (ServiceHash.FriendsService,          14u), (Bgs.Protocol.Friends.V1.CreateFriendshipRequest.Parser, Bgs.Protocol.NoData.Parser) },
            { (ServiceHash.GameUtilitiesService,     1u), (Bgs.Protocol.GameUtilities.V1.ClientRequest.Parser, Bgs.Protocol.GameUtilities.V1.ClientResponse.Parser) },
            { (ServiceHash.GameUtilitiesService,     2u), (Bgs.Protocol.GameUtilities.V1.PresenceChannelCreatedRequest.Parser, Bgs.Protocol.NoData.Parser) },
            { (ServiceHash.GameUtilitiesService,     6u), (Bgs.Protocol.GameUtilities.V1.ServerRequest.Parser, Bgs.Protocol.GameUtilities.V1.ServerResponse.Parser) },
            { (ServiceHash.GameUtilitiesService,     7u), (Bgs.Protocol.GameUtilities.V1.GameAccountOnlineNotification.Parser, Bgs.Protocol.NO_RESPONSE.Parser) },
            { (ServiceHash.GameUtilitiesService,     8u), (Bgs.Protocol.GameUtilities.V1.GameAccountOfflineNotification.Parser, Bgs.Protocol.NO_RESPONSE.Parser) },
            { (ServiceHash.GameUtilitiesService,    10u), (Bgs.Protocol.GameUtilities.V1.GetAllValuesForAttributeRequest.Parser, Bgs.Protocol.GameUtilities.V1.GetAllValuesForAttributeResponse.Parser) },
            { (ServiceHash.GameUtilitiesService,    11u), (Bgs.Protocol.GameUtilities.V1.RegisterUtilitiesRequest.Parser, Bgs.Protocol.GameUtilities.V1.RegisterUtilitiesResponse.Parser) },
            { (ServiceHash.GameUtilitiesService,    12u), (Bgs.Protocol.GameUtilities.V1.UnregisterUtilitiesRequest.Parser, Bgs.Protocol.NO_RESPONSE.Parser) },
            { (ServiceHash.PresenceListener,         1u), (Bgs.Protocol.Presence.V1.SubscribeNotification.Parser, Bgs.Protocol.NO_RESPONSE.Parser) },
            { (ServiceHash.PresenceListener,         2u), (Bgs.Protocol.Presence.V1.StateChangedNotification.Parser, Bgs.Protocol.NO_RESPONSE.Parser) },
            { (ServiceHash.ReportService,            1u), (Bgs.Protocol.Report.V1.SendReportRequest.Parser, Bgs.Protocol.NoData.Parser) },
            { (ServiceHash.ReportService,            2u), (Bgs.Protocol.Report.V1.SubmitReportRequest.Parser, Bgs.Protocol.NoData.Parser) },
            { (ServiceHash.ReportServiceV2,          1u), (Bgs.Protocol.Report.V2.SubmitReportRequest.Parser, Bgs.Protocol.NoData.Parser) },
            { (ServiceHash.ResourceService,          1u), (Bgs.Protocol.Resources.V1.ContentHandleRequest.Parser, Bgs.Protocol.ContentHandle.Parser) },
            { (ServiceHash.ResourceService,          2u), (Bgs.Protocol.Resources.V1.GetTitleIconsRequest.Parser, Bgs.Protocol.Resources.V1.GetTitleIconsResponse.Parser) },
            { (ServiceHash.UserManagerService,       1u), (Bgs.Protocol.UserManager.V1.SubscribeRequest.Parser, Bgs.Protocol.UserManager.V1.SubscribeResponse.Parser) },
            { (ServiceHash.UserManagerService,      10u), (Bgs.Protocol.UserManager.V1.AddRecentPlayersRequest.Parser, Bgs.Protocol.NoData.Parser) },
            { (ServiceHash.UserManagerService,      11u), (Bgs.Protocol.UserManager.V1.ClearRecentPlayersRequest.Parser, Bgs.Protocol.NoData.Parser) },
            { (ServiceHash.UserManagerService,      20u), (Bgs.Protocol.UserManager.V1.BlockPlayerRequest.Parser, Bgs.Protocol.NoData.Parser) },
            { (ServiceHash.UserManagerService,      21u), (Bgs.Protocol.UserManager.V1.UnblockPlayerRequest.Parser, Bgs.Protocol.NoData.Parser) },
            { (ServiceHash.UserManagerService,      40u), (Bgs.Protocol.UserManager.V1.BlockPlayerRequest.Parser, Bgs.Protocol.NoData.Parser) },
            { (ServiceHash.UserManagerService,      51u), (Bgs.Protocol.UserManager.V1.UnsubscribeRequest.Parser, Bgs.Protocol.NoData.Parser) }
        };

        public static Google.Protobuf.MessageParser GetParser(uint serviceHash, uint methodId, int opcode)
        {
            var key = ((ServiceHash)serviceHash, methodId & 0x3FFFFFFF);
            if (!Parsers.ContainsKey(key))
                return null;

            return (opcode == WowPacketParser.Enums.Version.Opcodes.GetOpcode(Opcode.SMSG_BATTLENET_RESPONSE, Direction.ServerToClient)) ? Parsers[key].Item2 : Parsers[key].Item1;
        }

        public static string GetParserName(Google.Protobuf.MessageParser parser)
        {
            if (parser == null || parser.GetType().IsGenericType == false)
                return String.Empty;

            if (parser.GetType().GetGenericArguments().Length == 0)
                return String.Empty;

            var name = parser.GetType().GetGenericArguments()[0].ToString();

            return name.Replace(typeof(ProtobufParser).Namespace + ".", String.Empty);
        }
    }
}
