// <auto-generated>
// DO NOT EDIT
// </auto-generated>

using System.CodeDom.Compiler;
using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

namespace WowPacketParserModule.V11_0_0_55666.UpdateFields.V11_0_2_55959
{
    [GeneratedCode("UpdateFieldCodeGenerator.Formats.WowPacketParserHandler", "1.0.0.0")]
    public class SelectedAzeriteEssences : ISelectedAzeriteEssences
    {
        public System.Nullable<uint>[] AzeriteEssenceID { get; } = new System.Nullable<uint>[4];
        public System.Nullable<uint> SpecializationID { get; set; }
        public System.Nullable<bool> Enabled { get; set; }
    }
}

