// <auto-generated>
// DO NOT EDIT
// </auto-generated>

using System.CodeDom.Compiler;
using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

namespace WowPacketParserModule.V5_5_0_61735.UpdateFields.V5_5_2_64068
{
    [GeneratedCode("UpdateFieldCodeGenerator.Formats.WowPacketParserHandler", "1.0.0.0")]
    public class AreaTriggerData : IAreaTriggerData
    {
        public WowGuid Caster { get; set; }
        public System.Nullable<uint> Duration { get; set; }
        public System.Nullable<uint> TimeToTarget { get; set; }
        public System.Nullable<uint> TimeToTargetScale { get; set; }
        public System.Nullable<uint> TimeToTargetExtraScale { get; set; }
        public System.Nullable<uint> TimeToTargetPos { get; set; }
        public System.Nullable<int> SpellID { get; set; }
        public System.Nullable<int> SpellForVisuals { get; set; }
        public System.Nullable<int> SpellXSpellVisualID { get; set; }
        public System.Nullable<float> BoundsRadius2D { get; set; }
        public System.Nullable<uint> DecalPropertiesID { get; set; }
        public WowGuid CreatingEffectGUID { get; set; }
        public WowGuid OrbitPathTarget { get; set; }
        public Vector3 RollPitchYaw { get; set; }
        public System.Nullable<uint> MovementStartTime { get; set; }
        public System.Nullable<uint> CreationTime { get; set; }
        public System.Nullable<float> ZOffset { get; set; }
        public Vector3? TargetRollPitchYaw { get; set; }
        public System.Nullable<uint> Flags { get; set; }
        public System.Nullable<uint> ScaleCurveId { get; set; }
        public System.Nullable<uint> FacingCurveId { get; set; }
        public System.Nullable<uint> MorphCurveId { get; set; }
        public System.Nullable<uint> MoveCurveId { get; set; }
        public System.Nullable<float> Facing { get; set; }
        public IForceSetAreaTriggerPositionAndRotation ForcedPositionAndRotation { get; set; }
        public System.Nullable<int> PathType { get; set; }
        public System.Nullable<byte> ShapeType { get; set; }
        public IAreaTriggerMovementScript MovementScript { get; set; }
        public IAreaTriggerSphere Sphere { get; set; }
        public IAreaTriggerBox Box { get; set; }
        public IAreaTriggerPolygon Polygon { get; set; }
        public IAreaTriggerCylinder Cylinder { get; set; }
        public IScaleCurve OverrideScaleCurve { get; set; }
        public IScaleCurve ExtraScaleCurve { get; set; }
        public IScaleCurve OverrideMoveCurveX { get; set; }
        public IScaleCurve OverrideMoveCurveY { get; set; }
        public IScaleCurve OverrideMoveCurveZ { get; set; }
        public IVisualAnim VisualAnim { get; set; }
        public IAreaTriggerSplineCalculator Spline { get; set; }
        public IAreaTriggerOrbit Orbit { get; set; }
    }
}

