using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

// This file is automatically generated, DO NOT EDIT

namespace WowPacketParserModule.V3_4_0_45166.UpdateFields.V3_4_3_51666
{
    public class ContainerData : IContainerData
    {
        public WowGuid[] Slots { get; } = new WowGuid[36];
        public System.Nullable<uint> NumSlots { get; set; }
    }
}

