using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

// This file is automatically generated, DO NOT EDIT

namespace WowPacketParserModule.V3_4_0_45166.UpdateFields.V3_4_3_51666
{
    public class StableInfo : IStableInfo
    {
        public WowGuid StableMaster { get; set; }
        public DynamicUpdateField<IStablePetInfo> Pets { get; } = new DynamicUpdateField<IStablePetInfo>();
    }
}

