// <auto-generated>
// DO NOT EDIT
// </auto-generated>

using System.CodeDom.Compiler;
using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

namespace WowPacketParserModule.V4_4_0_54481.UpdateFields.V1_15_7_60000
{
    [GeneratedCode("UpdateFieldCodeGenerator.Formats.WowPacketParserHandler", "1.0.0.0")]
    public class AzeriteEmpoweredItemData : IAzeriteEmpoweredItemData
    {
        public System.Nullable<int>[] Selections { get; } = new System.Nullable<int>[5];
    }
}

