namespace WowPacketParser.Enums
{
    public enum CalendarError
    {
        // ReSharper disable InconsistentNaming
        NONE = 0,
        CALENDAR_ERROR_GUILD_EVENTS_EXCEEDED = 1,
        CALENDAR_ERROR_EVENTS_EXCEEDED = 2,
        CALENDAR_ERROR_SELF_INVITES_EXCEEDED = 3,
        CALENDAR_ERROR_OTHER_INVITES_EXCEEDED = 4,
        CALENDAR_ERROR_PERMISSIONS = 5,
        CALENDAR_ERROR_EVENT_INVALID = 6,
        CALENDAR_ERROR_NOT_INVITED = 7,
        CALENDAR_ERROR_INTERNAL = 8,
        ERR_GUILD_PLAYER_NOT_IN_GUILD = 9,
        CALENDAR_ERROR_ALREADY_INVITED_TO_EVENT_S = 10,
        PLAYER_NOT_FOUND = 11,
        CALENDAR_ERROR_NOT_ALLIED = 12,
        ERR_IGNORING_YOU_S = 13,
        CALENDAR_ERROR_INVITES_EXCEEDED = 14,
        CALENDAR_ERROR_INVALID_DATE = 16,
        CALENDAR_ERROR_INVALID_TIME = 17,

        CALENDAR_ERROR_NEEDS_TITLE = 19,
        CALENDAR_ERROR_EVENT_PASSED = 20,
        CALENDAR_ERROR_EVENT_LOCKED = 21,
        CALENDAR_ERROR_DELETE_CREATOR_FAILED = 22,
        ERR_SYSTEM_DISABLED = 24,
        ERR_RESTRICTED_ACCOUNT = 25,
        CALENDAR_ERROR_ARENA_EVENTS_EXCEEDED = 26,
        CALENDAR_ERROR_RESTRICTED_LEVEL = 27,
        ERR_USER_SQUELCHED = 28,
        CALENDAR_ERROR_NO_INVITE = 29,

        CALENDAR_ERROR_EVENT_WRONG_SERVER = 36,
        CALENDAR_ERROR_INVITE_WRONG_SERVER = 37,
        CALENDAR_ERROR_NO_GUILD_INVITES = 38,
        CALENDAR_ERROR_INVALID_SIGNUP = 39,
        CALENDAR_ERROR_NO_MODERATOR = 40
        // ReSharper restore InconsistentNaming
    }
}
