namespace WowPacketParser.Enums
{
    public enum GameObjectType
    {
        Door                 = 0,
        Button               = 1,
        QuestGiver           = 2,
        Chest                = 3,
        Binder               = 4,
        Generic              = 5,
        Trap                 = 6,
        Chair                = 7,
        SpellFocus           = 8,
        Text                 = 9,
        Goober               = 10,
        Transport            = 11,
        AreaDamage           = 12,
        Camera               = 13,
        MapObject            = 14,
        MOTransport          = 15,
        DuelFlag             = 16,
        FishingNode          = 17,
        SummoningRitual      = 18,
        Mailbox              = 19,
        DoNotUse1            = 20,
        GuardPost            = 21,
        SpellCaster          = 22,
        MeetingStone         = 23,
        FlagStand            = 24,
        FishingHole          = 25,
        FlagDrop             = 26,
        MiniGame             = 27,
        DoNotUse2            = 28,
        CapturePoint         = 29,
        AuraGenerator        = 30,
        DungeonDifficulty    = 31,
        BarberChair          = 32,
        DestructibleBuilding = 33,
        GuildBank            = 34,
        TrapDoor             = 35,
        GarrisonBuilding     = 38,
        GarrisonBuildingPlot = 39,
        ClientCreature       = 40,
        ClientItem           = 41,
        GarrisonBuilding2    = 43,
        GarrisonMonument     = 44,
        GarrisonShipment     = 45,
        GarrisonMonumentPlaque = 46
    }
}
