namespace WowPacketParser.Enums
{
    public enum GossipPOIIcon : uint
    {
        Blank                 = 0,
        GreyAlteracValleyMine = 1,
        RedAlteracValleyMine  = 2,
        BlueAlteracValleyMine = 3,
        BlueAndWhiteTombstone = 4,
        SmallHouse            = 5,
        GreyTower             = 6,
        RedFlag               = 7,
        Tombstone             = 8,
        BlueAndWhiteTower     = 9,
        RedTower              = 10,
        BlueTower             = 11,
        RedAndWhiteTower      = 12,
        RedTombstone          = 13,
        RedAndWhiteTombstone  = 14,
        BlueTombstone         = 15,
        Grey1                 = 16,
        BlueAndWhite1         = 17,
        Blue1                 = 18,
        RedAndWhite1          = 19,
        Red1                  = 20,
        GreyWoodLogs          = 21,
        BlueAndWhiteWoodLogs  = 22,
        BlueWoodLogs          = 23,
        RedAndWhiteWoodLogs   = 24,
        RedWoodLogs           = 25,
        Grey2                 = 26,
        BlueAndWhite2         = 27,
        Blue2                 = 28,
        RedAndWhite2          = 29,
        Red2                  = 30,
        GreyHouse             = 31,
        BlueAndWhiteHouse     = 32,
        BlueHouse             = 33,
        RedAndWhiteHouse      = 34,
        RedHouse              = 35,
        GreyHorse             = 36,
        BlueAndWhiteHorse     = 37,
        BlueHorse             = 38,
        RedAndWhiteHorse      = 39,
        RedHorse              = 40
    }
}
