namespace WowPacketParser.Enums
{
    public enum Holiday
    {
        None                          = 0,
        FireworksSpectacular          = 62,
        FeastOfWinterVeil             = 141,
        Noblegarden                   = 181,
        ChildrensWeek                 = 201,
        CallToArmsAlteracValley       = 283,
        CallToArmsWarsongGulch        = 284,
        CallToArmsArathiBasin         = 285,
        FishingExtravaganza           = 301,
        HarvestFestival               = 321,
        HallowsEnd                    = 324,
        LunarFestival                 = 327,
        LoveIsInTheAir                = 335,
        FireFestival                  = 341,
        CallToArmsEyeOfTheStorm       = 353,
        Brewfest                      = 372,
        DarkmoonFaireElwynn           = 374,
        DarkmoonFaireThunder          = 375,
        DarkmoonFaireShattrath        = 376,
        PiratesDay                    = 398,
        CallToArmsStrandOfTheAncients = 400,
        PilgrimsBounty                = 404,
        WrathOfTheLichKingLaunch      = 406,
        DayOfTheDead                  = 409,
        CallToArmsIsleOfConquest      = 420,
        LoveInTheAir                  = 423,
        FishingExtravaganza2          = 424,
        CallToArmsTheBattleForGilneas = 435,
        CallToArmsTwinPeaks           = 436,
        RatedBG15V15                  = 442,
        RatedBG25V25                  = 443,
        WoWs7ThAnniversary            = 467,
        WoWs8ThAnniversary            = 484,
        CallToArmsSilvershardMines    = 488,
        CallToArmsTempleOfKotmogu     = 489,
        WoWs9thAnniversary            = 509,
        WoWs10thAnniversary           = 514,
        CallToArmsDeepwindGorge1      = 515,
        CallToArmsDeepwindGorge2      = 516
    }
}
