namespace WowPacketParser.Enums
{
    public enum ItemModType : sbyte
    {
        None = -1,
        Mana = 0,
        Health = 1,
        Agility = 3,
        Strength = 4,
        Intellect = 5,
        Spirit = 6,
        Stamina = 7,
        DefenseSkillRating = 12,
        DodgeRating = 13,
        ParryRating = 14,
        BlockRating = 15,
        MeleeHitRating = 16,
        RangedHitRating = 17,
        SpellHitRating = 18,
        MeleeCritRating = 19,
        RangedCritRating = 20,
        SpellCritRating = 21,
        MeleeHitTakenRating = 22,
        RangedHitTakenRating = 23,
        SpellHitTakenRating = 24,
        MeleeCritTakenRating = 25,
        RangedCritTakenRating = 26,
        SpellCritTakenRating = 27,
        MeleeHasteRating = 28,
        RangedHasteRating = 29,
        SpellHasteRating = 30,
        HitRating = 31,
        CritRating = 32,
        HitTakenRating = 33,
        CritTakenRating = 34,
        ResilienceRating = 35,
        HasteRating = 36,
        ExpertiseRating = 37,
        AttackPower = 38,
        RangedAttackPower = 39,
        FeralAttackPowerOld = 40,
        SpellHealingDoneOld = 41,
        SpellDamageDoneOld = 42,
        ManaRegeneration = 43,
        ArmorPenetrationRating = 44,
        SpellPower = 45,
        HealthRegeneration = 46,
        SpellPenetration = 47,
        BlockValue = 48,
        Mastery = 49,
    }
}
