namespace WowPacketParser.Enums
{
    public enum ItemModifier : uint
    {
        TransmogrifyItemModifiedAppearanceIdSpecAll = 0,
        TransmogrifyItemModifiedAppearanceIdSpec0 = 1,
        IncrementLevelObsolete = 2,
        BattlePetSpecies = 3,
        BattlePetBreed = 4,
        BattlePetLevel = 5,
        BattlePetCreaturedisplayid = 6,
        TransmogrifyOverrideEnchantVisualIdSpecAll = 7,
        ArtifactAppearanceId = 8,
        TimewalkerLevel = 9,
        TransmogrifyOverrideEnchantVisualIdSpec0 = 10,
        TransmogrifyItemModifiedAppearanceIdSpec1 = 11,
        TransmogrifyOverrideEnchantVisualIdSpec1 = 12,
        TransmogrifyItemModifiedAppearanceIdSpec2 = 13,
        TransmogrifyOverrideEnchantVisualIdSpec2 = 14,
        TransmogrifyItemModifiedAppearanceIdSpec3 = 15,
        TransmogrifyOverrideEnchantVisualIdSpec3 = 16,
        KeystoneMapChallengeModeId = 17,
        KeystonePowerLevel = 18,
        KeystoneAffix0 = 19,
        KeystoneAffix01 = 20,
        KeystoneAffix02 = 21,
        KeystoneAffix03 = 22,
        LegionArtifactKnowledgeObsolete = 23,
        ArtifactTier = 24,
        TransmogrifyItemModifiedAppearanceIdSpec4 = 25,
        PvpRating = 26,
        TransmogrifyOverrideEnchantVisualIdSpec4 = 27,
        ContentTuningId = 28,
        ChangeModifiedCraftingStat1 = 29,
        ChangeModifiedCraftingStat2 = 30,
        TransmogrifySecondaryItemModifiedAppearanceIdSpecAll = 31,
        TransmogrifySecondaryItemModifiedAppearanceIdSpec0 = 32,
        TransmogrifySecondaryItemModifiedAppearanceIdSpec1 = 33,
        TransmogrifySecondaryItemModifiedAppearanceIdSpec2 = 34,
        TransmogrifySecondaryItemModifiedAppearanceIdSpec3 = 35,
        TransmogrifySecondaryItemModifiedAppearanceIdSpec4 = 36,
        SoulbindConduitRank = 37,
        CraftingQualityId = 38,
        CraftingSkillLineAbilityId = 39,
        CraftingDataId = 40,
        CraftingSkillReagents = 41,
        CraftingSkillWatermark = 42,
        CraftingReagentSlot0 = 43,
        CraftingReagentSlot1 = 44,
        CraftingReagentSlot2 = 45,
        CraftingReagentSlot3 = 46,
        CraftingReagentSlot4 = 47,
        CraftingReagentSlot5 = 48,
        CraftingReagentSlot6 = 49,
        CraftingReagentSlot7 = 50,
        CraftingReagentSlot8 = 51,
        CraftingReagentSlot9 = 52,
        CraftingReagentSlot10 = 53,
        CraftingReagentSlot11 = 54,
        CraftingReagentSlot12 = 55,
        CraftingReagentSlot13 = 56,
        CraftingReagentSlot14 = 57,
        Reforge = 58
    }
}
