namespace WowPacketParser.Enums
{
    public enum Language : uint
    {
        Universal      = 0,
        Orcish         = 1,
        Darnassian     = 2,
        Taurahe        = 3,
        Dwarvish       = 6,
        Common         = 7,
        Demonic        = 8,
        Titan          = 9,
        Thalassian     = 10,
        Draconic       = 11,
        Kalimag        = 12,
        Gnomish        = 13,
        Troll          = 14,
        Gutterspeak    = 33,
        Draenei        = 35,
        Zombie         = 36,
        GnomishBinary  = 37,
        GoblinBinary   = 38,
        Worgen         = 39,
        Goblin         = 40,
        Pandaren1      = 42,
        Pandaren2      = 43,
        Pandaren3      = 44,
        RikkitunSprite = 168,
        ShathYar       = 178,
        Nerglish       = 179,
        Moonkin        = 180,
        Shalassian     = 181,
        Thalassian2    = 182,
        AddonBfA       = 183,
        AddonLogged    = 184,
        Vulpera        = 285,
        ComplexCipher  = 287,
        BasicCypher    = 288,
        Metrial        = 290,
        Altonian       = 291,
        Sopranian      = 292,
        Aealic         = 293,
        Dealic         = 294,
        Trebelim       = 295,
        Bassalim       = 296,
        EmbeddedLanguages = 297,
        Unknowable     = 298,
        Addon          = uint.MaxValue
    }
}
