namespace WowPacketParser.Enums
{
    public enum Language : uint
    {
        Universal     = 0,
        Orcish        = 1,
        Darnassian    = 2,
        Taurahe       = 3,
        Dwarvish      = 6,
        Common        = 7,
        Demonic       = 8,
        Titan         = 9,
        Thalassian    = 10,
        Draconic      = 11,
        Kalimag       = 12,
        Gnomish       = 13,
        Troll         = 14,
        Gutterspeak   = 33,
        Draenei       = 35,
        Zombie        = 36,
        GnomishBinary = 37,
        GoblinBinary  = 38,
        Worgen        = 39,
        Goblin        = 40,
        Pandaren1     = 42,
        Pandaren2     = 43,
        Pandaren3     = 44,
        Rikkitun      = 168,
        Addon         = uint.MaxValue
    }

    public enum Language801 : uint
    {
        Universal     = 0,
        Orcish        = 1,
        Darnassian    = 2,
        Taurahe       = 3,
        Dwarvish      = 6,
        Common        = 7,
        Demonic       = 8,
        Titan         = 9,
        Thalassian    = 10,
        Draconic      = 11,
        Kalimag       = 12,
        Gnomish       = 13,
        Troll         = 14,
        Gutterspeak   = 33,
        Draenei       = 35,
        Zombie        = 36,
        GnomishBinary = 37,
        GoblinBinary  = 38,
        Worgen        = 39,
        Goblin        = 40,
        Pandaren1     = 42,
        Pandaren2     = 43,
        Pandaren3     = 44,
        Sprite        = 168,
        ShathYar      = 178,
        Nerglish      = 179,
        Moonkin       = 180,
        Shalassian    = 181,
        Thalassian2   = 182,
        Addon         = 183,
        AddonLogged   = 184
    }
}
