namespace WowPacketParser.Enums
{
    public enum QuestPushReason : byte
    {
        Success              = 0,    // "Sharing quest with %s..."
        Invalid              = 1,    // "%s is not eligible for that quest"
        Accepted             = 2,    // "%s has accepted your quest"
        Declined             = 3,    // "%s has declined your quest"
        Busy                 = 4,    // "%s is busy"
        Dead                 = 5,    // "%s is dead."
        LogFull              = 6,    // "%s's quest log is full"
        OnQuest              = 7,    // "%s is already on that quest"
        AlreadyDone          = 8,    // "%s has completed that quest"
        NotDaily             = 9,    // "That quest cannot be shared today"
        TimerExpired         = 10,   // "Quest sharing timer has expired"
        NotInParty           = 11,   // "You are not in a party"
        DifferentServerDaily = 12,   // "%s is not eligible for that quest today"
        NotAllowed           = 13    // "That quest cannot be shared"
    }

    public enum QuestPushReason915 : byte
    {
        Success                         = 0,    // "Sharing quest with %s..."
        Invalid                         = 1,    // "%s is not eligible for that quest"
        InvalidToRecipient              = 2,    // "%s's attempt to share quest "%s" failed. You are not eligible for that quest."
        Accepted                        = 3,    // "%s has accepted your quest"
        Declined                        = 4,    // "%s has declined your quest"
        Busy                            = 5,    // "%s is busy"
        Dead                            = 6,    // "%s is dead."
        DeadToRecipient                 = 7,    // "%s's attempt to share quest "%s" failed. You are dead."
        LogFull                         = 8,    // "%s's quest log is full"
        LogFullToRecipient              = 9,    // "%s's attempt to share quest "%s" failed. Your quest log is full."
        OnQuest                         = 10,   // "%s is already on that quest"
        OnQuestToRecipient              = 11,   // "%s's attempt to share quest "%s" failed. You are already on that quest."
        AlreadyDone                     = 12,   // "%s has completed that quest"
        AlreadyDoneToRecipient          = 13,   // "%s's attempt to share quest "%s" failed. You have completed that quest."
        NotDaily                        = 14,   // "That quest cannot be shared today"
        TimerExpired                    = 15,   // "Quest sharing timer has expired"
        NotInParty                      = 16,   // "You are not in a party"
        DifferentServerDaily            = 17,   // "%s is not eligible for that quest today"
        DifferentServerDailyToRecipient = 18,   // "%s's attempt to share quest "%s" failed. You are not eligible for that quest today."
        NotAllowed                      = 19,   // "That quest cannot be shared"
        Prerequisite                    = 20,   // "%s hasn't completed all of the prerequisite quests required for that quest."
        PrerequisiteToRecipient         = 21,   // "%s's attempt to share quest "%s" failed. You must complete all of the prerequisite quests first."
        LowLevel                        = 22,   // "%s is too low level for that quest."
        LowLevelToRecipient             = 23,   // "%s's attempt to share quest "%s" failed. You are too low level for that quest."
        HighLevel                       = 24,   // "%s is too high level for that quest."
        HighLevelToRecipient            = 25,   // "%s's attempt to share quest "%s" failed. You are too high level for that quest."
        Class                           = 26,   // "%s is the wrong class for that quest."
        ClassToRecipient                = 27,   // "%s's attempt to share quest "%s" failed. You are the wrong class for that quest."
        Race                            = 28,   // "%s is the wrong race for that quest."
        RaceToRecipient                 = 29,   // "%s's attempt to share quest "%s" failed. You are the wrong race for that quest."
        LowFaction                      = 30,   // "%s's reputation is too low for that quest."
        LowFactionToRecipient           = 31,   // "%s's attempt to share quest "%s" failed. Your reputation is too low for that quest."
        Expansion                       = 32,   // "%s doesn't own the required expansion for that quest."
        ExpansionToRecipient            = 33,   // "%s's attempt to share quest "%s" failed. You do not own the required expansion for that quest."
        NotGarrisonOwner                = 34,   // "%s must own a garrison to accept that quest."
        NotGarrisonOwnerToRecipient     = 35,   // "%s's attempt to share quest "%s" failed. You must own a garrison to accept that quest."
        WrongCovenant                   = 36,   // "%s is in the wrong covenant for that quest."
        WrongCovenantToRecipient        = 37,   // "%s's attempt to share quest "%s" failed. You are in the wrong covenant for that quest."
        NewPlayerExperience             = 38,   // "%s must complete Exile's Reach to accept that quest."
        NewPlayerExperienceToRecipient  = 39,   // "%s's attempt to share quest "%s" failed. You must complete Exile's Reach to accept that quest."
        WrongFaction                    = 40,   // "%s is the wrong faction for that quest."
        WrongFactionToRecipient         = 41    // "%s's attempt to share quest "%s" failed. You are the wrong faction for that quest."
    }
}
