namespace WowPacketParser.Enums
{
    public enum SpellModOp
    {
        Damage                 = 0,
        Duration               = 1,
        Threat                 = 2,
        Effect1                = 3,
        Charges                = 4,
        Range                  = 5,
        Radius                 = 6,
        CritChance             = 7,
        AllEffects             = 8,
        NotLoseCastTime        = 9,
        CastingTime            = 10,
        Cooldown               = 11,
        Effect2                = 12,
        IgnoreArmor            = 13,
        Cost                   = 14,
        CritDamageBonus        = 15,
        ResistMissChance       = 16,
        JumpTargets            = 17,
        ChanceOfSuccess        = 18,
        ActivationTimer        = 19,
        DmgMultiplier          = 20,
        GlobalCooldown         = 21,
        Dot                    = 22,
        Effect3                = 23,
        BonusMultiplier        = 24,
        Unk25                  = 25,
        ProcPerMinute          = 26,
        ValueMultiplier        = 27,
        ResistDispelChance     = 28,
        CritDamageBonus2       = 29,
        SpellCostRefoundOnFail = 30,
        Unk41                  = 41,
        Unk51                  = 51,
        Unk71                  = 71,
        Unk215                 = 215
    }
}
