namespace WowPacketParser.Enums
{
    public enum TotemCategory
    {
        None                     = 0,
        SkinningSkifeOld         = 1,
        EarthTotem               = 2,
        AirTotem                 = 3,
        FireTotem                = 4,
        WaterTotem               = 5,
        CopperRod                = 6,
        SilverRod                = 7,
        GoldenRod                = 8,
        TruesilverRod            = 9,
        ArcaniteRod              = 10,
        MiningPickOld            = 11,
        PhilosophersStone        = 12,
        BlacksmithHammerOld      = 13,
        ArclightSpanner          = 14,
        GyromaticMA              = 15,
        MasterTotem              = 21,
        FelIronRod               = 41,
        AdamantiteRod            = 62,
        EterniumRod              = 63,
        HollowQuill              = 81,
        RunedAzuriteRod          = 101,
        VirtuosoInkingSet        = 121,
        Drums                    = 141,
        GnomishArmyKnife         = 161,
        BlacksmithHammer         = 162,
        MiningPick               = 165,
        SkinningKnife            = 166,
        HammerPick               = 167,
        BladedPickaxe            = 168,
        FlintAndTinder           = 169,
        RunedCobaltRod           = 189,
        RunedTitaniumRod         = 190,
        RunedCopperRod1          = 209,
        HighPoweredBoltGun       = 210,
        RunedCopperRod2          = 230,
        JewelersKit              = 238,
        UltimateGnomishArmyKnife = 250
    }
}
