// <auto-generated>
// DO NOT EDIT
// </auto-generated>

using System.CodeDom.Compiler;
using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

namespace WowPacketParserModule.V4_4_0_54481.UpdateFields.V1_15_5_57638
{
    [GeneratedCode("UpdateFieldCodeGenerator.Formats.WowPacketParserHandler", "1.0.0.0")]
    public class DelveData : IDelveData
    {
        public int Field_0 { get; set; }
        public ulong Field_8 { get; set; }
        public int Field_10 { get; set; }
        public int SpellID { get; set; }
        public WowGuid[] Owners { get; set; }
        public uint Started { get; set; }
    }
}

