using System.Collections.Generic;

namespace WowPacketParser.Enums.Version//.V4_3_3_15354
{
    public static partial class Opcodes
    {
        private static readonly Dictionary<Opcode, int> _V4_3_3_opcodes = new Dictionary<Opcode, int>
        {
            {Opcode.CMSG_AREATRIGGER, 0x33A4},
            {Opcode.CMSG_AUTH_SESSION, 0x0A02},
            {Opcode.CMSG_CHAR_ENUM, 0x2161},
            {Opcode.CMSG_CREATURE_QUERY, 0x23ED},
            {Opcode.CMSG_GAMEOBJ_USE, 0x7B64},
            {Opcode.CMSG_GAMEOBJECT_QUERY, 0x6B65},
            {Opcode.CMSG_GOSSIP_HELLO, 0x65AC},
            {Opcode.CMSG_GOSSIP_SELECT_OPTION, 0x2724},
            {Opcode.CMSG_ITEM_REFUND_INFO, 0x6FE4},
            {Opcode.CMSG_LOAD_SCREEN, 0x3101},
            {Opcode.CMSG_NPC_TEXT_QUERY, 0x7CA5},
            {Opcode.CMSG_PLAYED_TIME, 0x68E5},
            {Opcode.CMSG_PLAYER_LOGIN, 0x3320},
            {Opcode.CMSG_QUERY_TIME, 0x3625},
            {Opcode.CMSG_QUESTGIVER_ACCEPT_QUEST, 0x3065},
            {Opcode.CMSG_QUESTGIVER_CHOOSE_REWARD, 0x2BAD},
            {Opcode.CMSG_QUESTGIVER_COMPLETE_QUEST, 0x796D},
            {Opcode.CMSG_QUESTGIVER_QUERY_QUEST, 0x7AED},
            {Opcode.CMSG_QUESTGIVER_STATUS_MULTIPLE_QUERY, 0x77E4},
            {Opcode.CMSG_QUESTGIVER_STATUS_QUERY, 0x6024},
            {Opcode.CMSG_QUESTLOG_REMOVE_QUEST, 0x7665},
            {Opcode.CMSG_READY_FOR_ACCOUNT_DATA_TIMES, 0x2924},
            {Opcode.CMSG_REALM_SPLIT, 0x66AD},
            {Opcode.CMSG_REDIRECTION_AUTH_PROOF,0x0A26},
            {Opcode.CMSG_REQUEST_ACCOUNT_DATA, 0x29A4},
            {Opcode.CMSG_REQUEST_RAID_INFO, 0x60ED},
            {Opcode.CMSG_SELL_ITEM, 0x2B25},
            {Opcode.CMSG_SET_ACTIONBAR_TOGGLES, 0x74A5},
            {Opcode.CMSG_SET_SELECTION, 0x2325},
            {Opcode.CMSG_SETSHEATHED, 0x2AED},
            {Opcode.CMSG_USE_ITEM, 0x352D},
            {Opcode.CMSG_WARDEN_DATA, 0x0202},
            {Opcode.CMSG_WORLD_STATE_UI_TIMER_UPDATE, 0x39E5},
            {Opcode.CMSG_ZONEUPDATE, 0x3125},
            {Opcode.SMSG_ACCOUNT_DATA_TIMES, 0x622D},
            {Opcode.SMSG_ADDON_INFO, 0x22AD},
            {Opcode.SMSG_ALL_ACHIEVEMENT_DATA, 0x390E},
            {Opcode.SMSG_ATTACKERSTATEUPDATE, 0x306D},
            {Opcode.SMSG_AURA_UPDATE, 0x3A24},
            {Opcode.SMSG_AURA_UPDATE_ALL, 0x7A25},
            {Opcode.SMSG_AUTH_CHALLENGE, 0x0055},
            {Opcode.SMSG_AUTH_RESPONSE, 0x3C84},
            {Opcode.SMSG_CHAR_ENUM, 0x30C6},
            {Opcode.SMSG_CLIENTCACHE_VERSION, 0x306C},
            {Opcode.SMSG_CONTACT_LIST, 0x2D65},
            {Opcode.SMSG_CORPSE_RECLAIM_DELAY, 0x79EC},
            {Opcode.SMSG_CREATURE_QUERY_RESPONSE, 0x6424},
            {Opcode.SMSG_EQUIPMENT_SET_LIST, 0x6AED},
            {Opcode.SMSG_GAMEOBJECT_QUERY_RESPONSE, 0x64AC},
            {Opcode.SMSG_GOSSIP_COMPLETE, 0x21AC},
            {Opcode.SMSG_GOSSIP_MESSAGE, 0x7664},
            {Opcode.SMSG_GUILD_QUERY_RESPONSE, 0x2BEC},
            {Opcode.SMSG_INIT_WORLD_STATES, 0x272C},
            {Opcode.SMSG_INITIAL_SPELLS, 0x7364},
            {Opcode.SMSG_INITIALIZE_FACTIONS, 0x3865},
            {Opcode.SMSG_LEARNED_DANCE_MOVES, 0x2CEC},
            {Opcode.SMSG_LOGIN_SETTIMESPEED, 0x6B2D},
            {Opcode.SMSG_LOGIN_VERIFY_WORLD, 0x3EE5},
            {Opcode.SMSG_MESSAGECHAT, 0x2FEC},
            {Opcode.SMSG_MONSTER_MOVE, 0x29A5},
            {Opcode.SMSG_MOTD, 0x3C6D},
            {Opcode.SMSG_NPC_TEXT_UPDATE, 0x646C},
            {Opcode.SMSG_QUEST_QUERY_RESPONSE, 0x2AAD},
            {Opcode.SMSG_QUESTGIVER_QUEST_DETAILS, 0x23E5},
            {Opcode.SMSG_REDIRECT_CLIENT, 0x0855},
            {Opcode.SMSG_SEND_UNLEARN_SPELLS, 0x78AC},
            {Opcode.SMSG_SET_PHASE_SHIFT, 0x7104},
            {Opcode.SMSG_SET_PROFICIENCY, 0x7324},
            {Opcode.SMSG_SPELL_GO, 0x6425},
            {Opcode.SMSG_SPELL_START, 0x212D},
            {Opcode.SMSG_TALENTS_INFO, 0x7FA5},
            {Opcode.SMSG_TUTORIAL_FLAGS, 0x25A4},
            {Opcode.SMSG_UPDATE_ACTION_BUTTONS, 0x604C},
            {Opcode.SMSG_UPDATE_OBJECT, 0x6264},
        };
    }
}
