using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

// This file is automatically generated, DO NOT EDIT

namespace WowPacketParserModule.V10_0_0_46181.UpdateFields.V10_0_7_48676
{
    public class SelectedAzeriteEssences : ISelectedAzeriteEssences
    {
        public System.Nullable<uint>[] AzeriteEssenceID { get; } = new System.Nullable<uint>[4];
        public System.Nullable<uint> SpecializationID { get; set; }
        public System.Nullable<bool> Enabled { get; set; }
    }
}

