using WowPacketParser.Misc;

namespace WowPacketParser.Enums.Version.V6_0_3_19103
{
    public static class Opcodes_6_0_3
    {
        public static BiDictionary<Opcode, int> Opcodes()
        {
            return Opcs;
        }

        private static readonly BiDictionary<Opcode, int> Opcs = new BiDictionary<Opcode, int>
        {
            {Opcode.CMSG_ADDON_REGISTERED_PREFIXES, 0x03F4 | 0x10000},
            {Opcode.CMSG_AUCTION_HELLO, 0x13EA},
            {Opcode.CMSG_AUTH_SESSION, 0x0487},
            {Opcode.CMSG_AREATRIGGER, 0x01B4},
            {Opcode.CMSG_BANKER_ACTIVATE, 0x1B24},
            {Opcode.CMSG_CANCEL_TRADE, 0x1159},
            {Opcode.CMSG_CAST_SPELL, 0x08FE},
            {Opcode.CMSG_CHAR_CREATE, 0x070D},
            {Opcode.CMSG_CHAR_DELETE, 0x030E},
            {Opcode.CMSG_CHAR_ENUM, 0x0918},
            {Opcode.CMSG_CHAR_UNDELETE_ENUM, 0x0F2D},
            {Opcode.CMSG_CREATURE_QUERY, 0x0505},
            {Opcode.CMSG_DB_QUERY_BULK, 0x138B | 0x10000},
            {Opcode.CMSG_EQUIPMENT_SET_SAVE, 0x1B54},
            {Opcode.CMSG_FACTION_BONUS_INFO, 0x0928},
            {Opcode.CMSG_JOIN_CHANNEL, 0x0B4B},
            {Opcode.CMSG_GAMEOBJ_REPORT_USE, 0x082E},
            {Opcode.CMSG_GAMEOBJECT_QUERY, 0x0D97},
            {Opcode.CMSG_GOSSIP_HELLO, 0x00F3},
            {Opcode.CMSG_GOSSIP_SELECT_OPTION, 0x0332 | 0x10000},
            {Opcode.CMSG_GUILD_QUERY, 0x0930},
            {Opcode.CMSG_GUILD_REQUEST_PARTY_STATE, 0x0A8E},
            {Opcode.CMSG_LOAD_SCREEN, 0x0B08},
            {Opcode.CMSG_LOG_DISCONNECT, 0x04D5},
            {Opcode.CMSG_LOGOUT_REQUEST, 0x1911},
            {Opcode.CMSG_ITEM_REFUND_INFO, 0x0924},
            {Opcode.CMSG_MESSAGECHAT_AFK, 0x1BDC | 0x10000},
            {Opcode.CMSG_MESSAGECHAT_DND, 0x0AAB | 0x10000},
            {Opcode.CMSG_MESSAGECHAT_CHANNEL, 0x0913 | 0x10000},
            {Opcode.CMSG_MESSAGECHAT_EMOTE, 0x113C | 0x10000},
            {Opcode.CMSG_MESSAGECHAT_GUILD, 0x0B1B | 0x10000},
            {Opcode.CMSG_MESSAGECHAT_PARTY, 0x0134},
            {Opcode.CMSG_MESSAGECHAT_SAY, 0x1884 | 0x10000},
            {Opcode.CMSG_MESSAGECHAT_YELL, 0x1161 | 0x10000},
            {Opcode.CMSG_MOVE_TIME_SKIPPED, 0x19C2},
            {Opcode.CMSG_NAME_QUERY, 0x0B15},
            {Opcode.CMSG_NPC_TEXT_QUERY, 0x0ECB},
            {Opcode.CMSG_PAGE_TEXT_QUERY, 0x0BBB},
            {Opcode.CMSG_PING, 0x0416},
            {Opcode.CMSG_PET_NAME_QUERY, 0x1433},
            {Opcode.CMSG_PET_ACTION, 0x133A},
            {Opcode.CMSG_PLAYER_LOGIN, 0x0B1D},
            {Opcode.CMSG_QUESTGIVER_QUERY_QUEST, 0x1924},
            {Opcode.CMSG_QUESTGIVER_STATUS_QUERY, 0x0704},
            {Opcode.CMSG_QUESTGIVER_STATUS_MULTIPLE_QUERY, 0x0131},
            {Opcode.CMSG_QUEST_NPC_QUERY, 0x0B81},
            {Opcode.CMSG_QUEST_POI_QUERY, 0x0BD9},
            {Opcode.CMSG_QUEST_QUERY, 0x09A6},
            {Opcode.CMSG_REDIRECT_AUTH_PROOF, 0x0485},
            {Opcode.CMSG_REORDER_CHARACTERS, 0x0DAA},
            {Opcode.CMSG_REQUEST_ACCOUNT_DATA, 0x0F3E},
            {Opcode.CMSG_RESET_FACTION_CHEAT, 0x0C56},
            {Opcode.CMSG_SAVE_CUF_PROFILES, 0x0053},
            {Opcode.CMSG_SET_RAID_DIFFICULTY, 0x04DF},
            {Opcode.CMSG_SEND_MAIL, 0x0910},
            {Opcode.CMSG_SET_SELECTION, 0x05BD},
            {Opcode.CMSG_SUSPEND_TOKEN, 0x0142},
            {Opcode.CMSG_TEXT_EMOTE, 0x1901 | 0x10000},
            {Opcode.CMSG_TIME_SYNC_RESP, 0x0003},
            {Opcode.CMSG_UNDELETE_CHARACTER, 0x0D99},
            {Opcode.CMSG_UNDELETE_COOLDOWN_STATUS_QUERY, 0x19A9},
            {Opcode.CMSG_UPDATE_ACCOUNT_DATA, 0x12A1},
            {Opcode.CMSG_VIOLENCE_LEVEL, 0x098D | 0x10000},
            {Opcode.CMSG_WARDEN_DATA, 0x0BA1 | 0x10000},
            {Opcode.CMSG_WHO, 0x1322},

            {Opcode.SMSG_ACCOUNT_DATA_TIMES, 0x0120},
            {Opcode.SMSG_ACTION_BUTTONS, 0x1D1F},
            {Opcode.SMSG_ADDON_INFO, 0x1D9F},
            {Opcode.SMSG_ALL_ACHIEVEMENT_DATA_ACCOUNT, 0x0123},
            {Opcode.SMSG_ALL_ACHIEVEMENT_DATA_PLAYER, 0x0030},
            {Opcode.SMSG_ARENA_SEASON_WORLD_STATE, 0x09E3},
            {Opcode.SMSG_ATTACKERSTATEUPDATE, 0x1204},
            {Opcode.SMSG_ATTACKSTART, 0x1D3E},
            {Opcode.SMSG_ATTACKSTOP, 0x1382},
            {Opcode.SMSG_AUCTION_COMMAND_RESULT, 0x0B2D},
            {Opcode.SMSG_AUCTION_HELLO, 0x011F},
            {Opcode.SMSG_AUCTION_LIST_RESULT, 0x19D2 | 0x20000},
            {Opcode.SMSG_AURA_UPDATE, 0x091C},
            {Opcode.SMSG_AUTH_RESPONSE, 0x0DA9},
            {Opcode.SMSG_AUTH_CHALLENGE, 0x1759},
            {Opcode.SMSG_BATTLE_PET_JOURNAL, 0x19A2},
            {Opcode.SMSG_BINDPOINTUPDATE, 0x0A30},
            {Opcode.SMSG_CHANNEL_NOTIFY, 0x0643},
            {Opcode.SMSG_CHANNEL_NOTIFY_JOINED, 0x1602},
            {Opcode.SMSG_CHAR_CREATE, 0x0107},
            {Opcode.SMSG_CHAR_DELETE, 0x0BC4},
            {Opcode.SMSG_CHAR_ENUM, 0x05AF},
            {Opcode.SMSG_CRITERIA_UPDATE_ACCOUNT, 0x0912},
            {Opcode.SMSG_CRITERIA_UPDATE_PLAYER, 0x1904},
            {Opcode.SMSG_CLIENTCACHE_VERSION, 0x080D},
            {Opcode.SMSG_CORPSE_RECLAIM_DELAY, 0x0BE2},
            {Opcode.SMSG_CREATURE_QUERY_RESPONSE, 0x0A26},
            {Opcode.SMSG_DB_REPLY, 0x1939},
            {Opcode.SMSG_EMOTE, 0x071D | 0x20000},
            {Opcode.SMSG_EQUIPMENT_SET_LIST, 0x0F1E},
            {Opcode.SMSG_EQUIPMENT_SET_SAVED, 0x0027},
            {Opcode.SMSG_FEATURE_SYSTEM_STATUS, 0x0B1E},
            {Opcode.SMSG_FEATURE_SYSTEM_STATUS_GLUE_SCREEN, 0x1540},
            {Opcode.SMSG_FLIGHT_SPLINE_SYNC, 0x08A5},
            {Opcode.SMSG_FORCE_SEND_QUEUED_PACKETS, 0x07C9},
            {Opcode.SMSG_INITIAL_SETUP, 0x0B07},
            {Opcode.SMSG_INITIAL_SPELLS, 0x0A81},
            {Opcode.SMSG_INIT_CURRENCY,  0x0B06},
            {Opcode.SMSG_INIT_WORLD_STATES, 0x0B04},
            {Opcode.SMSG_INITIALIZE_FACTIONS, 0x0B10},
            {Opcode.SMSG_ITEM_ENCHANT_TIME_UPDATE, 0x010D},
            {Opcode.SMSG_LEARNED_SPELL, 0x08AB},
            {Opcode.SMSG_LIST_INVENTORY, 0x0940},
            {Opcode.SMSG_LFG_PLAYER_INFO, 0x0F36},
            {Opcode.SMSG_LOAD_CUF_PROFILES, 0x1530},
            {Opcode.SMSG_LOGIN_VERIFY_WORLD, 0x0B19 | 0x20000},
            {Opcode.SMSG_LOGIN_SETTIMESPEED, 0x09AA},
            {Opcode.SMSG_LOGOUT_COMPLETE, 0x0B21},
            {Opcode.SMSG_LOGOUT_RESPONSE, 0x052D},
            {Opcode.SMSG_GAMEOBJECT_QUERY_RESPONSE, 0x128A},
            {Opcode.SMSG_GOSSIP_COMPLETE, 0x15D1},
            {Opcode.SMSG_GOSSIP_MESSAGE, 0x1746},
            {Opcode.SMSG_GOSSIP_POI, 0x011E},
            {Opcode.SMSG_GUILD_ACHIEVEMENT_DATA, 0x1866},
            {Opcode.SMSG_GUILD_EVENT, 0x1027},
            {Opcode.SMSG_GUILD_EVENT_PRESENCE_CHANGE, 0x1228},
            {Opcode.SMSG_GUILD_MOTD, 0x1825},
            {Opcode.SMSG_GUILD_QUERY_RESPONSE, 0x1046},
            {Opcode.SMSG_GUILD_RANK, 0x1218},
            {Opcode.SMSG_GUILD_RECIPES, 0x1078},
            {Opcode.SMSG_GUILD_ROSTER, 0x1026},
            {Opcode.SMSG_GUILD_PARTY_STATE_RESPONSE, 0x1225},
            {Opcode.SMSG_HIGHEST_THREAT_UPDATE, 0x059A},
            {Opcode.SMSG_HOTFIX_INFO, 0x1D1D},
            {Opcode.SMSG_MAIL_LIST_RESULT, 0x0B3F},
            {Opcode.SMSG_MESSAGECHAT, 0x0603},
            {Opcode.SMSG_MONSTER_MOVE, 0x0994},
            {Opcode.SMSG_MOTD, 0x0442},
            {Opcode.SMSG_NAME_QUERY_RESPONSE, 0x0828},
            {Opcode.SMSG_NEW_WORLD, 0x0206},
            {Opcode.SMSG_NPC_TEXT_UPDATE, 0x1122},
            {Opcode.SMSG_PAGE_TEXT_QUERY_RESPONSE, 0x05A0},
            {Opcode.SMSG_PET_NAME_QUERY_RESPONSE, 0x0D0E},
            {Opcode.SMSG_PET_SPELLS, 0x0174},
            {Opcode.SMSG_PERIODICAURALOG, 0x0B1B},
            {Opcode.SMSG_PLAYER_MOVE, 0x0ACE},
            {Opcode.SMSG_PONG, 0x17CA},
            {Opcode.SMSG_POWER_UPDATE, 0x0B27},
            {Opcode.SMSG_QUESTGIVER_QUEST_DETAILS, 0x15B3},
            {Opcode.SMSG_QUESTGIVER_STATUS, 0x1567},
            {Opcode.SMSG_QUESTGIVER_STATUS_MULTIPLE, 0x17C6},
            {Opcode.SMSG_QUEST_NPC_QUERY_RESPONSE, 0x1591},
            {Opcode.SMSG_QUEST_POI_QUERY_RESPONSE, 0x1715},
            {Opcode.SMSG_QUEST_QUERY_RESPONSE, 0x1547},
            {Opcode.SMSG_REDIRECT_CLIENT, 0x175A},
            {Opcode.SMSG_SEND_MAIL_RESULT, 0x0302 | 0x20000},
            {Opcode.SMSG_SET_TIME_ZONE_INFORMATION, 0x153E},
            {Opcode.SMSG_SEND_UNLEARN_SPELLS, 0x1A82},
            {Opcode.SMSG_SET_FLAT_SPELL_MODIFIER, 0x1884 | 0x20000},
            {Opcode.SMSG_SET_PCT_SPELL_MODIFIER, 0x113C | 0x20000},
            {Opcode.SMSG_SET_PHASE_SHIFT, 0x00D1},
            {Opcode.SMSG_SET_PROFICIENCY, 0x00D3},
            {Opcode.SMSG_SET_VIGNETTE, 0x09AC},
            {Opcode.SMSG_SPELL_CATEGORY_COOLDOWN, 0x082A | 0x20000},
            {Opcode.SMSG_SPELL_GO, 0x1161 | 0x20000},
            {Opcode.SMSG_SPELL_START, 0x0803},
            {Opcode.SMSG_SPELLENERGIZELOG, 0x137C},
            {Opcode.SMSG_SPELLHEALLOG, 0x0114},
            {Opcode.SMSG_SPELLLOGEXECUTE, 0x1823},
            {Opcode.SMSG_SPELLNONMELEEDAMAGELOG, 0x11FB},
            {Opcode.SMSG_SPLINE_MOVE_SET_FLIGHT_SPEED, 0x060C},
            {Opcode.SMSG_SPLINE_MOVE_SET_RUN_SPEED, 0x1B9A},
            {Opcode.SMSG_SPLINE_MOVE_SET_RUN_BACK_SPEED, 0x0086},
            {Opcode.SMSG_SPLINE_MOVE_SET_SWIM_SPEED, 0x098D},
            {Opcode.SMSG_SPLINE_MOVE_SET_WALK_SPEED, 0x01D5},
            {Opcode.SMSG_SUSPEND_COMMS, 0x076A},
            {Opcode.SMSG_SUSPEND_TOKEN_RESPONSE, 0x12A2},
            {Opcode.SMSG_TALENTS_INFO, 0x012D},
            {Opcode.SMSG_TEXT_EMOTE, 0x0383},
            {Opcode.SMSG_TRAINER_LIST, 0x0BA9},
            {Opcode.SMSG_TRANSFER_PENDING, 0x172A},
            {Opcode.SMSG_TIME_SYNC_REQ, 0x03B1},
            {Opcode.SMSG_TUTORIAL_FLAGS, 0x020F},
            {Opcode.SMSG_UNDELETE_CHARACTER_RESPONSE, 0x0344},
            {Opcode.SMSG_UNDELETE_COOLDOWN_STATUS_RESPONSE, 0x0310},
            {Opcode.SMSG_UPDATE_ACCOUNT_DATA, 0x1520},
            {Opcode.SMSG_UPDATE_OBJECT, 0x122C},
            {Opcode.SMSG_UPDATE_WORLD_STATE, 0x03EC},
            {Opcode.SMSG_WARDEN_DATA, 0x0BEC},
            {Opcode.SMSG_WEATHER, 0x073E},
            {Opcode.SMSG_WEEKLY_SPELL_USAGE, 0x13DC},
            {Opcode.SMSG_WHO, 0x0601},
            {Opcode.SMSG_WORLD_SERVER_INFO, 0x11AC},
        };
    }
}
