using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

// This file is automatically generated, DO NOT EDIT

namespace WowPacketParserModule.V9_0_1_36216.UpdateFields.V9_2_5_43903
{
    public class ActivePlayerUnk901 : IActivePlayerUnk901
    {
        public WowGuid Field_0 { get; set; }
        public System.Nullable<int> Field_10 { get; set; }
    }
}

