using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

// This file is automatically generated, DO NOT EDIT

namespace WowPacketParserModule.V9_0_1_36216.UpdateFields.V9_2_5_43903
{
    public class QuestSession : IQuestSession
    {
        public WowGuid Owner { get; set; }
        public System.Nullable<ulong>[] QuestCompleted { get; } = new System.Nullable<ulong>[875];
    }
}

