// <auto-generated>
// DO NOT EDIT
// </auto-generated>

using System.CodeDom.Compiler;
using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

namespace WowPacketParserModule.V3_4_0_45166.UpdateFields.V3_4_4_59817
{
    [GeneratedCode("UpdateFieldCodeGenerator.Formats.WowPacketParserHandler", "1.0.0.0")]
    public class VisibleItem : IMutableVisibleItem
    {
        public System.Nullable<int> ItemID { get; set; }
        public System.Nullable<int> SecondaryItemModifiedAppearanceID { get; set; }
        public System.Nullable<int> ConditionalItemAppearanceID { get; set; }
        public System.Nullable<ushort> ItemAppearanceModID { get; set; }
        public System.Nullable<ushort> ItemVisual { get; set; }
    }
}

