using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

// This file is automatically generated, DO NOT EDIT

namespace WowPacketParserModule.V10_0_0_46181.UpdateFields.V10_2_5_52902
{
    public class LevelLinkInfo : ILevelLinkInfo
    {
        public WowGuid TargetGUID { get; set; }
        public System.Nullable<int> Level { get; set; }
    }
}

