// <auto-generated>
// DO NOT EDIT
// </auto-generated>

using System.CodeDom.Compiler;
using WowPacketParser.Misc;
using WowPacketParser.Store.Objects;
using WowPacketParser.Store.Objects.UpdateFields;

namespace WowPacketParserModule.V11_0_0_55666.UpdateFields.V11_1_0_59347
{
    [GeneratedCode("UpdateFieldCodeGenerator.Formats.WowPacketParserHandler", "1.0.0.0")]
    public class CraftingOrder : ICraftingOrder
    {
        public DynamicUpdateField<ItemEnchantData> Enchantments { get; } = new DynamicUpdateField<ItemEnchantData>();
        public DynamicUpdateField<ItemGemData> Gems { get; } = new DynamicUpdateField<ItemGemData>();
        public ICraftingOrderData Data { get; set; }
    }
}

