// <auto-generated>
// DO NOT EDIT
// </auto-generated>

using System.CodeDom.Compiler;
using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

namespace WowPacketParserModule.V11_0_0_55666.UpdateFields.V11_1_0_59347
{
    [GeneratedCode("UpdateFieldCodeGenerator.Formats.WowPacketParserHandler", "1.0.0.0")]
    public class SceneObjectData : ISceneObjectData
    {
        public System.Nullable<int> ScriptPackageID { get; set; }
        public System.Nullable<uint> RndSeedVal { get; set; }
        public WowGuid CreatedBy { get; set; }
        public System.Nullable<uint> SceneType { get; set; }
    }
}

