using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

// This file is automatically generated, DO NOT EDIT

namespace WowPacketParserModule.V4_4_0_53627.UpdateFields.V4_4_0_53627
{
    public class CompletedProject : ICompletedProject
    {
        public System.Nullable<uint> ProjectID { get; set; }
        public System.Nullable<long> FirstCompleted { get; set; }
        public System.Nullable<uint> CompletionCount { get; set; }
    }
}

