using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

// This file is automatically generated, DO NOT EDIT

namespace WowPacketParserModule.V4_4_0_53627.UpdateFields.V4_4_0_53627
{
    public class CustomTabardInfo : ICustomTabardInfo
    {
        public System.Nullable<int> EmblemStyle { get; set; }
        public System.Nullable<int> EmblemColor { get; set; }
        public System.Nullable<int> BorderStyle { get; set; }
        public System.Nullable<int> BorderColor { get; set; }
        public System.Nullable<int> BackgroundColor { get; set; }
    }
}

