namespace WowPacketParserModule.V5_4_8_18414.Enums
{
    public enum ObjectField
    {
        OBJECT_FIELD_GUID                                        = 0x0, // Size: 2, Flags: UF_FLAG_PUBLIC
        OBJECT_FIELD_GUID2,
        OBJECT_FIELD_DATA                                        = 0x2, // Size: 2, Flags: UF_FLAG_PUBLIC
        OBJECT_FIELD_DATA2,
        OBJECT_FIELD_TYPE                                        = 0x4, // Size: 1, Flags: UF_FLAG_PUBLIC
        OBJECT_FIELD_ENTRY_ID                                    = 0x5, // Size: 1, Flags: UF_FLAG_VIEWER_DEPENDENT
        OBJECT_FIELD_DYNAMIC_FLAGS                               = 0x6, // Size: 1, Flags: UF_FLAG_VIEWER_DEPENDENT, UF_FLAG_URGENT
        OBJECT_FIELD_SCALE                                       = 0x7, // Size: 1, Flags: UF_FLAG_PUBLIC
        OBJECT_END                                               = 0x8,
    }

    public enum ItemField
    {
        ITEM_FIELD_OWNER                                         = ObjectField.OBJECT_END + 0x00, // Size: 2, Flags: UF_FLAG_PUBLIC
        ITEM_FIELD_OWNER2,
        ITEM_FIELD_CONTAINED_IN                                  = ObjectField.OBJECT_END + 0x02, // Size: 2, Flags: UF_FLAG_PUBLIC
        ITEM_FIELD_CONTAINED_IN2,
        ITEM_FIELD_CREATOR                                       = ObjectField.OBJECT_END + 0x04, // Size: 2, Flags: UF_FLAG_PUBLIC
        ITEM_FIELD_CREATOR2,
        ITEM_FIELD_GIFT_CREATOR                                  = ObjectField.OBJECT_END + 0x06, // Size: 2, Flags: UF_FLAG_PUBLIC
        ITEM_FIELD_GIFT_CREATOR2,
        ITEM_FIELD_STACK_COUNT                                   = ObjectField.OBJECT_END + 0x08, // Size: 1, Flags: UF_FLAG_OWNER
        ITEM_FIELD_EXPIRATION                                    = ObjectField.OBJECT_END + 0x09, // Size: 1, Flags: UF_FLAG_OWNER
        ITEM_FIELD_SPELL_CHARGES                                 = ObjectField.OBJECT_END + 0x0A, // Size: 5, Flags: UF_FLAG_OWNER
        ITEM_FIELD_SPELL_CHARGES2,
        ITEM_FIELD_SPELL_CHARGES3,
        ITEM_FIELD_SPELL_CHARGES4,
        ITEM_FIELD_SPELL_CHARGES5,
        ITEM_FIELD_DYNAMIC_FLAGS                                 = ObjectField.OBJECT_END + 0x0F, // Size: 1, Flags: UF_FLAG_PUBLIC
        ITEM_FIELD_ENCHANTMENT                                   = ObjectField.OBJECT_END + 0x10, // Size: 39, Flags: UF_FLAG_PUBLIC
        ITEM_FIELD_ENCHANTMENT1_2,
        ITEM_FIELD_ENCHANTMENT1_3,
        ITEM_FIELD_ENCHANTMENT2_1,
        ITEM_FIELD_ENCHANTMENT2_2,
        ITEM_FIELD_ENCHANTMENT2_3,
        ITEM_FIELD_ENCHANTMENT3_1,
        ITEM_FIELD_ENCHANTMENT3_2,
        ITEM_FIELD_ENCHANTMENT3_3,
        ITEM_FIELD_ENCHANTMENT4_1,
        ITEM_FIELD_ENCHANTMENT4_2,
        ITEM_FIELD_ENCHANTMENT4_3,
        ITEM_FIELD_ENCHANTMENT5_1,
        ITEM_FIELD_ENCHANTMENT5_2,
        ITEM_FIELD_ENCHANTMENT5_3,
        ITEM_FIELD_ENCHANTMENT6_1,
        ITEM_FIELD_ENCHANTMENT6_2,
        ITEM_FIELD_ENCHANTMENT6_3,
        ITEM_FIELD_ENCHANTMENT7_1,
        ITEM_FIELD_ENCHANTMENT7_2,
        ITEM_FIELD_ENCHANTMENT7_3,
        ITEM_FIELD_ENCHANTMENT8_1,
        ITEM_FIELD_ENCHANTMENT8_2,
        ITEM_FIELD_ENCHANTMENT8_3,
        ITEM_FIELD_ENCHANTMENT9_1,
        ITEM_FIELD_ENCHANTMENT9_2,
        ITEM_FIELD_ENCHANTMENT9_3,
        ITEM_FIELD_ENCHANTMENT10_1,
        ITEM_FIELD_ENCHANTMENT10_2,
        ITEM_FIELD_ENCHANTMENT10_3,
        ITEM_FIELD_ENCHANTMENT11_1,
        ITEM_FIELD_ENCHANTMENT11_2,
        ITEM_FIELD_ENCHANTMENT11_3,
        ITEM_FIELD_ENCHANTMENT12_1,
        ITEM_FIELD_ENCHANTMENT12_2,
        ITEM_FIELD_ENCHANTMENT12_3,
        ITEM_FIELD_ENCHANTMENT13_1,
        ITEM_FIELD_ENCHANTMENT13_2,
        ITEM_FIELD_ENCHANTMENT13_3,
        ITEM_FIELD_PROPERTY_SEED                                 = ObjectField.OBJECT_END + 0x37, // Size: 1, Flags: UF_FLAG_PUBLIC
        ITEM_FIELD_RANDOM_PROPERTIES_ID                          = ObjectField.OBJECT_END + 0x38, // Size: 1, Flags: UF_FLAG_PUBLIC
        ITEM_FIELD_DURABILITY                                    = ObjectField.OBJECT_END + 0x39, // Size: 1, Flags: UF_FLAG_OWNER
        ITEM_FIELD_MAX_DURABILITY                                = ObjectField.OBJECT_END + 0x3A, // Size: 1, Flags: UF_FLAG_OWNER
        ITEM_FIELD_CREATE_PLAYED_TIME                            = ObjectField.OBJECT_END + 0x3B, // Size: 1, Flags: UF_FLAG_PUBLIC
        ITEM_FIELD_MODIFIERS_MASK                                = ObjectField.OBJECT_END + 0x3C, // Size: 1, Flags: UF_FLAG_OWNER
        ITEM_END                                                 = ObjectField.OBJECT_END + 0x3D,
    }

    public enum ContainerField
    {
        CONTAINER_FIELD_SLOT                                    = ItemField.ITEM_END + 0x00, // Size: 72, Flags: UF_FLAG_PUBLIC
        CONTAINER_FIELD_SLOTh,
        CONTAINER_FIELD_SLOT2,
        CONTAINER_FIELD_SLOT2h,
        CONTAINER_FIELD_SLOT3,
        CONTAINER_FIELD_SLOT3h,
        CONTAINER_FIELD_SLOT4,
        CONTAINER_FIELD_SLOT4h,
        CONTAINER_FIELD_SLOT5,
        CONTAINER_FIELD_SLOT5h,
        CONTAINER_FIELD_SLOT6,
        CONTAINER_FIELD_SLOT6h,
        CONTAINER_FIELD_SLOT7,
        CONTAINER_FIELD_SLOT7h,
        CONTAINER_FIELD_SLOT8,
        CONTAINER_FIELD_SLOT8h,
        CONTAINER_FIELD_SLOT9,
        CONTAINER_FIELD_SLOT9h,
        CONTAINER_FIELD_SLOT10,
        CONTAINER_FIELD_SLOT10h,
        CONTAINER_FIELD_SLOT11,
        CONTAINER_FIELD_SLOT11h,
        CONTAINER_FIELD_SLOT12,
        CONTAINER_FIELD_SLOT12h,
        CONTAINER_FIELD_SLOT13,
        CONTAINER_FIELD_SLOT13h,
        CONTAINER_FIELD_SLOT14,
        CONTAINER_FIELD_SLOT14h,
        CONTAINER_FIELD_SLOT15,
        CONTAINER_FIELD_SLOT15h,
        CONTAINER_FIELD_SLOT16,
        CONTAINER_FIELD_SLOT16h,
        CONTAINER_FIELD_SLOT17,
        CONTAINER_FIELD_SLOT17h,
        CONTAINER_FIELD_SLOT18,
        CONTAINER_FIELD_SLOT18h,
        CONTAINER_FIELD_SLOT19,
        CONTAINER_FIELD_SLOT19h,
        CONTAINER_FIELD_SLOT20,
        CONTAINER_FIELD_SLOT20h,
        CONTAINER_FIELD_SLOT21,
        CONTAINER_FIELD_SLOT21h,
        CONTAINER_FIELD_SLOT22,
        CONTAINER_FIELD_SLOT22h,
        CONTAINER_FIELD_SLOT23,
        CONTAINER_FIELD_SLOT23h,
        CONTAINER_FIELD_SLOT24,
        CONTAINER_FIELD_SLOT24h,
        CONTAINER_FIELD_SLOT25,
        CONTAINER_FIELD_SLOT25h,
        CONTAINER_FIELD_SLOT26,
        CONTAINER_FIELD_SLOT26h,
        CONTAINER_FIELD_SLOT27,
        CONTAINER_FIELD_SLOT27h,
        CONTAINER_FIELD_SLOT28,
        CONTAINER_FIELD_SLOT28h,
        CONTAINER_FIELD_SLOT29,
        CONTAINER_FIELD_SLOT29h,
        CONTAINER_FIELD_SLOT30,
        CONTAINER_FIELD_SLOT30h,
        CONTAINER_FIELD_SLOT31,
        CONTAINER_FIELD_SLOT31h,
        CONTAINER_FIELD_SLOT32,
        CONTAINER_FIELD_SLOT32h,
        CONTAINER_FIELD_SLOT33,
        CONTAINER_FIELD_SLOT33h,
        CONTAINER_FIELD_SLOT34,
        CONTAINER_FIELD_SLOT34h,
        CONTAINER_FIELD_SLOT35,
        CONTAINER_FIELD_SLOT35h,
        CONTAINER_FIELD_SLOT36,
        CONTAINER_FIELD_SLOT36h,
        CONTAINER_FIELD_NUM_SLOTS                                = ItemField.ITEM_END + 0x48, // Size: 1, Flags: UF_FLAG_PUBLIC
        CONTAINER_END                                            = ItemField.ITEM_END + 0x49
    }

    public enum UnitField
    {
        UNIT_FIELD_CHARM                                         = ObjectField.OBJECT_END + 0x00, // Size: 2, Flags: UF_FLAG_PUBLIC
        UNIT_FIELD_CHARM2,
        UNIT_FIELD_SUMMON                                        = ObjectField.OBJECT_END + 0x02, // Size: 2, Flags: UF_FLAG_PUBLIC
        UNIT_FIELD_SUMMON2,
        UNIT_FIELD_CRITTER                                       = ObjectField.OBJECT_END + 0x04, // Size: 2, Flags: UF_FLAG_PRIVATE
        UNIT_FIELD_CRITTER2,
        UNIT_FIELD_CHARMED_BY                                    = ObjectField.OBJECT_END + 0x06, // Size: 2, Flags: UF_FLAG_PUBLIC
        UNIT_FIELD_CHARMED_BY2,
        UNIT_FIELD_SUMMONED_BY                                   = ObjectField.OBJECT_END + 0x08, // Size: 2, Flags: UF_FLAG_PUBLIC
        UNIT_FIELD_SUMMONED_BY2,
        UNIT_FIELD_CREATED_BY                                    = ObjectField.OBJECT_END + 0x0A, // Size: 2, Flags: UF_FLAG_PUBLIC
        UNIT_FIELD_CREATED_BY2,
        UNIT_FIELD_DEMON_CREATOR                                 = ObjectField.OBJECT_END + 0x0C, // Size: 2, Flags: UF_FLAG_PUBLIC
        UNIT_FIELD_DEMON_CREATOR2,
        UNIT_FIELD_TARGET                                        = ObjectField.OBJECT_END + 0x0E, // Size: 2, Flags: UF_FLAG_PUBLIC
        UNIT_FIELD_TARGET2,
        UNIT_FIELD_BATTLE_PET_COMPANION_GUID                     = ObjectField.OBJECT_END + 0x10, // Size: 2, Flags: UF_FLAG_PUBLIC
        UNIT_FIELD_BATTLE_PET_COMPANION_GUID2,
        UNIT_FIELD_CHANNEL_OBJECT                                = ObjectField.OBJECT_END + 0x12, // Size: 2, Flags: UF_FLAG_PUBLIC, UF_FLAG_URGENT
        UNIT_FIELD_CHANNEL_OBJECT2,
        UNIT_FIELD_CHANNEL_SPELL                                 = ObjectField.OBJECT_END + 0x14, // Size: 1, Flags: UF_FLAG_PUBLIC, UF_FLAG_URGENT
        UNIT_FIELD_SUMMONED_BY_HOME_REALM                        = ObjectField.OBJECT_END + 0x15, // Size: 1, Flags: UF_FLAG_PUBLIC
        UNIT_FIELD_SEX                                           = ObjectField.OBJECT_END + 0x16, // Size: 1, Flags: UF_FLAG_PUBLIC
        UNIT_FIELD_DISPLAY_POWER                                 = ObjectField.OBJECT_END + 0x17, // Size: 1, Flags: UF_FLAG_PUBLIC
        UNIT_FIELD_OVERRIDE_DISPLAY_POWER_ID                     = ObjectField.OBJECT_END + 0x18, // Size: 1, Flags: UF_FLAG_PUBLIC
        UNIT_FIELD_HEALTH                                        = ObjectField.OBJECT_END + 0x19, // Size: 1, Flags: UF_FLAG_PUBLIC
        UNIT_FIELD_POWER                                         = ObjectField.OBJECT_END + 0x1A, // Size: 5, Flags: UF_FLAG_PUBLIC
        UNIT_FIELD_POWER2,
        UNIT_FIELD_POWER3,
        UNIT_FIELD_POWER4,
        UNIT_FIELD_POWER5,
        UNIT_FIELD_MAX_HEALTH                                    = ObjectField.OBJECT_END + 0x1F, // Size: 1, Flags: UF_FLAG_PUBLIC
        UNIT_FIELD_MAX_POWER                                     = ObjectField.OBJECT_END + 0x20, // Size: 5, Flags: UF_FLAG_PUBLIC
        UNIT_FIELD_MAX_POWER2,
        UNIT_FIELD_MAX_POWER3,
        UNIT_FIELD_MAX_POWER4,
        UNIT_FIELD_MAX_POWER5,
        UNIT_FIELD_POWER_REGEN_FLAT_MODIFIER                     = ObjectField.OBJECT_END + 0x25, // Size: 5, Flags: UF_FLAG_PRIVATE, UF_FLAG_OWNER, UF_FLAG_UNIT_ALL
        UNIT_FIELD_POWER_REGEN_FLAT_MODIFIER2,
        UNIT_FIELD_POWER_REGEN_FLAT_MODIFIER3,
        UNIT_FIELD_POWER_REGEN_FLAT_MODIFIER4,
        UNIT_FIELD_POWER_REGEN_FLAT_MODIFIER5,
        UNIT_FIELD_POWER_REGEN_INTERRUPTED_FLAT_MODIFIER         = ObjectField.OBJECT_END + 0x2A, // Size: 5, Flags: UF_FLAG_PRIVATE, UF_FLAG_OWNER, UF_FLAG_UNIT_ALL
        UNIT_FIELD_POWER_REGEN_INTERRUPTED_FLAT_MODIFIER2,
        UNIT_FIELD_POWER_REGEN_INTERRUPTED_FLAT_MODIFIER3,
        UNIT_FIELD_POWER_REGEN_INTERRUPTED_FLAT_MODIFIER4,
        UNIT_FIELD_POWER_REGEN_INTERRUPTED_FLAT_MODIFIER5,
        UNIT_FIELD_LEVEL                                         = ObjectField.OBJECT_END + 0x2F, // Size: 1, Flags: UF_FLAG_PUBLIC
        UNIT_FIELD_EFFECTIVE_LEVEL                               = ObjectField.OBJECT_END + 0x30, // Size: 1, Flags: UF_FLAG_PUBLIC
        UNIT_FIELD_FACTION_TEMPLATE                              = ObjectField.OBJECT_END + 0x31, // Size: 1, Flags: UF_FLAG_PUBLIC
        UNIT_FIELD_VIRTUAL_ITEM_ID                               = ObjectField.OBJECT_END + 0x32, // Size: 3, Flags: UF_FLAG_PUBLIC
        UNIT_FIELD_VIRTUAL_ITEM_ID2,
        UNIT_FIELD_VIRTUAL_ITEM_ID3,
        UNIT_FIELD_FLAGS                                         = ObjectField.OBJECT_END + 0x35, // Size: 1, Flags: UF_FLAG_PUBLIC
        UNIT_FIELD_FLAGS2                                        = ObjectField.OBJECT_END + 0x36, // Size: 1, Flags: UF_FLAG_PUBLIC
        UNIT_FIELD_AURA_STATE                                    = ObjectField.OBJECT_END + 0x37, // Size: 1, Flags: UF_FLAG_PUBLIC
        UNIT_FIELD_ATTACK_ROUND_BASE_TIME                        = ObjectField.OBJECT_END + 0x38, // Size: 2, Flags: UF_FLAG_PUBLIC
        UNIT_FIELD_ATTACK_ROUND_BASE_TIME2,
        UNIT_FIELD_RANGED_ATTACK_ROUND_BASE_TIME                 = ObjectField.OBJECT_END + 0x3A, // Size: 1, Flags: UF_FLAG_PRIVATE
        UNIT_FIELD_BOUNDING_RADIUS                               = ObjectField.OBJECT_END + 0x3B, // Size: 1, Flags: UF_FLAG_PUBLIC
        UNIT_FIELD_COMBAT_REACH                                  = ObjectField.OBJECT_END + 0x3C, // Size: 1, Flags: UF_FLAG_PUBLIC
        UNIT_FIELD_DISPLAY_ID                                    = ObjectField.OBJECT_END + 0x3D, // Size: 1, Flags: UF_FLAG_VIEWER_DEPENDENT, UF_FLAG_URGENT
        UNIT_FIELD_NATIVE_DISPLAY_ID                             = ObjectField.OBJECT_END + 0x3E, // Size: 1, Flags: UF_FLAG_PUBLIC, UF_FLAG_URGENT
        UNIT_FIELD_MOUNT_DISPLAY_ID                              = ObjectField.OBJECT_END + 0x3F, // Size: 1, Flags: UF_FLAG_PUBLIC, UF_FLAG_URGENT
        UNIT_FIELD_MIN_DAMAGE                                    = ObjectField.OBJECT_END + 0x40, // Size: 1, Flags: UF_FLAG_PRIVATE, UF_FLAG_OWNER, UF_FLAG_EMPATH
        UNIT_FIELD_MAX_DAMAGE                                    = ObjectField.OBJECT_END + 0x41, // Size: 1, Flags: UF_FLAG_PRIVATE, UF_FLAG_OWNER, UF_FLAG_EMPATH
        UNIT_FIELD_MIN_OFF_HAND_DAMAGE                           = ObjectField.OBJECT_END + 0x42, // Size: 1, Flags: UF_FLAG_PRIVATE, UF_FLAG_OWNER, UF_FLAG_EMPATH
        UNIT_FIELD_MAX_OFF_HAND_DAMAGE                           = ObjectField.OBJECT_END + 0x43, // Size: 1, Flags: UF_FLAG_PRIVATE, UF_FLAG_OWNER, UF_FLAG_EMPATH
        UNIT_FIELD_ANIM_TIER                                     = ObjectField.OBJECT_END + 0x44, // Size: 1, Flags: UF_FLAG_PUBLIC
        UNIT_FIELD_PET_NUMBER                                    = ObjectField.OBJECT_END + 0x45, // Size: 1, Flags: UF_FLAG_PUBLIC
        UNIT_FIELD_PET_NAME_TIMESTAMP                            = ObjectField.OBJECT_END + 0x46, // Size: 1, Flags: UF_FLAG_PUBLIC
        UNIT_FIELD_PET_EXPERIENCE                                = ObjectField.OBJECT_END + 0x47, // Size: 1, Flags: UF_FLAG_OWNER
        UNIT_FIELD_PET_NEXT_LEVEL_EXPERIENCE                     = ObjectField.OBJECT_END + 0x48, // Size: 1, Flags: UF_FLAG_OWNER
        UNIT_FIELD_MOD_CASTING_SPEED                             = ObjectField.OBJECT_END + 0x49, // Size: 1, Flags: UF_FLAG_PUBLIC
        UNIT_FIELD_MOD_SPELL_HASTE                               = ObjectField.OBJECT_END + 0x4A, // Size: 1, Flags: UF_FLAG_PUBLIC
        UNIT_FIELD_MOD_HASTE                                     = ObjectField.OBJECT_END + 0x4B, // Size: 1, Flags: UF_FLAG_PUBLIC
        UNIT_FIELD_MOD_RANGED_HASTE                              = ObjectField.OBJECT_END + 0x4C, // Size: 1, Flags: UF_FLAG_PUBLIC
        UNIT_FIELD_MOD_HASTE_REGEN                               = ObjectField.OBJECT_END + 0x4D, // Size: 1, Flags: UF_FLAG_PUBLIC
        UNIT_FIELD_CREATED_BY_SPELL                              = ObjectField.OBJECT_END + 0x4E, // Size: 1, Flags: UF_FLAG_PUBLIC
        UNIT_FIELD_NPC_FLAGS                                     = ObjectField.OBJECT_END + 0x4F, // Size: 1, Flags: UF_FLAG_PUBLIC, UF_FLAG_VIEWER_DEPENDENT
        UNIT_FIELD_NPC_EMOTESTATE                                = ObjectField.OBJECT_END + 0x50, // Size: 2, Flags: UF_FLAG_PUBLIC
        UNIT_FIELD_NPC_EMOTESTATE2,
        UNIT_FIELD_STATS                                         = ObjectField.OBJECT_END + 0x52, // Size: 5, Flags: UF_FLAG_PRIVATE, UF_FLAG_OWNER
        UNIT_FIELD_STATS2,
        UNIT_FIELD_STATS3,
        UNIT_FIELD_STATS4,
        UNIT_FIELD_STATS5,
        UNIT_FIELD_STAT_POS_BUFF                                 = ObjectField.OBJECT_END + 0x57, // Size: 5, Flags: UF_FLAG_PRIVATE, UF_FLAG_OWNER
        UNIT_FIELD_STAT_POS_BUFF2,
        UNIT_FIELD_STAT_POS_BUFF3,
        UNIT_FIELD_STAT_POS_BUFF4,
        UNIT_FIELD_STAT_POS_BUFF5,
        UNIT_FIELD_STAT_NEG_BUFF                                 = ObjectField.OBJECT_END + 0x5C, // Size: 5, Flags: UF_FLAG_PRIVATE, UF_FLAG_OWNER
        UNIT_FIELD_STAT_NEG_BUFF2,
        UNIT_FIELD_STAT_NEG_BUFF3,
        UNIT_FIELD_STAT_NEG_BUFF4,
        UNIT_FIELD_STAT_NEG_BUFF5,
        UNIT_FIELD_RESISTANCES                                   = ObjectField.OBJECT_END + 0x61, // Size: 7, Flags: UF_FLAG_PRIVATE, UF_FLAG_OWNER, UF_FLAG_EMPATH
        UNIT_FIELD_RESISTANCES2,
        UNIT_FIELD_RESISTANCES3,
        UNIT_FIELD_RESISTANCES4,
        UNIT_FIELD_RESISTANCES5,
        UNIT_FIELD_RESISTANCES6,
        UNIT_FIELD_RESISTANCES7,
        UNIT_FIELD_RESISTANCE_BUFF_MODS_POSITIVE                 = ObjectField.OBJECT_END + 0x68, // Size: 7, Flags: UF_FLAG_PRIVATE, UF_FLAG_OWNER
        UNIT_FIELD_RESISTANCE_BUFF_MODS_POSITIVE2,
        UNIT_FIELD_RESISTANCE_BUFF_MODS_POSITIVE3,
        UNIT_FIELD_RESISTANCE_BUFF_MODS_POSITIVE4,
        UNIT_FIELD_RESISTANCE_BUFF_MODS_POSITIVE5,
        UNIT_FIELD_RESISTANCE_BUFF_MODS_POSITIVE6,
        UNIT_FIELD_RESISTANCE_BUFF_MODS_POSITIVE7,
        UNIT_FIELD_RESISTANCE_BUFF_MODS_NEGATIVE                 = ObjectField.OBJECT_END + 0x6F, // Size: 7, Flags: UF_FLAG_PRIVATE, UF_FLAG_OWNER
        UNIT_FIELD_RESISTANCE_BUFF_MODS_NEGATIVE2,
        UNIT_FIELD_RESISTANCE_BUFF_MODS_NEGATIVE3,
        UNIT_FIELD_RESISTANCE_BUFF_MODS_NEGATIVE4,
        UNIT_FIELD_RESISTANCE_BUFF_MODS_NEGATIVE5,
        UNIT_FIELD_RESISTANCE_BUFF_MODS_NEGATIVE6,
        UNIT_FIELD_RESISTANCE_BUFF_MODS_NEGATIVE7,
        UNIT_FIELD_BASE_MANA                                     = ObjectField.OBJECT_END + 0x76, // Size: 1, Flags: UF_FLAG_PUBLIC
        UNIT_FIELD_BASE_HEALTH                                   = ObjectField.OBJECT_END + 0x77, // Size: 1, Flags: UF_FLAG_PRIVATE, UF_FLAG_OWNER
        UNIT_FIELD_SHAPESHIFT_FORM                               = ObjectField.OBJECT_END + 0x78, // Size: 1, Flags: UF_FLAG_PUBLIC
        UNIT_FIELD_ATTACK_POWER                                  = ObjectField.OBJECT_END + 0x79, // Size: 1, Flags: UF_FLAG_PRIVATE, UF_FLAG_OWNER
        UNIT_FIELD_ATTACK_POWER_MOD_POS                          = ObjectField.OBJECT_END + 0x7A, // Size: 1, Flags: UF_FLAG_PRIVATE, UF_FLAG_OWNER
        UNIT_FIELD_ATTACK_POWER_MOD_NEG                          = ObjectField.OBJECT_END + 0x7B, // Size: 1, Flags: UF_FLAG_PRIVATE, UF_FLAG_OWNER
        UNIT_FIELD_ATTACK_POWER_MULTIPLIER                       = ObjectField.OBJECT_END + 0x7C, // Size: 1, Flags: UF_FLAG_PRIVATE, UF_FLAG_OWNER
        UNIT_FIELD_RANGED_ATTACK_POWER                           = ObjectField.OBJECT_END + 0x7D, // Size: 1, Flags: UF_FLAG_PRIVATE, UF_FLAG_OWNER
        UNIT_FIELD_RANGED_ATTACK_POWER_MOD_POS                   = ObjectField.OBJECT_END + 0x7E, // Size: 1, Flags: UF_FLAG_PRIVATE, UF_FLAG_OWNER
        UNIT_FIELD_RANGED_ATTACK_POWER_MOD_NEG                   = ObjectField.OBJECT_END + 0x7F, // Size: 1, Flags: UF_FLAG_PRIVATE, UF_FLAG_OWNER
        UNIT_FIELD_RANGED_ATTACK_POWER_MULTIPLIER                = ObjectField.OBJECT_END + 0x80, // Size: 1, Flags: UF_FLAG_PRIVATE, UF_FLAG_OWNER
        UNIT_FIELD_MIN_RANGED_DAMAGE                             = ObjectField.OBJECT_END + 0x81, // Size: 1, Flags: UF_FLAG_PRIVATE, UF_FLAG_OWNER
        UNIT_FIELD_MAX_RANGED_DAMAGE                             = ObjectField.OBJECT_END + 0x82, // Size: 1, Flags: UF_FLAG_PRIVATE, UF_FLAG_OWNER
        UNIT_FIELD_POWER_COST_MODIFIER                           = ObjectField.OBJECT_END + 0x83, // Size: 7, Flags: UF_FLAG_PRIVATE, UF_FLAG_OWNER
        UNIT_FIELD_POWER_COST_MODIFIER2,
        UNIT_FIELD_POWER_COST_MODIFIER3,
        UNIT_FIELD_POWER_COST_MODIFIER4,
        UNIT_FIELD_POWER_COST_MODIFIER5,
        UNIT_FIELD_POWER_COST_MODIFIER6,
        UNIT_FIELD_POWER_COST_MODIFIER7,
        UNIT_FIELD_POWER_COST_MULTIPLIER                         = ObjectField.OBJECT_END + 0x8A, // Size: 7, Flags: UF_FLAG_PRIVATE, UF_FLAG_OWNER
        UNIT_FIELD_POWER_COST_MULTIPLIER2,
        UNIT_FIELD_POWER_COST_MULTIPLIER3,
        UNIT_FIELD_POWER_COST_MULTIPLIER4,
        UNIT_FIELD_POWER_COST_MULTIPLIER5,
        UNIT_FIELD_POWER_COST_MULTIPLIER6,
        UNIT_FIELD_POWER_COST_MULTIPLIER7,
        UNIT_FIELD_MAX_HEALTH_MODIFIER                           = ObjectField.OBJECT_END + 0x91, // Size: 1, Flags: UF_FLAG_PRIVATE, UF_FLAG_OWNER
        UNIT_FIELD_HOVER_HEIGHT                                  = ObjectField.OBJECT_END + 0x92, // Size: 1, Flags: UF_FLAG_PUBLIC
        UNIT_FIELD_MIN_ITEM_LEVEL                                = ObjectField.OBJECT_END + 0x93, // Size: 1, Flags: UF_FLAG_PUBLIC
        UNIT_FIELD_MAX_ITEM_LEVEL                                = ObjectField.OBJECT_END + 0x94, // Size: 1, Flags: UF_FLAG_PUBLIC
        UNIT_FIELD_WILD_BATTLE_PET_LEVEL                         = ObjectField.OBJECT_END + 0x95, // Size: 1, Flags: UF_FLAG_PUBLIC
        UNIT_FIELD_BATTLE_PET_COMPANION_NAME_TIMESTAMP           = ObjectField.OBJECT_END + 0x96, // Size: 1, Flags: UF_FLAG_PUBLIC
        UNIT_FIELD_INTERACT_SPELL_ID                             = ObjectField.OBJECT_END + 0x97, // Size: 1, Flags: UF_FLAG_PUBLIC
        UNIT_END                                                 = ObjectField.OBJECT_END + 0x98
    }

    public enum PlayerField
    {
        PLAYER_AMMO_ID,
        PLAYER_BLOCK_PERCENTAGE,
        PLAYER_BYTES,
        PLAYER_BYTES_2,
        PLAYER_BYTES_3,
        PLAYER_CHARACTER_POINTS,
        PLAYER_CHARACTER_POINTS1,
        PLAYER_CHARACTER_POINTS2,
        PLAYER_CHOSEN_TITLE,
        PLAYER_CRIT_PERCENTAGE,
        PLAYER_DODGE_PERCENTAGE,
        PLAYER_DUEL_ARBITER,
        PLAYER_DUEL_TEAM,
        PLAYER_END,
        PLAYER_EXPERTISE,
        PLAYER_EXPLORED_ZONES_1,
        PLAYER_FAKE_INEBRIATION,
        PLAYER_FARSIGHT,
        PLAYER_FIELD_ARENA_CURRENCY,
        PLAYER_FIELD_ARENA_TEAM_INFO_1_1,
        PLAYER_FIELD_BANKBAG_SLOT_1,
        PLAYER_FIELD_BANK_SLOT_1,
        PLAYER_FIELD_BATTLEGROUND_RATING,
        PLAYER_FIELD_BUYBACK_PRICE_1,
        PLAYER_FIELD_BUYBACK_PRICE_10,
        PLAYER_FIELD_BUYBACK_PRICE_11,
        PLAYER_FIELD_BUYBACK_PRICE_12,
        PLAYER_FIELD_BUYBACK_PRICE_2,
        PLAYER_FIELD_BUYBACK_PRICE_3,
        PLAYER_FIELD_BUYBACK_PRICE_4,
        PLAYER_FIELD_BUYBACK_PRICE_5,
        PLAYER_FIELD_BUYBACK_PRICE_6,
        PLAYER_FIELD_BUYBACK_PRICE_7,
        PLAYER_FIELD_BUYBACK_PRICE_8,
        PLAYER_FIELD_BUYBACK_PRICE_9,
        PLAYER_FIELD_BUYBACK_TIMESTAMP_1,
        PLAYER_FIELD_BUYBACK_TIMESTAMP_10,
        PLAYER_FIELD_BUYBACK_TIMESTAMP_11,
        PLAYER_FIELD_BUYBACK_TIMESTAMP_12,
        PLAYER_FIELD_BUYBACK_TIMESTAMP_2,
        PLAYER_FIELD_BUYBACK_TIMESTAMP_3,
        PLAYER_FIELD_BUYBACK_TIMESTAMP_4,
        PLAYER_FIELD_BUYBACK_TIMESTAMP_5,
        PLAYER_FIELD_BUYBACK_TIMESTAMP_6,
        PLAYER_FIELD_BUYBACK_TIMESTAMP_7,
        PLAYER_FIELD_BUYBACK_TIMESTAMP_8,
        PLAYER_FIELD_BUYBACK_TIMESTAMP_9,
        PLAYER_FIELD_BYTES,
        PLAYER_FIELD_BYTES2,
        PLAYER_FIELD_COINAGE,
        PLAYER_FIELD_COMBAT_RATING_1,
        PLAYER_FIELD_CURRENCYTOKEN_SLOT_1,
        PLAYER_FIELD_DAILY_QUESTS_1,
        PLAYER_FIELD_GLYPHS_1,
        PLAYER_FIELD_GLYPHS_2,
        PLAYER_FIELD_GLYPHS_3,
        PLAYER_FIELD_GLYPHS_4,
        PLAYER_FIELD_GLYPHS_5,
        PLAYER_FIELD_GLYPHS_6,
        PLAYER_FIELD_GLYPH_SLOTS_1,
        PLAYER_FIELD_GLYPH_SLOTS_2,
        PLAYER_FIELD_GLYPH_SLOTS_3,
        PLAYER_FIELD_GLYPH_SLOTS_4,
        PLAYER_FIELD_GLYPH_SLOTS_5,
        PLAYER_FIELD_GLYPH_SLOTS_6,
        PLAYER_FIELD_HOME_REALM_TIME_OFFSET,
        PLAYER_FIELD_HONOR_CURRENCY,
        PLAYER_FIELD_INV_SLOT_FIXME1,
        PLAYER_FIELD_INV_SLOT_FIXME10,
        PLAYER_FIELD_INV_SLOT_FIXME11,
        PLAYER_FIELD_INV_SLOT_FIXME12,
        PLAYER_FIELD_INV_SLOT_FIXME13,
        PLAYER_FIELD_INV_SLOT_FIXME14,
        PLAYER_FIELD_INV_SLOT_FIXME15,
        PLAYER_FIELD_INV_SLOT_FIXME16,
        PLAYER_FIELD_INV_SLOT_FIXME17,
        PLAYER_FIELD_INV_SLOT_FIXME18,
        PLAYER_FIELD_INV_SLOT_FIXME19,
        PLAYER_FIELD_INV_SLOT_FIXME2,
        PLAYER_FIELD_INV_SLOT_FIXME20,
        PLAYER_FIELD_INV_SLOT_FIXME21,
        PLAYER_FIELD_INV_SLOT_FIXME22,
        PLAYER_FIELD_INV_SLOT_FIXME3,
        PLAYER_FIELD_INV_SLOT_FIXME4,
        PLAYER_FIELD_INV_SLOT_FIXME5,
        PLAYER_FIELD_INV_SLOT_FIXME6,
        PLAYER_FIELD_INV_SLOT_FIXME7,
        PLAYER_FIELD_INV_SLOT_FIXME8,
        PLAYER_FIELD_INV_SLOT_FIXME9,
        PLAYER_FIELD_INV_SLOT_HEAD,
        PLAYER_FIELD_KEYRING_SLOT_1,
        PLAYER_FIELD_KILLS,
        PLAYER_FIELD_KNOWN_CURRENCIES,
        PLAYER_FIELD_KNOWN_TITLES,
        PLAYER_FIELD_KNOWN_TITLES1,
        PLAYER_FIELD_KNOWN_TITLES2,
        PLAYER_FIELD_LIFETIME_HONORABLE_KILLS,
        PLAYER_FIELD_MAX_LEVEL,
        PLAYER_FIELD_MOD_DAMAGE_DONE_NEG,
        PLAYER_FIELD_MOD_DAMAGE_DONE_PCT,
        PLAYER_FIELD_MOD_DAMAGE_DONE_PCT1,
        PLAYER_FIELD_MOD_DAMAGE_DONE_PCT2,
        PLAYER_FIELD_MOD_DAMAGE_DONE_PCT3,
        PLAYER_FIELD_MOD_DAMAGE_DONE_PCT4,
        PLAYER_FIELD_MOD_DAMAGE_DONE_PCT5,
        PLAYER_FIELD_MOD_DAMAGE_DONE_PCT6,
        PLAYER_FIELD_MOD_DAMAGE_DONE_PCT7,
        PLAYER_FIELD_MOD_DAMAGE_DONE_POS,
        PLAYER_FIELD_MOD_HASTE,
        PLAYER_FIELD_MOD_HASTE_REGEN,
        PLAYER_FIELD_MOD_HEALING_DONE_PCT,
        PLAYER_FIELD_MOD_HEALING_DONE_POS,
        PLAYER_FIELD_MOD_HEALING_PCT,
        PLAYER_FIELD_MOD_PET_HASTE,
        PLAYER_FIELD_MOD_RANGED_HASTE,
        PLAYER_FIELD_MOD_SPELL_POWER_PCT,
        PLAYER_FIELD_MOD_TARGET_PHYSICAL_RESISTANCE,
        PLAYER_FIELD_MOD_TARGET_RESISTANCE,
        PLAYER_FIELD_PACK_SLOT_1,
        PLAYER_FIELD_PADDING,
        PLAYER_FIELD_PAD_0,
        PLAYER_FIELD_PVP_MEDALS,
        PLAYER_FIELD_RESEARCHING_1,
        PLAYER_FIELD_RESERACH_SITE_1,
        PLAYER_FIELD_TODAY_CONTRIBUTION,
        PLAYER_FIELD_UI_HIT_MODIFIER,
        PLAYER_FIELD_UI_SPELL_HIT_MODIFIER,
        PLAYER_FIELD_VENDORBUYBACK_SLOT_1,
        PLAYER_FIELD_WATCHED_FACTION_INDEX,
        PLAYER_FIELD_WEAPON_DMG_MULTIPLIERS,
        PLAYER_FIELD_YESTERDAY_CONTRIBUTION,
        PLAYER_FLAGS,
        PLAYER_GLYPHS_ENABLED,
        PLAYER_GUILDDELETE_DATE,
        PLAYER_GUILDID,
        PLAYER_GUILDLEVEL,
        PLAYER_GUILDRANK,
        PLAYER_GUILD_TIMESTAMP,
        PLAYER_MASTERY,
        PLAYER_NEXT_LEVEL_XP,
        PLAYER_NO_REAGENT_COST_1,
        PLAYER_OFFHAND_CRIT_PERCENTAGE,
        PLAYER_OFFHAND_EXPERTISE,
        PLAYER_PARRY_PERCENTAGE,
        PLAYER_PET_SPELL_POWER,
        PLAYER_PROFESSION_SKILL_LINE_1,
        PLAYER_QUEST_LOG_10_1,
        PLAYER_QUEST_LOG_10_2,
        PLAYER_QUEST_LOG_10_3,
        PLAYER_QUEST_LOG_10_5,
        PLAYER_QUEST_LOG_11_1,
        PLAYER_QUEST_LOG_11_2,
        PLAYER_QUEST_LOG_11_3,
        PLAYER_QUEST_LOG_11_5,
        PLAYER_QUEST_LOG_12_1,
        PLAYER_QUEST_LOG_12_2,
        PLAYER_QUEST_LOG_12_3,
        PLAYER_QUEST_LOG_12_5,
        PLAYER_QUEST_LOG_13_1,
        PLAYER_QUEST_LOG_13_2,
        PLAYER_QUEST_LOG_13_3,
        PLAYER_QUEST_LOG_13_5,
        PLAYER_QUEST_LOG_14_1,
        PLAYER_QUEST_LOG_14_2,
        PLAYER_QUEST_LOG_14_3,
        PLAYER_QUEST_LOG_14_5,
        PLAYER_QUEST_LOG_15_1,
        PLAYER_QUEST_LOG_15_2,
        PLAYER_QUEST_LOG_15_3,
        PLAYER_QUEST_LOG_15_5,
        PLAYER_QUEST_LOG_16_1,
        PLAYER_QUEST_LOG_16_2,
        PLAYER_QUEST_LOG_16_3,
        PLAYER_QUEST_LOG_16_5,
        PLAYER_QUEST_LOG_17_1,
        PLAYER_QUEST_LOG_17_2,
        PLAYER_QUEST_LOG_17_3,
        PLAYER_QUEST_LOG_17_5,
        PLAYER_QUEST_LOG_18_1,
        PLAYER_QUEST_LOG_18_2,
        PLAYER_QUEST_LOG_18_3,
        PLAYER_QUEST_LOG_18_5,
        PLAYER_QUEST_LOG_19_1,
        PLAYER_QUEST_LOG_19_2,
        PLAYER_QUEST_LOG_19_3,
        PLAYER_QUEST_LOG_19_5,
        PLAYER_QUEST_LOG_1_1,
        PLAYER_QUEST_LOG_1_2,
        PLAYER_QUEST_LOG_1_3,
        PLAYER_QUEST_LOG_1_4,
        PLAYER_QUEST_LOG_1_5,
        PLAYER_QUEST_LOG_20_1,
        PLAYER_QUEST_LOG_20_2,
        PLAYER_QUEST_LOG_20_3,
        PLAYER_QUEST_LOG_20_5,
        PLAYER_QUEST_LOG_21_1,
        PLAYER_QUEST_LOG_21_2,
        PLAYER_QUEST_LOG_21_3,
        PLAYER_QUEST_LOG_21_5,
        PLAYER_QUEST_LOG_22_1,
        PLAYER_QUEST_LOG_22_2,
        PLAYER_QUEST_LOG_22_3,
        PLAYER_QUEST_LOG_22_5,
        PLAYER_QUEST_LOG_23_1,
        PLAYER_QUEST_LOG_23_2,
        PLAYER_QUEST_LOG_23_3,
        PLAYER_QUEST_LOG_23_5,
        PLAYER_QUEST_LOG_24_1,
        PLAYER_QUEST_LOG_24_2,
        PLAYER_QUEST_LOG_24_3,
        PLAYER_QUEST_LOG_24_5,
        PLAYER_QUEST_LOG_25_1,
        PLAYER_QUEST_LOG_25_2,
        PLAYER_QUEST_LOG_25_3,
        PLAYER_QUEST_LOG_25_5,
        PLAYER_QUEST_LOG_26_1,
        PLAYER_QUEST_LOG_26_2,
        PLAYER_QUEST_LOG_26_3,
        PLAYER_QUEST_LOG_26_5,
        PLAYER_QUEST_LOG_27_1,
        PLAYER_QUEST_LOG_27_2,
        PLAYER_QUEST_LOG_27_3,
        PLAYER_QUEST_LOG_27_5,
        PLAYER_QUEST_LOG_28_1,
        PLAYER_QUEST_LOG_28_2,
        PLAYER_QUEST_LOG_28_3,
        PLAYER_QUEST_LOG_28_5,
        PLAYER_QUEST_LOG_29_1,
        PLAYER_QUEST_LOG_29_2,
        PLAYER_QUEST_LOG_29_3,
        PLAYER_QUEST_LOG_29_5,
        PLAYER_QUEST_LOG_2_1,
        PLAYER_QUEST_LOG_2_2,
        PLAYER_QUEST_LOG_2_3,
        PLAYER_QUEST_LOG_2_5,
        PLAYER_QUEST_LOG_30_1,
        PLAYER_QUEST_LOG_30_2,
        PLAYER_QUEST_LOG_30_3,
        PLAYER_QUEST_LOG_30_5,
        PLAYER_QUEST_LOG_31_1,
        PLAYER_QUEST_LOG_31_2,
        PLAYER_QUEST_LOG_31_3,
        PLAYER_QUEST_LOG_31_5,
        PLAYER_QUEST_LOG_32_1,
        PLAYER_QUEST_LOG_32_2,
        PLAYER_QUEST_LOG_32_3,
        PLAYER_QUEST_LOG_32_5,
        PLAYER_QUEST_LOG_33_1,
        PLAYER_QUEST_LOG_33_2,
        PLAYER_QUEST_LOG_33_3,
        PLAYER_QUEST_LOG_33_5,
        PLAYER_QUEST_LOG_34_1,
        PLAYER_QUEST_LOG_34_2,
        PLAYER_QUEST_LOG_34_3,
        PLAYER_QUEST_LOG_34_5,
        PLAYER_QUEST_LOG_35_1,
        PLAYER_QUEST_LOG_35_2,
        PLAYER_QUEST_LOG_35_3,
        PLAYER_QUEST_LOG_35_5,
        PLAYER_QUEST_LOG_36_1,
        PLAYER_QUEST_LOG_36_2,
        PLAYER_QUEST_LOG_36_3,
        PLAYER_QUEST_LOG_36_5,
        PLAYER_QUEST_LOG_37_1,
        PLAYER_QUEST_LOG_37_2,
        PLAYER_QUEST_LOG_37_3,
        PLAYER_QUEST_LOG_37_5,
        PLAYER_QUEST_LOG_38_1,
        PLAYER_QUEST_LOG_38_2,
        PLAYER_QUEST_LOG_38_3,
        PLAYER_QUEST_LOG_38_5,
        PLAYER_QUEST_LOG_39_1,
        PLAYER_QUEST_LOG_39_2,
        PLAYER_QUEST_LOG_39_3,
        PLAYER_QUEST_LOG_39_5,
        PLAYER_QUEST_LOG_3_1,
        PLAYER_QUEST_LOG_3_2,
        PLAYER_QUEST_LOG_3_3,
        PLAYER_QUEST_LOG_3_5,
        PLAYER_QUEST_LOG_40_1,
        PLAYER_QUEST_LOG_40_2,
        PLAYER_QUEST_LOG_40_3,
        PLAYER_QUEST_LOG_40_5,
        PLAYER_QUEST_LOG_41_1,
        PLAYER_QUEST_LOG_41_2,
        PLAYER_QUEST_LOG_41_3,
        PLAYER_QUEST_LOG_41_5,
        PLAYER_QUEST_LOG_42_1,
        PLAYER_QUEST_LOG_42_2,
        PLAYER_QUEST_LOG_42_3,
        PLAYER_QUEST_LOG_42_5,
        PLAYER_QUEST_LOG_43_1,
        PLAYER_QUEST_LOG_43_2,
        PLAYER_QUEST_LOG_43_3,
        PLAYER_QUEST_LOG_43_5,
        PLAYER_QUEST_LOG_44_1,
        PLAYER_QUEST_LOG_44_2,
        PLAYER_QUEST_LOG_44_3,
        PLAYER_QUEST_LOG_44_5,
        PLAYER_QUEST_LOG_45_1,
        PLAYER_QUEST_LOG_45_2,
        PLAYER_QUEST_LOG_45_3,
        PLAYER_QUEST_LOG_45_5,
        PLAYER_QUEST_LOG_46_1,
        PLAYER_QUEST_LOG_46_2,
        PLAYER_QUEST_LOG_46_3,
        PLAYER_QUEST_LOG_46_5,
        PLAYER_QUEST_LOG_47_1,
        PLAYER_QUEST_LOG_47_2,
        PLAYER_QUEST_LOG_47_3,
        PLAYER_QUEST_LOG_47_5,
        PLAYER_QUEST_LOG_48_1,
        PLAYER_QUEST_LOG_48_2,
        PLAYER_QUEST_LOG_48_3,
        PLAYER_QUEST_LOG_48_5,
        PLAYER_QUEST_LOG_49_1,
        PLAYER_QUEST_LOG_49_2,
        PLAYER_QUEST_LOG_49_3,
        PLAYER_QUEST_LOG_49_5,
        PLAYER_QUEST_LOG_4_1,
        PLAYER_QUEST_LOG_4_2,
        PLAYER_QUEST_LOG_4_3,
        PLAYER_QUEST_LOG_4_5,
        PLAYER_QUEST_LOG_50_1,
        PLAYER_QUEST_LOG_50_2,
        PLAYER_QUEST_LOG_50_3,
        PLAYER_QUEST_LOG_50_5,
        PLAYER_QUEST_LOG_5_1,
        PLAYER_QUEST_LOG_5_2,
        PLAYER_QUEST_LOG_5_3,
        PLAYER_QUEST_LOG_5_5,
        PLAYER_QUEST_LOG_6_1,
        PLAYER_QUEST_LOG_6_2,
        PLAYER_QUEST_LOG_6_3,
        PLAYER_QUEST_LOG_6_5,
        PLAYER_QUEST_LOG_7_1,
        PLAYER_QUEST_LOG_7_2,
        PLAYER_QUEST_LOG_7_3,
        PLAYER_QUEST_LOG_7_5,
        PLAYER_QUEST_LOG_8_1,
        PLAYER_QUEST_LOG_8_2,
        PLAYER_QUEST_LOG_8_3,
        PLAYER_QUEST_LOG_8_5,
        PLAYER_QUEST_LOG_9_1,
        PLAYER_QUEST_LOG_9_2,
        PLAYER_QUEST_LOG_9_3,
        PLAYER_QUEST_LOG_9_5,
        PLAYER_RANGED_CRIT_PERCENTAGE,
        PLAYER_REST_STATE_EXPERIENCE,
        PLAYER_RUNE_REGEN_1,
        PLAYER_RUNE_REGEN_2,
        PLAYER_RUNE_REGEN_3,
        PLAYER_RUNE_REGEN_4,
        PLAYER_SELF_RES_SPELL,
        PLAYER_SHIELD_BLOCK,
        PLAYER_SHIELD_BLOCK_CRIT_PERCENTAGE,
        PLAYER_SKILL_INFO_1_1,
        PLAYER_SPELL_CRIT_PERCENTAGE1,
        PLAYER_SPELL_CRIT_PERCENTAGE2,
        PLAYER_SPELL_CRIT_PERCENTAGE3,
        PLAYER_SPELL_CRIT_PERCENTAGE4,
        PLAYER_SPELL_CRIT_PERCENTAGE5,
        PLAYER_SPELL_CRIT_PERCENTAGE6,
        PLAYER_SPELL_CRIT_PERCENTAGE7,
        PLAYER_TRACK_CREATURES,
        PLAYER_TRACK_RESOURCES,
        PLAYER_VISIBLE_ITEM_10_ENCHANTMENT,
        PLAYER_VISIBLE_ITEM_10_ENTRYID,
        PLAYER_VISIBLE_ITEM_11_ENCHANTMENT,
        PLAYER_VISIBLE_ITEM_11_ENTRYID,
        PLAYER_VISIBLE_ITEM_12_ENCHANTMENT,
        PLAYER_VISIBLE_ITEM_12_ENTRYID,
        PLAYER_VISIBLE_ITEM_13_ENCHANTMENT,
        PLAYER_VISIBLE_ITEM_13_ENTRYID,
        PLAYER_VISIBLE_ITEM_14_ENCHANTMENT,
        PLAYER_VISIBLE_ITEM_14_ENTRYID,
        PLAYER_VISIBLE_ITEM_15_ENCHANTMENT,
        PLAYER_VISIBLE_ITEM_15_ENTRYID,
        PLAYER_VISIBLE_ITEM_16_ENCHANTMENT,
        PLAYER_VISIBLE_ITEM_16_ENTRYID,
        PLAYER_VISIBLE_ITEM_17_ENCHANTMENT,
        PLAYER_VISIBLE_ITEM_17_ENTRYID,
        PLAYER_VISIBLE_ITEM_18_ENCHANTMENT,
        PLAYER_VISIBLE_ITEM_18_ENTRYID,
        PLAYER_VISIBLE_ITEM_19_ENCHANTMENT,
        PLAYER_VISIBLE_ITEM_19_ENTRYID,
        PLAYER_VISIBLE_ITEM_1_ENCHANTMENT,
        PLAYER_VISIBLE_ITEM_1_ENTRYID,
        PLAYER_VISIBLE_ITEM_2_ENCHANTMENT,
        PLAYER_VISIBLE_ITEM_2_ENTRYID,
        PLAYER_VISIBLE_ITEM_3_ENCHANTMENT,
        PLAYER_VISIBLE_ITEM_3_ENTRYID,
        PLAYER_VISIBLE_ITEM_4_ENCHANTMENT,
        PLAYER_VISIBLE_ITEM_4_ENTRYID,
        PLAYER_VISIBLE_ITEM_5_ENCHANTMENT,
        PLAYER_VISIBLE_ITEM_5_ENTRYID,
        PLAYER_VISIBLE_ITEM_6_ENCHANTMENT,
        PLAYER_VISIBLE_ITEM_6_ENTRYID,
        PLAYER_VISIBLE_ITEM_7_ENCHANTMENT,
        PLAYER_VISIBLE_ITEM_7_ENTRYID,
        PLAYER_VISIBLE_ITEM_8_ENCHANTMENT,
        PLAYER_VISIBLE_ITEM_8_ENTRYID,
        PLAYER_VISIBLE_ITEM_9_ENCHANTMENT,
        PLAYER_VISIBLE_ITEM_9_ENTRYID,
        PLAYER_XP,
        PLAYER__FIELD_KNOWN_TITLES,
        PLAYER__FIELD_KNOWN_TITLES1,
        PLAYER__FIELD_KNOWN_TITLES2,
    }

    public enum GameObjectField
    {
        GAMEOBJECT_FIELD_CREATED_BY                              = ObjectField.OBJECT_END + 0x0, // Size: 2, Flags: UF_FLAG_PUBLIC
        GAMEOBJECT_FIELD_CREATED_BY2,
        GAMEOBJECT_FIELD_DISPLAY_ID                              = ObjectField.OBJECT_END + 0x2, // Size: 1, Flags: UF_FLAG_PUBLIC
        GAMEOBJECT_FIELD_FLAGS                                   = ObjectField.OBJECT_END + 0x3, // Size: 1, Flags: UF_FLAG_PUBLIC, UF_FLAG_URGENT
        GAMEOBJECT_FIELD_PARENT_ROTATION                         = ObjectField.OBJECT_END + 0x4, // Size: 4, Flags: UF_FLAG_PUBLIC
        GAMEOBJECT_FIELD_PARENT_ROTATION2,
        GAMEOBJECT_FIELD_PARENT_ROTATION3,
        GAMEOBJECT_FIELD_PARENT_ROTATION4,
        GAMEOBJECT_FIELD_FACTION_TEMPLATE                        = ObjectField.OBJECT_END + 0x8, // Size: 1, Flags: UF_FLAG_PUBLIC
        GAMEOBJECT_FIELD_LEVEL                                   = ObjectField.OBJECT_END + 0x9, // Size: 1, Flags: UF_FLAG_PUBLIC
        GAMEOBJECT_FIELD_PERCENT_HEALTH                          = ObjectField.OBJECT_END + 0xA, // Size: 1, Flags: UF_FLAG_PUBLIC, UF_FLAG_URGENT
        GAMEOBJECT_FIELD_STATE_SPELL_VISUAL_ID                   = ObjectField.OBJECT_END + 0xB, // Size: 1, Flags: UF_FLAG_PUBLIC, UF_FLAG_URGENT
        GAMEOBJECT_END                                           = ObjectField.OBJECT_END + 0xC
    }

    public enum DynamicObjectField
    {
        DYNAMICOBJECT_FIELD_CASTER                               = ObjectField.OBJECT_END + 0x0, // Size: 2, Flags: UF_FLAGý_PUBLIC
        DYNAMICOBJECT_FIELD_CASTER2,
        DYNAMICOBJECT_FIELD_TYPE_AND_VISUAL_ID                   = ObjectField.OBJECT_END + 0x2, // Size: 1, Flags: UF_FLAG_VIEWER_DEPENDENT
        DYNAMICOBJECT_FIELD_SPELL_ID                             = ObjectField.OBJECT_END + 0x3, // Size: 1, Flags: UF_FLAG_PUBLIC
        DYNAMICOBJECT_FIELD_RADIUS                               = ObjectField.OBJECT_END + 0x4, // Size: 1, Flags: UF_FLAG_PUBLIC
        DYNAMICOBJECT_FIELD_CAST_TIME                            = ObjectField.OBJECT_END + 0x5, // Size: 1, Flags: UF_FLAG_PUBLIC
        DYNAMICOBJECT_END                                        = ObjectField.OBJECT_END + 0x6
    }

    public enum CorpseField
    {
        CORPSE_FIELD_OWNER                                       = ObjectField.OBJECT_END + 0x00, // Size: 2, Flags: UF_FLAG_PUBLIC
        CORPSE_FIELD_OWNER2,
        CORPSE_FIELD_PARTY_GUID                                  = ObjectField.OBJECT_END + 0x02, // Size: 2, Flags: UF_FLAG_PUBLIC
        CORPSE_FIELD_PARTY_GUID2,
        CORPSE_FIELD_DISPLAY_ID                                  = ObjectField.OBJECT_END + 0x04, // Size: 1, Flags: UF_FLAG_PUBLIC
        CORPSE_FIELD_ITEM                                        = ObjectField.OBJECT_END + 0x05, // Size: 19, Flags: UF_FLAG_PUBLIC
        CORPSE_FIELD_ITEM2,
        CORPSE_FIELD_ITEM3,
        CORPSE_FIELD_ITEM4,
        CORPSE_FIELD_ITEM5,
        CORPSE_FIELD_ITEM6,
        CORPSE_FIELD_ITEM7,
        CORPSE_FIELD_ITEM8,
        CORPSE_FIELD_ITEM9,
        CORPSE_FIELD_ITEM10,
        CORPSE_FIELD_ITEM11,
        CORPSE_FIELD_ITEM12,
        CORPSE_FIELD_ITEM13,
        CORPSE_FIELD_ITEM14,
        CORPSE_FIELD_ITEM15,
        CORPSE_FIELD_ITEM16,
        CORPSE_FIELD_ITEM17,
        CORPSE_FIELD_ITEM18,
        CORPSE_FIELD_ITEM19,
        CORPSE_FIELD_SKIN_ID                                     = ObjectField.OBJECT_END + 0x18, // Size: 1, Flags: UF_FLAG_PUBLIC
        CORPSE_FIELD_FACIAL_HAIR_STYLE_ID                        = ObjectField.OBJECT_END + 0x19, // Size: 1, Flags: UF_FLAG_PUBLIC
        CORPSE_FIELD_FLAGS                                       = ObjectField.OBJECT_END + 0x1A, // Size: 1, Flags: UF_FLAG_PUBLIC
        CORPSE_FIELD_DYNAMIC_FLAGS                               = ObjectField.OBJECT_END + 0x1B, // Size: 1, Flags: UF_FLAG_VIEWER_DEPENDENT
        CORPSE_END                                               = ObjectField.OBJECT_END + 0x1C
    }

    public enum AreaTriggerField
    {
        AREATRIGGER_FIELD_CASTER                                 = ObjectField.OBJECT_END + 0x0, // Size: 2, Flags: UF_FLAG_PUBLIC
        AREATRIGGER_FIELD_CASTER2,
        AREATRIGGER_FIELD_DURATION                               = ObjectField.OBJECT_END + 0x2, // Size: 1, Flags: UF_FLAG_PUBLIC
        AREATRIGGER_FIELD_SPELL_ID                               = ObjectField.OBJECT_END + 0x3, // Size: 1, Flags: UF_FLAG_PUBLIC
        AREATRIGGER_FIELD_SPELL_VISUAL_ID                        = ObjectField.OBJECT_END + 0x4, // Size: 1, Flags: UF_FLAG_VIEWER_DEPENDENT
        AREATRIGGER_FIELD_EXPLICIT_SCALE                         = ObjectField.OBJECT_END + 0x5, // Size: 1, Flags: UF_FLAG_PUBLIC, UF_FLAG_URGENT
        AREATRIGGER_END                                          = ObjectField.OBJECT_END + 0x6
    }

    public enum SceneObjectField
    {
        SCENEOBJECT_FIELD_SCRIPT_PACKAGE_ID                      = ObjectField.OBJECT_END + 0x0, // Size: 1, Flags: UF_FLAG_PUBLIC
        SCENEOBJECT_FIELD_RND_SEED_VAL                           = ObjectField.OBJECT_END + 0x1, // Size: 1, Flags: UF_FLAG_PUBLIC
        SCENEOBJECT_FIELD_CREATED_BY                             = ObjectField.OBJECT_END + 0x2, // Size: 2, Flags: UF_FLAG_PUBLIC
        SCENEOBJECT_FIELD_CREATED_BY2,
        SCENEOBJECT_FIELD_SCENE_TYPE                             = ObjectField.OBJECT_END + 0x4, // Size: 1, Flags: UF_FLAG_PUBLIC
        SCENEOBJECT_FIELD_END                                    = ObjectField.OBJECT_END + 0x5
    };
}
