using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

// This file is automatically generated, DO NOT EDIT

namespace WowPacketParserModule.V3_4_0_45166.UpdateFields.V1_15_0_52302
{
    public class ConversationActor : IConversationActor
    {
        public int Id { get; set; }
        public uint CreatureID { get; set; }
        public uint CreatureDisplayInfoID { get; set; }
        public WowGuid ActorGUID { get; set; }
        public uint Type { get; set; }

        // dummy required by implementation
        public uint NoActorObject { get; }
    }
}

