using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

// This file is automatically generated, DO NOT EDIT

namespace WowPacketParserModule.V9_0_1_36216.UpdateFields.V9_2_7_45114
{
    public class ItemMod : IItemMod
    {
        public int Value { get; set; }
        public byte Type { get; set; }
    }
}

