using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

// This file is automatically generated, DO NOT EDIT

namespace WowPacketParserModule.V9_0_1_36216.UpdateFields.V9_2_7_45114
{
    public class MawPower : IMawPower
    {
        public int Field_0 { get; set; }
        public int Field_4 { get; set; }
        public int Field_8 { get; set; }
    }
}

