using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

// This file is automatically generated, DO NOT EDIT

namespace WowPacketParserModule.V4_4_0_53627.UpdateFields.V4_4_0_53863
{
    public class SceneObjectData : ISceneObjectData
    {
        public System.Nullable<int> ScriptPackageID { get; set; }
        public System.Nullable<uint> RndSeedVal { get; set; }
        public WowGuid CreatedBy { get; set; }
        public System.Nullable<uint> SceneType { get; set; }
    }
}

