using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

// This file is automatically generated, DO NOT EDIT

namespace WowPacketParserModule.V4_4_0_53627.UpdateFields.V4_4_0_53863
{
    public class VisualAnim : IVisualAnim
    {
        public System.Nullable<uint> AnimationDataID { get; set; }
        public System.Nullable<uint> AnimKitID { get; set; }
        public System.Nullable<uint> AnimProgress { get; set; }
        public System.Nullable<bool> Field_C { get; set; }
    }
}

