using System.Collections.Generic;

namespace WowPacketParser.Enums.Version//.V4_3_0_15005
{
    public static partial class Opcodes
    {
        private static Dictionary<Opcode, int> _V4_3_0_opcodes = new Dictionary<Opcode, int>
        {
            {Opcode.CMSG_AUTH_SESSION, 0x1100},
            {Opcode.CMSG_BUY_ITEM, 0x1086},
            {Opcode.CMSG_CHAR_CREATE, 0x2A86},
            {Opcode.CMSG_CHAR_DELETE, 0x38A4},
            {Opcode.CMSG_GOSSIP_HELLO, 0x3622},
            {Opcode.CMSG_GMRESPONSE_CREATE_TICKET, 0x6C82},
            {Opcode.CMSG_GMRESPONSE_RESOLVE, 0x284},
            {Opcode.CMSG_GMSURVEY_SUBMIT, 0x70A6},
            {Opcode.CMSG_GMTICKET_DELETETICKET, 0x200},
            {Opcode.CMSG_GMTICKET_UPDATETEXT, 0x32A0},
            {Opcode.CMSG_GM_REPORT_LAG, 0x6CA6},
            {Opcode.CMSG_JOIN_CHANNEL, 0x074C},
            {Opcode.CMSG_KEEP_ALIVE, 0x66A0},
            {Opcode.CMSG_MESSAGECHAT_SAY, 0x136E},
            {Opcode.CMSG_MESSAGECHAT_YELL, 0x034C},
            {Opcode.CMSG_NAME_QUERY, 0x7220},
            {Opcode.CMSG_PING, 0x0100},
            {Opcode.CMSG_PLAYER_LOGIN, 0x0326},
            {Opcode.CMSG_QUERY_TIME, 0x5200},
            {Opcode.CMSG_QUESTGIVER_ACCEPT_QUEST, 0x6A82},
            {Opcode.CMSG_QUESTGIVER_REQUEST_REWARD, 0x66A6},
            {Opcode.CMSG_QUESTGIVER_STATUS_QUERY, 0x7E86},
            {Opcode.CMSG_QUESTGIVER_STATUS_MULTIPLE_QUERY, 0x1284},
            {Opcode.CMSG_QUESTGIVER_QUERY_QUEST, 0x2A06},
            {Opcode.CMSG_REQUEST_PET_INFO, 0x78A6},
            {Opcode.CMSG_SELL_ITEM, 0x3000},
            {Opcode.CMSG_TAXINODE_STATUS_QUERY, 0x6E02},
            {Opcode.CMSG_TIME_SYNC_RESP, 0x7293},
            {Opcode.CMSG_UPDATE_ACCOUNT_DATA, 0x02A0},
            {Opcode.SMSG_AUTH_CHALLENGE, 0x1723},
            {Opcode.SMSG_CHAR_CREATE, 0x2A82},
            {Opcode.SMSG_CHAR_DELETE, 0x2A02},
            {Opcode.SMSG_MESSAGECHAT, 0x3884},
            {Opcode.SMSG_NAME_QUERY_RESPONSE, 0x5E20},
            {Opcode.SMSG_PARTY_MEMBER_STATS_FULL, 0x5680},
            {Opcode.SMSG_PONG, 0x0302},
            {Opcode.SMSG_QUESTGIVER_QUEST_DETAILS, 0x2004},
            {Opcode.SMSG_QUESTGIVER_QUEST_FAILED, 0x60A2},
            {Opcode.SMSG_QUESTGIVER_QUEST_LIST, 0x5024},
            {Opcode.SMSG_QUESTLOG_FULL, 0x2A84},
            {Opcode.SMSG_QUESTUPDATE_COMPLETE, 0x6284},
            {Opcode.SMSG_QUESTUPDATE_FAILED, 0x5684},
            {Opcode.SMSG_TRAINER_BUY_FAILED, 0x34A2},
            {Opcode.SMSG_TRAINER_LIST, 0x4C80},
            {Opcode.SMSG_UPDATE_ACCOUNT_DATA_COMPLETE, 0x40A4},
            {Opcode.SMSG_GAMEOBJECT_QUERY_RESPONSE, 0x4CA6},
            {Opcode.SMSG_MONSTER_MOVE, 0x60A0},
            {Opcode.SMSG_MONSTER_MOVE_TRANSPORT, 0xEA4},

            // Tests
            {Opcode.TEST_43_34595, 0x8723},
            {Opcode.CMSG_LOAD_SCREEN, 0x0976},
            {Opcode.SMSG_MULTIPLE_PACKETS, 0x0723},


            // SF, TODO: Rename to "TC" opcode names
            {Opcode.SMSG_GUILD_FLAGGED_FOR_RENAME, 0x41A},
            {Opcode.CMSG_GUILD_CHANGE_NAME_REQUEST, 0x224C},
            {Opcode.SMSG_GUILD_CHANGE_NAME_RESULT, 0x241C},
            {Opcode.SMSG_GUILD_MEMBER_DAILY_RESET, 0x243E},
            {Opcode.CMSG_GUILD_REPLACE_GUILD_MASTER, 0x2A48},
            {Opcode.CMSG_GUILD_INVITE_BY_NAME, 0x4936},
            {Opcode.SMSG_GUILD_BANK_QUERY_RESULTS, 0x4C28}, // ???
            {Opcode.SMSG_GUILD_ROSTER_UPDATE, 0x4E3C}, // ???
            {Opcode.CMSG_DF_PROPOSAL_RESPONSE, 0x146},
            {Opcode.CMSG_DF_JOIN, 0x154},
            {Opcode.CMSG_DF_SET_ROLES, 0x304},
            {Opcode.CMSG_DF_TELEPORT, 0x366},
            {Opcode.CMSG_DF_BOOT_PLAYER_VOTE, 0x924},
            {Opcode.CMSG_DF_GET_SYSTEM_INFO, 0x926},
            {Opcode.CMSG_DF_SET_COMMENT, 0xB06},
            {Opcode.CMSG_DF_GET_JOIN_STATUS, 0x4144},
            {Opcode.CMSG_DF_LEAVE, 0x4306},
            {Opcode.CMSG_DF_SEARCH_JOIN, 0x4B36},
            {Opcode.CMSG_DF_SEARCH_LEAVE, 0x4B44},
            {Opcode.SMSG_SET_DF_FAST_LAUNCH_RESULT, 0x661C},
            {Opcode.SMSG_LFG_UPDATE_STATUS, 0x40A},
            {Opcode.CMSG_SET_EVERYONE_IS_ASSISTANT, 0x376},
            {Opcode.SMSG_RESET_COMPRESSION_CONTEXT, 0x1722}, // ??? must-implement
            {Opcode.SMSG_CUSTOM_LOAD_SCREEN, 0x2438}, // ???
            {Opcode.SMSG_GAME_EVENT_DEBUG_LOG, 0x2498},
            {Opcode.SMSG_SERVER_PERF, 0x2638}, // ???
            {Opcode.SMSG_FLOOD_DETECTED, 0x323},
            {Opcode.SMSG_AREA_TRIGGER_MOVEMENT_UPDATE, 0x438},
            {Opcode.SMSG_LFG_SLOT_INVALID, 0x263E},
            {Opcode.SMSG_XP_GAIN_ABORTED, 0x2C0C},
            {Opcode.SMSG_CHAT_IGNORED_ACCOUNT_MUTED, 0x2E3C},
            {Opcode.SMSG_MAP_OBJ_EVENTS, 0x2E88},
            {Opcode.SMSG_DUMP_RIDE_TICKETS_RESPONSE, 0x4C9A},
            {Opcode.SMSG_UPDATE_SERVER_PLAYER_POSITION, 0x4E9C},
            {Opcode.CMSG_BATTLEFIELD_LEAVE, 0x6203},
            {Opcode.SMSG_CLEAR_COOLDOWNS, 0x64BC},
            {Opcode.SMSG_LOOT_CONTENTS, 0x660A},
            {Opcode.SMSG_PRINT_NOTIFICATION, 0x669A},
            {Opcode.SMSG_GAME_OBJECT_ACTIVATE_ANIM_KIT, 0x6C0A},
            {Opcode.SMSG_LFG_UPDATE_STATUS_NONE, 0x6C28},
            {Opcode.SMSG_ACCOUNT_INFO_RESPONSE, 0x6C3A},
            {Opcode.CMSG_UNLEARN_SPECIALIZATION, 0x7003},
            {Opcode.SMSG_FAILED_PLAYER_CONDITION, 0x269A},
            {Opcode.SMSG_DONT_AUTO_PUSH_SPELLS_TO_ACTION_BAR, 0x26BE},
            {Opcode.SMSG_UPDATE_DUNGEON_ENCOUNTER_FOR_LOOT, 0x449C},
            {Opcode.SMSG_UPDATE_ACTION_BUTTONS, 0x461C},
            {Opcode.SMSG_MISSILE_CANCEL, 0x46B8},
            {Opcode.SMSG_ITEM_EXPIRE_PURCHASE_REFUND, 0x2C08},
            {Opcode.SMSG_VOID_ITEM_SWAP_RESPONSE, 0xC1C},
            {Opcode.CMSG_VOID_STORAGE_TRANSFER, 0x2011},
            {Opcode.SMSG_VOID_TRANSFER_RESULT, 0x2CA8},
            {Opcode.CMSG_UNLOCK_VOID_STORAGE, 0x2681},
            {Opcode.CMSG_SWAP_VOID_ITEM, 0x3291},
            {Opcode.CMSG_QUERY_VOID_STORAGE, 0x3431},
            {Opcode.SMSG_VOID_STORAGE_FAILED, 0x263C},
            {Opcode.SMSG_VOID_STORAGE_CONTENTS, 0x2698},
            {Opcode.SMSG_VOID_STORAGE_TRANSFER_CHANGES, 0x4CAE},
            {Opcode.CMSG_TRANSMOGRIFY_ITEMS, 0x3081},
            {Opcode.CMSG_GUILD_MEMBER_SEND_SOR_REQUEST, 0x88C},
            {Opcode.CMSG_SEND_SOR_REQUEST_VIA_BNET_ACCOUNT_ID, 0X4956},
            {Opcode.CMSG_SEND_SOR_REQUEST_VIA_ADDRESS, 0x4B16},
            {Opcode.SMSG_SOR_START_EXPERIENCE_INCOMPLETE, 0x4C8C},

        };
    }
}
