using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

// This file is automatically generated, DO NOT EDIT

namespace WowPacketParserModule.V10_0_0_46181.UpdateFields.V10_0_5_47777
{
    public class ReplayedQuest : IReplayedQuest
    {
        public System.Nullable<int> QuestID { get; set; }
        public System.Nullable<uint> ReplayTime { get; set; }
    }
}

