using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

// This file is automatically generated, DO NOT EDIT

namespace WowPacketParserModule.V3_4_0_45166.UpdateFields.V3_4_1_47014
{
    public class SceneObjectData : ISceneObjectData
    {
        public System.Nullable<int> ScriptPackageID { get; set; }
        public System.Nullable<uint> RndSeedVal { get; set; }
        public WowGuid CreatedBy { get; set; }
        public System.Nullable<uint> SceneType { get; set; }
    }
}

