// <auto-generated>
// DO NOT EDIT
// </auto-generated>

using System.CodeDom.Compiler;
using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

namespace WowPacketParserModule.V11_0_0_55666.UpdateFields.V11_2_7_64632
{
    [GeneratedCode("UpdateFieldCodeGenerator.Formats.WowPacketParserHandler", "1.0.0.0")]
    public class AreaTriggerPolygon : IAreaTriggerPolygon
    {
        public System.Nullable<float> Height { get; set; }
        public System.Nullable<float> HeightTarget { get; set; }
        public DynamicUpdateField<System.Nullable<Vector2>> Vertices { get; } = new();
        public DynamicUpdateField<System.Nullable<Vector2>> VerticesTarget { get; } = new();
    }
}

