// <auto-generated>
// DO NOT EDIT
// </auto-generated>

using System.CodeDom.Compiler;
using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

namespace WowPacketParserModule.V11_0_0_55666.UpdateFields.V11_2_7_64632
{
    [GeneratedCode("UpdateFieldCodeGenerator.Formats.WowPacketParserHandler", "1.0.0.0")]
    public class PlayerHouseInfoComponentData : IPlayerHouseInfoComponentData
    {
        public WowGuid Field_40 { get; set; }
        public INeighborhoodCharter Charter { get; set; }
        public System.Nullable<byte> Field_178 { get; set; }
        public DynamicUpdateField<WowGuid> Field_8 { get; } = new();
        public DynamicUpdateField<IPlayerMirrorHouse> Houses { get; } = new();
        public DynamicUpdateField<WowGuid> Field_88 { get; } = new();
        public DynamicUpdateField<WowGuid> Field_C0 { get; } = new();
        public DynamicUpdateField<WowGuid> Field_F8 { get; } = new();
    }
}

