// <auto-generated>
// DO NOT EDIT
// </auto-generated>

using System.CodeDom.Compiler;
using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

namespace WowPacketParserModule.V11_0_0_55666.UpdateFields.V11_2_7_64632
{
    [GeneratedCode("UpdateFieldCodeGenerator.Formats.WowPacketParserHandler", "1.0.0.0")]
    public class ScaleCurve : IScaleCurve
    {
        public System.Nullable<uint> StartTimeOffset { get; set; }
        public System.Nullable<Vector2>[] Points { get; } = new System.Nullable<Vector2>[2];
        public System.Nullable<uint> ParameterCurve { get; set; }
        public System.Nullable<bool> OverrideActive { get; set; }
    }
}

