using WowPacketParser.Misc;
using WowPacketParser.Store.Objects.UpdateFields;

// This file is automatically generated, DO NOT EDIT

namespace WowPacketParserModule.V10_0_0_46181.UpdateFields.V10_2_0_52038
{
    public class SkillInfo : ISkillInfo
    {
        public System.Nullable<ushort>[] SkillLineID { get; } = new System.Nullable<ushort>[256];
        public System.Nullable<ushort>[] SkillStep { get; } = new System.Nullable<ushort>[256];
        public System.Nullable<ushort>[] SkillRank { get; } = new System.Nullable<ushort>[256];
        public System.Nullable<ushort>[] SkillStartingRank { get; } = new System.Nullable<ushort>[256];
        public System.Nullable<ushort>[] SkillMaxRank { get; } = new System.Nullable<ushort>[256];
        public System.Nullable<short>[] SkillTempBonus { get; } = new System.Nullable<short>[256];
        public System.Nullable<ushort>[] SkillPermBonus { get; } = new System.Nullable<ushort>[256];
    }
}

